[query] Reference Counting NDArrays
hail-is/hail pull request #10001
Opened 2021-02-05 20:28 UTC by johnc1231

This PR introduces reference counted ndarrays. 

This means that like arrays, ndarrays will now store a pointer inside of tuples / structs that points to their location. Unlike arrays, ndarrays will live outside of regions, allowing them to be moved between regions without copies by editing the reference count. 

TODO: Type up thorough outline of changes.

2021-02-05 20:29 UTC, tpoterba commented
woah, this is a small PR for this change! Nice!

2021-02-08 16:46 UTC, johnc1231 commented
Right now this passes all tests, but there are some `???`s in there that just never get triggered. Going to try and write tests that hit them before coming up with an implementation.

2021-02-08 23:46 UTC, johnc1231 commented
Basically done, I just have to go through and rewrite the LAPACK calls to use the new interface (so far I've only done so with NDArrayInverse). If you have any thoughts on the actual reference counting  @tpoterba, that can be reviewed.

2021-02-09 21:41 UTC, tpoterba requested changes
A couple minor things. Looks great otherwise.

2021-02-09 21:41 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
> +      case _ =>
you can just leave this case out, and when we add something out we'll get a better error (match error with the thing that failed to match)

2021-02-09 21:41 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/PCanonicalStruct.scala
> +  def loadField(offset: Long, fieldName: String): Long = {
don't add this -- it's pretty expensive to do a string lookup to do pointer arithmetic.

2021-02-09 21:54 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionPool.scala
> +  def allocateNDArray(nBytes: Long): Long = {
Yep, good point

2021-02-17 01:52 UTC, johnc1231 commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +          val (aAadrFirstElement, finish) = ndPT.constructDataFunction(shapeArray, stridesArray, cb, region.code)
I actually intended this to be "a addr first element", like the matrix is named a (that's the lapack argument name)

2021-02-17 14:43 UTC, johnc1231 commented
Ok, so this is all working now. The one thing that's not ideal is that we are losing copy free transposes right now, as I don't know how to have two ndarrays share the same data and keep the reference counts correct. In some sense I want the ndarray's data to be reference counted, not the stride / shape bits which are cheap to copy.

2021-02-17 16:21 UTC, johnc1231 commented
Benchmarks on this are not good, still investigating.

2021-02-18 23:45 UTC, johnc1231 commented
Fixing MakeNDArray to not double allocate cut my laptop benchmark time by more than 50%, it's only a bit slower than main now (~5-10%), so we should probably try and get it in. Feel free to review again when you get a chance.

2021-02-18 23:45 UTC, tpoterba commented
wow!

2021-02-19 15:41 UTC, tpoterba submitted a review, later dismissed

2021-02-19 15:41 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/PCanonicalStruct.scala
> +  def loadField(offset: Long, fieldName: String): Long = {
can we still get rid of this?

2021-02-19 15:42 UTC, johnc1231 commented on hail/src/main/scala/is/hail/types/physical/PCanonicalStruct.scala
> +  def loadField(offset: Long, fieldName: String): Long = {
Oh sorry i thought I did, will do now

2021-02-22 21:46 UTC, tpoterba requested changes

2021-02-22 21:46 UTC, tpoterba commented on hail/src/test/scala/is/hail/types/physical/PNDArraySuite.scala
> +        snd1.tcode[Long]
no tcode please! use a `store` method or something

2021-02-22 22:00 UTC, johnc1231 commented on hail/src/test/scala/is/hail/types/physical/PNDArraySuite.scala
> +        snd1.tcode[Long]
Fixed!

2021-02-22 22:04 UTC, tpoterba approved these changes
:shipit:

2021-02-23 16:37 UTC, merged