[k8s] add dataproc and pypi secrets to createNamespace
hail-is/hail pull request #10066
Opened 2021-02-18 22:22 UTC by daniel-goldstein

Secrets needed to dev deploy site.

2021-02-22 16:32 UTC, danking approved these changes

2021-02-22 16:33 UTC, danking requested changes
Hmm. PyPI shouldn't be needed by dev deploys or PR tests and I'm inclined to not expose them if not necessary.

2021-02-22 16:56 UTC, daniel-goldstein commented
Holding on this until #10056 goes in because it removes the need for pypi credentials in deploying site.

2021-02-26 01:25 UTC, danking approved these changes
In the future, if you apply the `WIP` or `Stacked PR` tags, CI will not merge the PR, even if it has an approved review and is passing the tests.

2021-02-26 01:55 UTC, merged