[libhail] SArray and SArrayValue
hail-is/hail pull request #10128
Opened 2021-03-01 21:00 UTC by johnc1231

Just laying out the type hierarchy, wanted to PR to check if I was doing class hierarchies / inheritance in idiomatic C++. 

Also wanted to check if the destructors for `SValues` need to do anything special. I assume they don't free the memory of the underlying Values, as we can't know whether those values are used more than once, right?

2021-03-01 21:18 UTC, cseed requested changes

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/stype.cpp
> +SArray::SArray(const Type *type, const SType *elementType)
`element_type`, variables use snake case.

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/stype.cpp
> +SCanonicalArray::SCanonicalArray(const Type *type, const SType *elementType)
Same.

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/stype.hpp
> +    static const Tag self_tag = SType::Tag::ARRAY;
This won't work as it stands.  Only concrete members of the hierarchy can have tags, so we shouldn't have this, and there should be a `Tag::CANONICAL_ARRAY`.

There is a question if we should have SArray at all.  If you want to be able to do `isa<SArray>(stype)` or `cast<SArray>(stype)`, then we enhance the casting stuff to support non-concrete intermediate classes (I would probably avoid concrete intermediate classes for now).

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +SCanonicalArrayValue::SCanonicalArrayValue(const SArray *stype, llvm::Value *length, llvm::Value *missing, llvm::Value *data)
`stype` should be a `SCanonicalArray`, no?

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +SCanonicalArrayValue::getLength(TypeContext *tc) {
Members are snake case: `get_length`.

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/svalue.hpp
> +  virtual SInt64 getLength()=0;
Spaces: `...() = 0`.

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/svalue.hpp
> +    llvm::Value *length;
Don't  you need the missing pointer here, too?

2021-03-01 21:18 UTC, cseed commented on libhail/src/hail/query/backend/svalue.hpp
> +  static const Tag self_tag = SValue::Tag::ARRAY;
Same comments as SArray.

2021-03-18 15:21 UTC, cseed requested changes
Mostly formatting, naming, etc.  Code itself looks good.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/compile.cpp
> +  auto arraySValue = cast<SArrayValue>(arrayDataValue.svalue);
Variables are snake_case.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/compile.cpp
> +  return EmitValue(arrayDataValue.missing, arraySValue->get_length(&this->tc));
You don't need to use `this->`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/stype.hpp
> +class SCanonicalArray : public SType{
Space before `{`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/stype.hpp
> +  public:
Access specifiers are flush with the class definition and indent is 2.  So:

```
class SCanonicalArray :  public SType {
public:
  static const Tag ...
}
```

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +#include <stdint.h>
Prefer C++ headers: `#include <cstdint>`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +  // TODO: Implement?
Nothing needed.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +SInt64Value*
Space before *.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +SCanonicalArrayValue::get_length(TypeContext *tc) const {
Use reference when the pointer can't be null.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +  auto returnType = new SInt64(tc->tint32);
`return_type`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +  auto stride_value = llvm::ConstantInt::get(llvm::Type::getInt64Ty(cf.llvm_context), static_cast<uint64_t>(this->stype->element_stride));
I don't think you need the static cast here.  Also, no, `this->`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.hpp
> +  SArrayValue(const SCanonicalArray *stype): SValue(self_tag, stype), stype(stype) {};
No semi after function definition.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.hpp
> +  virtual SInt64Value* get_length(TypeContext *tc) const = 0;
`type *function()` not `type* function()`.

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/ir_type.cpp
> +  auto inferedChild = infer(x->get_child(0));
`infered_child` (maybe `child_type` is better?)

2021-03-18 15:21 UTC, cseed commented on libhail/src/hail/query/backend/svalue.cpp
> +  return this->stype->element_type->load_from_address(cf, element_addr);
No `this->` needed.

2021-05-07 14:20 UTC, johnc1231 commented
Bump @cseed

2021-06-01 14:39 UTC, johnc1231 commented
Bump @cseed

2022-02-24 16:18 UTC, danking commented
I'm closing this because its so old. We can start a new PR when we are ready to revisit this.

2022-02-24 16:18 UTC, closed without merging