[batch] add more logs and do not wait for asyncgens
hail-is/hail pull request #10136
Opened 2021-03-03 18:29 UTC by danking

I think there is some unresolved issue with asyncgen shutdown that is keeping
workers alive. This is not an issue in worker because worker calls sys.exit
which forcibly stops execution. cc: @daniel-goldstein @jigold.

2021-03-03 18:29 UTC, danking commented
Also: we called shutdown twice

2021-03-03 19:20 UTC, jigold requested changes

2021-03-03 19:20 UTC, jigold commented on batch/batch/worker/worker.py
> +            log.info(f'worker shutdown')
You have to get rid of the fstrings in all your log statements.

2021-03-03 19:50 UTC, jigold approved these changes

2021-03-09 14:18 UTC, jigold approved these changes

2021-03-09 21:46 UTC, merged