[datasets] add fixed gnomAD pext Hail Table
hail-is/hail pull request #10169
Opened 2021-03-10 00:52 UTC by pwc2

Adds fixed gnomAD annotation-level pext Hail Table (see #9955) to datasets.

2021-03-10 14:59 UTC, nawatts commented
I think the gnomAD group would probably prefer Hail point to the `gcp-public-data--gnomad` version of this dataset once that is updated.

@gtiao

2021-03-10 20:29 UTC, danking commented
I'll wait for Grace to chime in about the desired public location.

2021-03-11 20:35 UTC, gtiao commented
Yep, just waiting on final (unrelated) fixes to go through on the v3.1.1
nuclear variant release files before pinging them about copying over all
our changed files.



On Wed, Mar 10, 2021 at 3:29 PM Dan King ***@***.***> wrote:

> I'll wait for Grace to chime in about the desired public location.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hail-is/hail/pull/10169#issuecomment-796049879>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNSGHRVFLHDPK26N3MKTXLTC7CBTANCNFSM4Y42HNKA>
> .
>

2021-03-11 21:13 UTC, danking requested changes
Let's wait for the v3.1.1 release

2021-03-31 17:02 UTC, danking commented
@gtiao I think the `gcp-public-data--gnomad` bucket still hasn't been updated. Do you have a tentative date for the update?

2021-04-15 18:37 UTC, nawatts commented
It looks like `gs://gcp-public-data--gnomad/papers/2019-tx-annotation/pre_computed/all.possible.snvs.tx_annotated.021520.ht` has been updated now.

2021-04-15 18:40 UTC, danking commented
Awesome, thanks for the close attention, @nawatts ! @pwc2 let's update the path and get this merged!

2021-04-15 19:32 UTC, pwc2 commented
Just updated the path, should be good now.

2021-04-15 20:30 UTC, danking approved these changes

2021-04-15 20:53 UTC, merged