[query] Include info field key in parse error
hail-is/hail pull request #10211
Opened 2021-03-23 14:13 UTC by tpoterba

2021-03-24 15:12 UTC, johnc1231 approved these changes

2021-03-24 15:18 UTC, johnc1231 requested changes

2021-03-24 15:18 UTC, johnc1231 commented on hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
> +          case e => throw e
Delete this line. Don't catch something just to throw it.

2021-03-24 15:19 UTC, johnc1231 commented on hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
> +          case e => throw e
This is also the cause of your compilation error. Scala views doing this as a mistake.

2021-04-07 20:06 UTC, tpoterba commented
addressed, sorry I lost track of this...

2021-04-07 21:53 UTC, johnc1231 approved these changes

2021-04-07 22:19 UTC, merged