[terraform] fixes
hail-is/hail pull request #10246
Opened 2021-03-29 21:49 UTC by danking

@cseed, I want to add a new bucket for Hail Query to use for its own purposes. I tried to add it to
Terraform. I ran into some issues which I've fixed here.

Additionally, when I run `terraform plan -var-file="$HOME/.hail/global.tfvars`, it claims I need to
create all 82 resources. Do you know what is wrong? I thought terraform would recognize our, for
example, our MySQL database.

2021-03-31 16:24 UTC, cseed requested changes

2021-03-31 16:24 UTC, cseed commented on infra/README.md
> +  file.
I'm not sure I recommend that.  This wasn't intended to be 1-shot, but we eventually need to get things set up so changes to the terraform rules get applied automatically, so you'll need to keep around the terraform service account and Terraform state (which is created by `terraform apply`)

2021-03-31 16:25 UTC, cseed commented
> Additionally, when I run terraform plan -var-file="$HOME/.hail/global.tfvars, it claims I need to create all 82 resources. Do you know what is wrong? I thought terraform would recognize our, for example, our MySQL database.

Might be easier to explain the Terraform model in person.

2021-04-05 21:25 UTC, danking commented
I removed the objectionable verbiage.

2021-04-08 20:22 UTC, danking commented
bump

2021-04-21 22:01 UTC, danking commented
bump @cseed

2021-04-21 22:05 UTC, cseed approved these changes
Oops, sorry!

2021-04-21 22:38 UTC, merged