[query] Push FS through EmitFunctionBuilder
hail-is/hail pull request #10326
Opened 2021-04-14 17:45 UTC by tpoterba

2021-04-15 22:57 UTC, danking reviewed
I'm good with the changes to service code. Should someone from compilers team do a once over of the rest?

2021-04-15 22:57 UTC, danking commented on hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
> -    _staticFS
love it

2021-04-15 23:09 UTC, danking requested changes
x

2021-04-16 14:07 UTC, tpoterba commented
Good call. Assigning to Chris for another look, will move assignee.

2021-04-16 14:08 UTC, tpoterba commented
@chrisvittal - the motivation for this change is that we don't want to serialize the FS in the compiled function because it contains secrets. Instead, clients who call compiled functions should pass in the FS.

2021-04-16 16:02 UTC, chrisvittal approved these changes
lgtm

2021-04-16 21:33 UTC, merged