[query]  StreamLen needs to consume elements
hail-is/hail pull request #10330
Opened 2021-04-15 15:42 UTC by johnc1231

We will get errors about methods not being well formed if we don't define every label on an IEmitCode, so we have to consume each one even if we  don't do anything with it. 

I also moved `StreamLen` to `emitI`, because we were pointlessly switching back and forth from `EmitCode` to `IEmitCode`

2021-04-15 15:42 UTC, johnc1231 commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +                producer.element.toI(cb).consume(cb, {}, _ => {})
The diff makes it hard to see, but this is the single new interesting line.

2021-04-15 16:18 UTC, tpoterba commented
can we add the test in here?

2021-04-15 16:18 UTC, tpoterba requested changes
test

2021-04-15 17:55 UTC, johnc1231 commented
Ah, I was hoping the pca tests would start passing on the local backend with this change, but there are of course pruner issues. I'll have to try and craft a test that runs into this error.

2021-04-16 14:11 UTC, tpoterba commented
```scala
  @Test def testStreamLenUnconsumedInnerStream(): Unit = {
    assertEvalsTo(StreamLen(
      mapIR(StreamGrouped(filterIR(rangeIR(10))(x => x.cne(0)), 3))( group => ToArray(group))
    ), 3)
  }

```

2021-04-16 14:12 UTC, tpoterba commented
(can throw that in EmitStreamSuite)

2021-04-26 18:02 UTC, tpoterba approved these changes

2021-04-26 20:16 UTC, johnc1231 commented
@tpoterba That test doesn't pass, even with this fix:

```
2021-04-26 15:57:13 Hail: INFO: Running Hail version 0.2.65-77eb6e1a1cf4
2021-04-26 15:57:14 Hail: ERROR: error from strategy JvmCompile

java.lang.RuntimeException: unrealizable value unused asymmetrically: eos=false, ped=true

	at is.hail.expr.ir.streams.StreamProducer$.defineUnusedLabels(EmitStream.scala:29)
	at is.hail.expr.ir.Emit.$anonfun$emitI$68(Emit.scala:1080)
	at is.hail.expr.ir.IEmitCodeGen.map(Emit.scala:304)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:1065)
	at is.hail.expr.ir.Emit.emitInNewBuilder$1(Emit.scala:674)
	at is.hail.expr.ir.Emit.$anonfun$emitI$26(Emit.scala:816)
	at is.hail.expr.ir.EmitCode$.fromI(Emit.scala:391)
	at is.hail.expr.ir.Emit.$anonfun$emitI$25(Emit.scala:816)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:815)
	at is.hail.expr.ir.Emit$.$anonfun$apply$4(Emit.scala:99)
	at is.hail.expr.ir.EmitCodeBuilder$.scoped(EmitCodeBuilder.scala:19)
	at is.hail.expr.ir.EmitCodeBuilder$.scopedCode(EmitCodeBuilder.scala:24)
	at is.hail.expr.ir.EmitMethodBuilder.emitWithBuilder(EmitClassBuilder.scala:1044)
	at is.hail.expr.ir.WrappedEmitMethodBuilder.emitWithBuilder(EmitClassBuilder.scala:1095)
	at is.hail.expr.ir.WrappedEmitMethodBuilder.emitWithBuilder$(EmitClassBuilder.scala:1095)
	at is.hail.expr.ir.EmitFunctionBuilder.emitWithBuilder(EmitClassBuilder.scala:1192)
	at is.hail.expr.ir.Emit$.apply(Emit.scala:97)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:78)
	at is.hail.TestUtils$.eval(TestUtils.scala:256)
	at is.hail.TestUtils$.$anonfun$assertEvalsTo$5(TestUtils.scala:366)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:289)
	at is.hail.TestUtils$.$anonfun$assertEvalsTo$4(TestUtils.scala:348)
	at is.hail.TestUtils$.$anonfun$assertEvalsTo$4$adapted(TestUtils.scala:339)
	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:618)
	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:618)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
	at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:46)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:276)
	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$1(ExecuteContext.scala:40)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:39)
	at is.hail.TestUtils$.assertEvalsTo(TestUtils.scala:339)
	at is.hail.TestUtils$.assertEvalsTo(TestUtils.scala:314)
	at is.hail.expr.ir.IRSuite.testStreamLenUnconsumedInnerStream(IRSuite.scala:1800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

2021-04-26 23:06 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +                case SStreamCode(_, nested) => StreamProducer.defineUnusedLabels(producer, mb)
should be `defineUnusedLabels(nested, mb)`

2021-04-26 23:06 UTC, tpoterba commented
I think my comment may fix.

2021-04-27 12:17 UTC, johnc1231 commented
Yup, good catch.

2021-04-27 12:48 UTC, merged