[ci] allow Dockerfile to come from inputs
hail-is/hail pull request #10354
Opened 2021-04-21 17:52 UTC by danking

2021-04-21 18:42 UTC, daniel-goldstein approved these changes
How did this work before…

2021-04-21 18:46 UTC, danking commented
The docker file always came directly from the repository rather than from the inputs.

2021-04-21 18:53 UTC, daniel-goldstein requested changes
Some dockerfiles (e.g. Grafana) depend on a templated input file to render the Dockerfile. How could we have been rendering the Dockerfile before bringing in those inputs?

2021-04-21 18:53 UTC, daniel-goldstein commented on ci/test/resources/build.yaml
> +      - code
Isn't this from the other PR?

2021-04-21 19:29 UTC, danking commented
Grafana's Dockerfile is templated, but the template, `grafana/Dockerfile.nginx` came from the repository.

2021-04-21 19:29 UTC, danking commented on ci/test/resources/build.yaml
> +      - code
oh yep, that should be copy_files

2021-04-21 19:31 UTC, daniel-goldstein commented
Ah right, the dockerfile isn't actually used until after the inputs are brought in.

2021-04-22 21:20 UTC, danking reviewed
FYI Daniel, I got super frustrated trying to make this backwards compatible, so I just added a buildImage2 step, copied buildImage and removed all the unnecessary input manipulation and repository cloning.

After this PR and the next one go in, I can remove buildImage and rename buildImage2 to buildImage again.

2021-04-23 13:18 UTC, danking commented
@daniel-goldstein ok fixed!

2021-04-23 17:28 UTC, daniel-goldstein approved these changes
LGTM

2021-04-23 20:18 UTC, merged