[query]  NDArray Based Logistic Regression Round 1
hail-is/hail pull request #10469
Opened 2021-05-07 20:19 UTC by johnc1231

This PR reimplements the Wald and LRT test types of hail's logistic regression rows in terms of ndarrays. It is not yet in a state where it should replace hail's current Breeze based logistic regression since:

1. I still have to implement the `'firth'` and `'score'` test types (there's some extra work to implement Firth specifically that's going to mean adding a new ndarray method)
2. It is slower than Hail's Breeze based logistic regression.

I'd still like to get it in its current state, as it's still a feature add to the local and service backends, and I intend to follow up by adding a benchmark for this to track performance changes. 

This PR also fixes two bugs I found along the way:

1. In Python, `TailLoop._compute_type` was not recursively calling `_compute_type` on its params, which was a mistake. 
2. TailLoop creates bindings, but didn't have a `PruneDeadFields` rule. I added one based on the `Let` rule we already had.

2021-05-10 20:14 UTC, patrick-schultz submitted a review, later dismissed
Nice work John!

2021-05-11 13:58 UTC, johnc1231 commented on hail/python/hail/methods/statgen.py
> +            fisher = X.T @ (X * (mu * (1 - mu)).reshape(-1, 1))
Thanks, will look into this / maybe discuss at linalg meeting.

2021-05-11 13:58 UTC, johnc1231 commented on hail/python/hail/methods/statgen.py
> +        b = hl.nd.array(hl.array([y.sum()/n]).extend(hl.zeros(hl.int32(m - 1)).map(lambda e: hl.float64(e))))
You're right, fixed.

2021-05-11 20:28 UTC, patrick-schultz requested changes

2021-05-12 12:06 UTC, johnc1231 commented on hail/python/hail/methods/statgen.py
> +        b = hl.nd.hstack([hl.nd.array([hl.log(y.sum() / n)]), hl.nd.zeros((hl.int32(m - 1)))])
Fixed, thanks for checking thoroughly. I hate that tests don't catch this.

2021-05-13 19:31 UTC, patrick-schultz approved these changes

2021-05-13 20:01 UTC, merged