[compiler] Some groundwork for SStackStruct
hail-is/hail pull request #10490
Opened 2021-05-14 21:23 UTC by tpoterba

2021-05-21 15:10 UTC, tpoterba commented
Benchmarks show that this doesn't change performance, with the exception of making linear_regression_rows_nd about 4x slower. the unreliability of ndarray performance is being solved separately.

2021-05-24 12:05 UTC, tpoterba commented
ready for review!

2021-05-24 19:22 UTC, chrisvittal requested changes

2021-05-24 19:22 UTC, chrisvittal commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStackStruct.scala
> +  def code: Code[_] = throw new UnsupportedOperationException
This should be unnecessary.

2021-06-01 17:02 UTC, tpoterba commented
Bump. This is ready to go and is the base of the SType stack I have open.

2021-06-01 17:13 UTC, chrisvittal approved these changes
LTGM

2021-06-01 17:40 UTC, merged