[compiler] Add SUnreachable SType for NA / Die
hail-is/hail pull request #10539
Opened 2021-06-01 13:14 UTC by tpoterba

While only used in a few places, this helps us generate
much better code in the case where we emit error-checking
IRs as below:

```
If
  <error_condition>
  Die err_msg
  <value we want>
```

The code generator for the `If` node uses `SType.canonical` to
choose its result type, and casts both consequent and alternate
values to that type. We want the stype of the result here to be
the type of the alternate `<value we want>`, which we can achieve
by adding unreachable types/codes for the `SType.canonical` logic.

2021-06-28 12:09 UTC, tpoterba commented
still chasing down ndarray regressions...
```
                             linear_regression_rows_nd     246.9%     50.654    125.085      100.0%            8            8
                      ndarray_matmul_float64_benchmark     165.8%      4.999      8.290      100.0%            1            1
  hwe_normalized_pca_blanczos_small_data_10_iterations     128.7%     54.708     70.395      100.0%            8            8
  ```

2021-06-28 18:31 UTC, tpoterba commented
Benchmarks look good now.

2021-06-29 14:52 UTC, patrick-schultz requested changes
This is great. Just a few minor things.

One conceptual comment: you described `SUnreachable` as a type representing a value that will never be constructed at runtime, i.e. a bottom type. But I think what you've actually built is something different, that may have other uses. Each virtual type has a designated "default value", and the corresponding `SUnreachable` type is a subtype which can only have that default value, with a compact (usually 0 bytes) runtime representation.

2021-06-29 14:52 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala
> +
extra newline

2021-06-29 17:05 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/SType.scala
> +  def _coerceOrCopy(cb: EmitCodeBuilder, region: Value[Region], value: SCode, deepCopy: Boolean): SCode
good call.

2021-06-29 17:12 UTC, tpoterba commented
> One conceptual comment: you described SUnreachable as a type representing a value that will never be constructed at runtime, i.e. a bottom type. But I think what you've actually built is something different, that may have other uses. Each virtual type has a designated "default value", and the corresponding SUnreachable type is a subtype which can only have that default value, with a compact (usually 0 bytes) runtime representation.

I do think the usages right now do fit this description - any usage of a SUnreachableCode will never be on a live path at runtime. I think any of the methods on SUnreachableCode/Value could safely be replaced with thrown exceptions. That's not to say there might be other applications this helps streamline! Do you have any specific ideas?

2021-06-29 17:23 UTC, patrick-schultz commented
I don't have any specific ideas, no. Just noticing that this seems to implement a stronger abstraction: a type for default values. I don't know of any cases where we use default values, other than unreachable values, but if there were, it looks like this could be used. Mostly, that seems simpler conceptually than "unreachable values", since it doesn't involve control flow.

2021-06-29 17:23 UTC, patrick-schultz approved these changes

2021-06-29 19:02 UTC, merged