[batch] Make error messages clearer in the UI and formatted correctly
hail-is/hail pull request #10545
Opened 2021-06-02 16:03 UTC by jigold

2021-06-02 16:04 UTC, jigold commented
I added the error for each container to the logs output. I think that's fine, but maybe we need separate section for errors?

2021-06-03 18:29 UTC, daniel-goldstein commented
I think the layout you have makes sense (grouping logs and errors under steps vs separate logs and errors sections), though I think it would be helpful to mark where the log ends and the error begins with subheaders, e.g.
# Main
## Log
## Errors

2021-06-03 18:30 UTC, daniel-goldstein requested changes
I think the layout you have makes sense (grouping logs and errors under steps vs separate logs and errors sections), though I think it would be helpful to mark where the log ends and the error begins with subheaders, e.g.
# Main
## Log
## Errors

where there's only an error header if there was an error and only a log header if there's a log to view

2021-06-03 21:05 UTC, daniel-goldstein approved these changes

2021-06-03 21:05 UTC, merged