[docs] Improve MatrixTable.entries docs
hail-is/hail pull request #10540
Opened 2021-06-01 16:49 UTC by tpoterba

2021-06-01 18:14 UTC, johnc1231 commented
Failing `make_docs`

2021-06-11 13:53 UTC, johnc1231 commented
Bump, failing a docs build

2021-06-11 13:54 UTC, tpoterba commented
thanks for the reminder!

2021-06-11 17:54 UTC, johnc1231 requested changes
One typo, otherwise looks good.

2021-06-11 17:54 UTC, johnc1231 commented on hail/python/hail/matrixtable.py
> +        has no filtered entries nad contains N rows and M columns, the table will contain
`nad` -> `and`

2021-06-24 17:46 UTC, johnc1231 commented
Bump. Tiny typo and will be good to go.

2021-07-13 18:00 UTC, johnc1231 approved these changes

2021-07-13 18:41 UTC, merged