[compiler] Rework SIndexablePointer into SVector
hail-is/hail pull request #10579
Opened 2021-06-10 16:14 UTC by chrisvittal

SVector replaces SIndexablePointer and is comprised of three (two if the element type is required) codes:
```
length: Code[Int]
elements: Code[Long]
missing: Option[Code[Long]] // if None if element is required
```

2021-06-10 16:15 UTC, chrisvittal commented
Once again totally broken until we can return code tuples with more than one code from `invokePCode`

2021-06-10 16:19 UTC, tpoterba requested changes
This change is hard to read with both rename and semantic changes. Can you separate those and do the semantic changes first, then the rename after?

2021-06-10 16:43 UTC, chrisvittal commented
Un-renamed

2021-06-10 16:49 UTC, tpoterba commented
thanks, much easier to read.

2021-06-10 19:36 UTC, tpoterba requested changes
Some comments, still thinking through the baseAddress stuff.

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> -          dictType.construct(finishOuter(cb))
actually, I think it's `coerceArrayCode`.

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
> +    val array = indexable.asInstanceOf[SIndexablePointerSettable]
This is invalid. Can't cast before the match.

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
> +    val array = indexable.asInstanceOf[SIndexablePointerSettable]
(just move it inside I think)

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
> +      case value: SIndexablePointerCode if !deepCopy => new SIndexablePointerCode(this, value.length, value.elements, value.missing)
This is invalid. Types might not match.

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
> +    val (length, elements, missing) = settables match {
Should assert that the missingness option-status is what we expect.

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
>    def codeTupleTypes(): IndexedSeq[TypeInfo[_]] = FastIndexedSeq(LongInfo)
needs update

2021-06-10 19:36 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
>    override def settableTupleTypes(): IndexedSeq[TypeInfo[_]] = FastIndexedSeq(LongInfo, IntInfo, LongInfo)
needs update

2021-06-11 04:01 UTC, chrisvittal reviewed
baseAddress is sound if the components came from a PType with the layout of a PCanonicalArray

2021-06-11 04:20 UTC, chrisvittal commented
Compared to the baseAddress stuff, a more exotic change would be to change the layout of a PCanonicalArray, as well as update the notion of a 'pointer' to a PCanonicalArray.

The result would be something like [sds](https://github.com/antirez/sds) which is a dynamic string library, where the public api works on char pointers, and all the metadata is kept in a prefix to that pointer.

2021-08-05 16:27 UTC, chrisvittal commented
I plan on reworking this entirely.

2021-08-05 16:27 UTC, closed without merging