[compiler] Use AsmTuple for multi-code SType return values
hail-is/hail pull request #10581
Opened 2021-06-10 22:16 UTC by chrisvittal

This removes the single code requirement (st.nCodes == 1) for methods
returning SCodes.

2021-06-10 22:17 UTC, chrisvittal commented
This the branch that involves the AsmTuple is not taken (obviously), but will be with the changes from #10579

2021-06-11 13:45 UTC, tpoterba requested changes
I think before we merge this, we need to have a sense of the performance impact. Just running the benchmarks on the SIndexablePointer changes will include performance changes from the new representation and the asmtuple change, so isolating it here sounds like a good idea. Let's change this PR so all pcode methods go through an asm tuple (even with 1 code) and see how affects benchmark timings.

2021-06-14 16:02 UTC, chrisvittal commented
Okay, we can benchmark now.

2021-06-14 16:43 UTC, tpoterba commented
submitting benchmarks now.

2021-06-14 16:46 UTC, chrisvittal commented
I should probably fix things first.

2021-06-14 17:08 UTC, chrisvittal commented
Getting IncompatibleClassChangeError and I don't know why.

2021-06-14 17:13 UTC, chrisvittal commented
Pushed up latest version.

2021-06-14 18:56 UTC, chrisvittal reviewed
One thing I'd like to maybe change after benchmarking and restoring the `nCodes == 1` optimizations.

2021-06-14 18:56 UTC, chrisvittal commented on hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
> +        cb += new VCode(L, L, null)
This is messy, but I'm not what sure the best way to improve it is.

2021-06-15 16:08 UTC, chrisvittal commented
Pretty sure this is ready for review

2021-06-17 13:09 UTC, tpoterba commented
oh, sorry, didn't pop up on my to-do since my old review hadn't been dismissed. looks good!

2021-06-17 13:09 UTC, tpoterba approved these changes

2021-06-17 13:46 UTC, merged