[query] NDArrays only reference count their underlying data, are no longer based on arrays
hail-is/hail pull request #10619
Opened 2021-06-25 21:01 UTC by johnc1231

2021-07-13 14:15 UTC, patrick-schultz submitted a review, later dismissed
This is a great change. I do have one high level design concern, that isn't really introduced by this PR, but this PR makes it easier to fix.

I think it's wrong for `RegionMemory` to have a dependency on `PNDArray`. I'd propose that instead of `allocateNDArrayData` et al, we have `allocateSharedChunk`, which returns the pointer to the beginning of the usable data (after the header), with methods like `getSharedChunkRefCount(ptr: Long)` which know to subtract an offset from the pointer.

2021-07-13 14:17 UTC, patrick-schultz requested changes
Comments above

2021-07-13 17:59 UTC, johnc1231 commented
Great comments, addressed both.

2021-07-14 13:13 UTC, patrick-schultz approved these changes

2021-07-14 13:14 UTC, merged