Chunk cache
hail-is/hail pull request #10618
Opened 2021-06-25 20:39 UTC by ammekk

Running test on chunk cache draft

2021-06-29 15:19 UTC, johnc1231 requested changes

2021-06-29 15:19 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionMemory.scala
>      val o = pool.getChunk(size)
To make this clearer, do something like `val (addr, bytesAllocated) = pool.getChunk(size)`

2021-06-29 15:19 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionMemory.scala
> +    val allocatedChunk = pool.getChunk(size + extra)
Same as above, structure like `val (a, b) = pool.getChunk(...)`

2021-06-29 15:19 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionMemory.scala
> +    val ndArraysToFree = new LongArrayBuilder()
Like Tim said, we should try not allocating an object here every time. Let's just make a `freeChunk` method that takes one long, and change `freeChunks` to just call `freeChunk` a bunch of times or something

2021-06-29 21:27 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionMemory.scala
>      val o = pool.getChunk(size)
Here too.

2021-06-30 17:47 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionPool.scala
> +  override def getChunk(pool: RegionPool, size: Long): (Long, Long) = {
Leave new lines between method names. Necessary for the whole file really, I just highlight some examples.

2021-06-30 17:48 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/RegionPool.scala
> +   def freeInLongArrayBuilder(pool: RegionPool, ab: LongArrayBuilder):Unit = {
These defs aren't indented the same way

2021-07-07 20:21 UTC, tpoterba commented
design looks great! Awesome work!

2021-07-07 20:35 UTC, johnc1231 requested changes

2021-07-07 20:35 UTC, johnc1231 commented on hail/src/test/scala/is/hail/annotations/RegionSuite.scala
> +  }
We talked in person about what this test should be. We want to look at the operations arrays to check that we use the cache when appropriate, and free when appropriate.

2021-07-07 20:54 UTC, tpoterba commented on hail/src/main/scala/is/hail/annotations/ChunkCache.scala
> +  def freeChunkFromMemory(pool: RegionPool, chunkPointer: Long):Unit = {
might be easier for a cache to take a pool in the constructor, rather than on every method

2021-07-08 02:28 UTC, johnc1231 submitted a review, later dismissed

2021-07-08 02:28 UTC, johnc1231 commented on hail/src/main/scala/is/hail/annotations/ChunkCache.scala
> +  }
This is maybe overkill, but I think I would assert size > 0 here. If we somehow get a size of 0 here, you'll have an infinite loop. It doesn't really make sense to free something that's 0 bytes, but it's a bug that's happened before and I'd rather we get an error than an infinite loop.

2021-07-08 21:54 UTC, johnc1231 approved these changes

2021-07-08 22:30 UTC, merged