use a r/w lock for pulling/deleting images
hail-is/hail pull request #10674
Opened 2021-07-16 20:09 UTC by daniel-goldstein

2021-07-16 21:17 UTC, danking requested changes

2021-07-16 21:17 UTC, danking commented on batch/batch/worker/worker.py
> +                        shutil.rmtree(image_path)
blocking_to_async(self.pool, shutil.rmtree, image_path)

2021-07-16 21:21 UTC, danking approved these changes

2021-07-17 01:37 UTC, daniel-goldstein commented
Blocked by the same filesystem deletion it's trying to solve. Force merging.

2021-07-17 01:37 UTC, merged