Fix LGT_TO_GT to be a registered function
hail-is/hail pull request #10703
Opened 2021-07-26 15:59 UTC by tpoterba

Now supports 0-ploid and haploid as well as diploid.

2021-07-26 16:00 UTC, tpoterba commented on hail/src/main/scala/is/hail/variant/Call.scala
> +  def allelePair(c: Call): Int = {
Changes here and in Genotype.scala are to remove the AllelePair value class, which made code generation much harder and also introduced unintentional allocation in at least once place.

2021-07-26 16:01 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
> +  def lgtToGT(cb: EmitCodeBuilder, localAlleles: SIndexableValue, errorID: Value[Int]): SCallCode = {
lgt_to_gt is a function that translates LGT (local gt) to GT (absolute gt) using the local alleles array. 

For instance, with LGT=0/2 and LA=[0,3,4], the GT is 0/4.

2021-07-26 19:28 UTC, johnc1231 commented
Read through and looks good. Just checking: this is just intended to be an internal registered function, not something for users to call, right?

2021-07-26 19:31 UTC, johnc1231 requested changes

2021-07-26 19:31 UTC, johnc1231 commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
> +          val indexableLen = localAlleles.loadLength()
Unused?

2021-07-27 14:47 UTC, tpoterba commented
> Read through and looks good. Just checking: this is just intended to be an internal registered function, not something for users to call, right?

Users may sometimes use this -- it was exposed through `hl.experimental` previously as part of the vcf combiner utilities, I just moved it to `hl.vds` (though it still exists at the old location for compatibility)

2021-07-27 16:06 UTC, johnc1231 submitted a review, later dismissed
If users can call, we should pass `errorId`s thoroughly I think. Two places you are just using `fatal`

2021-07-27 16:06 UTC, johnc1231 commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
> +      EmitCodeBuilder.scopedVoid(cb.emb)(cb => cb._fatal(s"ploidy above 2 is not currently supported")),
Should be `fatalWithID` and

2021-07-27 16:06 UTC, johnc1231 commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
> +          cb.ifx(j >= localAlleles.loadLength(), cb._fatal("invalid lgt_to_gt: allele "))
Should be `fatalWithId`

2021-07-27 16:09 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
> +          cb.ifx(j >= localAlleles.loadLength(), cb._fatal("invalid lgt_to_gt: allele "))
good catch, thanks!

2021-07-27 16:10 UTC, johnc1231 approved these changes

2021-07-27 17:30 UTC, merged