[hailtop.batch] More batch pool executor fixes
hail-is/hail pull request #10738
Opened 2021-08-02 19:34 UTC by jigold

A couple of fixes to batch pool executor to both get rid of orphaned running forever jobs and exception not retrieved errors:

- `asyncio.wait` does not retrieve results. I had to change waits to gathers with return_exceptions=True to get the behavior we want.
- A timeout error with `asyncio.wait_for` cancels the task automatically. Therefore, the previous code would never cancel the batch because the task was already "cancelled".
- I made `asyncio_cancel` idempotent and made sure we cancel the batch if the task has been cancelled to address the issue above. I added a check to see if the batch is running before cancelling. I'm ambivalent on whether this change is necessary.
- I added an explicit test now to make sure all batches are terminated. I think this is a good change, but the downstream consequences could be if this runs forever on a deploy (relies on an explicit timeout). Although, `test_hailtop_batch_*` has explicit timeouts. So I think we're good.

2021-08-02 19:51 UTC, danking submitted a review, later dismissed

2021-08-02 19:51 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
> +                await cancel_batch()
Isn't cancel idempotent and doesn't care if the batch is finished or not? We shouldn't add a round trip to check the status if unnecessary.

2021-08-02 19:51 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
> +        async def cancel_batch():
I think we should just add `self.batch.cancel` to the finally block of the fetch_coro. Cancelling a completed batch is fine. That keeps everything simple: if the fetch_coro is cancelled, the BatchPoolFuture has been cancelled.

2021-08-02 20:02 UTC, jigold commented
Not 100% sure I understood the last comment.

2021-08-02 21:08 UTC, danking submitted a review, later dismissed

2021-08-02 21:08 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
> +            await self.batch.cancel()
This only fires if someone calls async_result, right? I'm sorry I was a bit vague. When I said `fetch_coro`, I was thinking of `self._async_fetch_result`, which is the function called to start the fetch_coro. I think you add self.batch.cancel() to its finally block, then if fetch_coro is cancelled, the batch will be cancelled. The batch will also be cancelled if any error happens during result fetching or job waiting.

2021-08-06 20:03 UTC, danking requested changes

2021-08-06 20:03 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
>          await self.batch.cancel()
We should remove this as well because cancelling the fetch_coro (on the next line) will cancel the batch.

2021-08-06 20:03 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
>              return await asyncio.wait_for(self.fetch_coro, timeout=timeout)
We should shield the fetch_coro here. It's perfectly valid to call `.result` again after a timeout.

2021-08-06 21:20 UTC, danking approved these changes

2021-08-06 21:25 UTC, merged