[compiler] Infrastructure up to and including StoredSTypePType
hail-is/hail pull request #10742
Opened 2021-08-02 22:03 UTC by tpoterba

Don't use StoredStypePType yet.

2021-08-03 19:17 UTC, chrisvittal requested changes
I was wrong about the anonymous typecasts. Sorry.

2021-08-03 19:18 UTC, tpoterba commented
intellij definitely didn't catch it.

2021-08-04 16:00 UTC, tpoterba commented
fixed!

2021-08-04 16:45 UTC, chrisvittal approved these changes

2021-08-04 16:46 UTC, merged