[compiler] Lots of compiler and code size performance improvements
hail-is/hail pull request #10746
Opened 2021-08-04 13:32 UTC by tpoterba

Necessary for the big aggregate benchmark to pass (albeit more slowly) in benchmarks.

2021-08-04 13:33 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +        if (!ctx.inLoopCriticalPath.contains(x) && xs.forall(x => !ctx.inLoopCriticalPath.contains(x))) {
method splitter doesn't do well with lots of flat children -- splitting manually does better.

2021-08-04 13:33 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
> +              val fieldArrays = Array.fill(ts.fields.length)(new BoxedArrayBuilder[Type])
This stuff was a major performance hotspot.

2021-08-04 13:33 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
> +    val lazyBuffer = kb.getOrDefineLazyField[MemoryBufferWrapper](Code.newInstance[MemoryBufferWrapper](), ("AggregatorStateBufferWrapper"))
we weren't caching the way we thought.

2021-08-04 13:34 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
> +  private def extract(ir: IR, ab: BoxedArrayBuilder[(InitOp, PhysicalAggSig)], seqBuilder: BoxedArrayBuilder[IR], letBuilder: BoxedArrayBuilder[AggLet], memo: mutable.Map[IR, Int], result: IR, r: Req
Here we cache agg IRs by identity, which deduplicates counts.

2021-08-04 13:34 UTC, tpoterba commented on hail/src/main/scala/is/hail/lir/Blocks.scala
> +  private val blockIdx = {
java map is faster than scala.

2021-08-05 20:26 UTC, patrick-schultz submitted a review, later dismissed

2021-08-05 20:26 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
> +    (children, newChildren).zipped.foreach { case (r1, r2) =>
Oh cool, I hadn't realized how `zipped` was implemented. The argument to `foreach` is actually a 2-ary function, so you don't even need the `case`. That may be a performance improvement, but also makes it immediately clear that we're not allocating tuples. (Likewise for the other uses of `zipped` in this file.)

2021-08-05 20:26 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
> +    children.iterator.zip(rowIterator(a.asInstanceOf[Row])).foreach { case (r, f) => r.unionLiteral(f) }
`zipped`?

2021-08-06 17:56 UTC, tpoterba commented on hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
> +    children.iterator.zip(rowIterator(a.asInstanceOf[Row])).foreach { case (r, f) => r.unionLiteral(f) }
oops, missed one, thanks.

2021-08-09 20:25 UTC, patrick-schultz requested changes

2021-08-09 20:25 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
> +        val valueTypes = (names, as).zipped.map { case (name, a) =>
As discussed in person, function literals with `case` still force a tuple to be allocated.

2021-08-10 13:11 UTC, patrick-schultz approved these changes

2021-08-10 14:38 UTC, merged