[compiler] refactor PType.store, SType.coerceOrCopy to take/return values
hail-is/hail pull request #10848
Opened 2021-09-07 17:54 UTC by patrick-schultz

I didn't give very good names to all the introduced `memoize`s, but those will all go away as we push the refactoring through.

2021-09-07 18:27 UTC, johnc1231 commented
@patrick-schultz Lots of test failures

2021-09-07 18:28 UTC, patrick-schultz commented
Not surprising, looking

2021-09-07 20:20 UTC, patrick-schultz commented
Most of the failures were coming from `SUnreachableValue`s inheriting from both `SValue` and `SCode`, which has caused me problems before too. Since `SCode` will be going away, I just gave in and duplicated them all for now.

2021-09-08 15:42 UTC, johnc1231 requested changes

2021-09-08 15:42 UTC, johnc1231 commented on hail/src/main/scala/is/hail/types/physical/stypes/concrete/SInsertFieldsStruct.scala
> +        println(s"coerce ${value.st} to ${this}")
Remove `println`

2021-09-08 15:46 UTC, johnc1231 approved these changes

2021-09-08 19:15 UTC, merged