[query] add `pc_relate_ts` method (tall skinny implementation)
hail-is/hail pull request #10874
Opened 2021-09-13 21:59 UTC by pwc2

Adds the tall skinny (table of NDArrays) implementation of `pc_relate` and associated tests.

2021-09-24 17:43 UTC, patrick-schultz requested changes
This is so cool, great work! Here are some initial thoughts.

2021-09-24 17:43 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/pc_relate_ts.py
> +    mu = beta.select(ndarray=((0.5 * V * S) @ beta.ndarray).T.map(lambda mu: hl.if_else(_bad_mu(mu, min_individual_maf), nan, mu)))
It looks like from this point on, `beta` `S` and `V` aren't used again, only `mu`. Is that right?

You shouldn't need to actually materialize the `hstack`s. From some quick scratch work, it looks like you can equivalently use
```
g = g.annotate(af=g.ndarray.sum(1) / (2 * n))
mu = g.select(ndarray=g.af + 0.5 * g.ndarray @ V0 @ V0.T).map(lambda mu: hl.if_else(_bad_mu(mu, min_individual_maf), nan, mu)))
```
which feels more intuitive to me as well (mean center, compute PCs and project, then add the mean back). Happy to go through the math with you.

2021-09-24 17:43 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/pc_relate_ts.py
> +    return A.aggregate(hl.agg.ndarray_sum(A.ndarray), _localize=False)
Even better, we might want to add an aggregator that uses the blas function `dsyrk` for computing gram matrices. It should be about a factor of 2 faster than the `dgemm` call.

2021-09-24 18:03 UTC, johnc1231 commented on hail/python/hail/methods/relatedness/pc_relate_ts.py
> +    return A.aggregate(hl.agg.ndarray_sum(A.ndarray), _localize=False)
Yeah, that is better. Should we expose a `gram` method or the like that calls that thing besides having it in an aggregator? I feel like it's common operation, but it's so much more readable to just write `A.T @ A`. Maybe it's a simplify rule we should add?

2021-09-24 18:10 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/pc_relate_ts.py
> +    return A.aggregate(hl.agg.ndarray_sum(A.ndarray), _localize=False)
Yeah, I think we should expose it explicitly so experts can ensure the efficient implementation is used, while also making a best effort to optimize all code. In this case, I guess just looking for the pattern `ApplyAggOp(..., Seq(NDArrayTranspose(Ref(x)), Ref(x)), NDArrayMultiplySum)`.

2022-02-24 16:51 UTC, danking commented
@pwc2 , I'm gonna close this because PR has trouble with old PRs. Can we revisit this when the PCA project is wrapped up?

2022-02-24 16:51 UTC, closed without merging

2022-02-24 17:02 UTC, pwc2 commented
> @pwc2 , I'm gonna close this because PR has trouble with old PRs. Can we revisit this when the PCA project is wrapped up?

Yeah, sounds good