[compiler] remove SCode
hail-is/hail pull request #11011
Opened 2021-10-25 13:11 UTC by patrick-schultz

~Stacked on #11008~

2021-11-17 20:50 UTC, johnc1231 requested changes

2021-11-17 20:50 UTC, johnc1231 commented on hail/src/main/scala/is/hail/lir/X.scala
> +   val stack = Thread.currentThread().getStackTrace
Need to recomment this!

2021-11-17 20:53 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/lir/X.scala
> +   val stack = Thread.currentThread().getStackTrace
Whoops, thanks!

2022-01-19 16:59 UTC, patrick-schultz commented
Will try to redo this in a few smaller pieces.

2022-01-19 16:59 UTC, closed without merging