[query] New Shuffler
hail-is/hail pull request #11050
Opened 2021-11-08 21:33 UTC by johnc1231

PRing for test suite, but it's mostly working. 

Todo:

- [ ] Optimization for already sorted tables
- [ ] Handle sort by descending
- [ ] Handle tables with no partitions

2021-11-15 21:47 UTC, johnc1231 commented
I assigned both Tim and Patrick for this since we've been talking about it. It still has prints and stuff in it that I'm using to debug / and experiment, but I think it's now in a place where a review would be welcome.

2021-12-02 19:04 UTC, patrick-schultz requested changes
Mostly looks good, though I found it quite hard to read. A few more comments in the big sort method might help.

2021-12-02 19:18 UTC, johnc1231 commented on hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
> +    val oversamplingNum = 1
Ah, sorry. Yeah I have to increase, right now we are basically not using this.

2021-12-13 17:14 UTC, johnc1231 commented
@patrick-schultz I addressed your comments, would be happy to take more steps to make code clearer if you see some. Otherwise I'd like if you could check that you're now happy with how `oversamplingNum` is being used.

2021-12-17 15:39 UTC, patrick-schultz requested changes
With one fix to the oversampling logic (and getting tests passing), I'm good with merging this.

2021-12-17 15:39 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
> +              val sortedSampling = ToArray(mapIR(StreamRange(0, ArrayLen(sortedOversampling), I32(oversamplingNum))) { idx =>
I believe the range you want is `range(oversamplingNum - 1, length, oversamplingNum)`. For example, say `branchingFactor = 4` and `oversamplingNum = 3`. Then we collect `4*3-1 = 11` "oversamples", and we want to extract `4-1` evenly spaced samples:
```
[*, *, 2, *, *, 5, *, *, 8, *, *]
```

2022-01-05 15:55 UTC, johnc1231 commented
Ok Patrick, back to you. I realized `PruneDeadFields` was disabled in my PR, I renabled it, and had to adjust the prune rule for `AggFold`.

2022-01-10 18:23 UTC, patrick-schultz approved these changes
Sorry I've been so slow reviewing, this is great work!

2022-01-10 19:15 UTC, merged