[batch] Use premium SSD data disks in Azure
hail-is/hail pull request #11123
Opened 2021-12-02 22:08 UTC by jigold

2021-12-09 18:12 UTC, jigold commented
Bump. This needs to go into production before we do massive scale tests since Standard_SSD charges per IO operation.

2021-12-09 18:14 UTC, jigold commented
Actually, this seems to cause instances to hang when using an actual data disk. I'm going to put the WIP tag on until I get a chance to investigate

2021-12-10 15:52 UTC, danking requested changes
dismiss when you're ready for a new look

2021-12-13 23:35 UTC, jigold commented
I'm not sure if we need a Premium SSD on the os disk or not.

2021-12-15 03:20 UTC, jigold commented
See question, but otherwise tests are passing.

2021-12-15 03:21 UTC, jigold commented on batch/batch/cloud/azure/resource_utils.py
> +        additive_features = 'ds'
d means use a local SSD data disk. s means support premium disks.

2021-12-15 14:45 UTC, danking submitted a review, later dismissed
x

2021-12-20 23:09 UTC, danking approved these changes

2021-12-21 00:15 UTC, merged