[aiogoogle] Use anonymous credentials when not in GCE
hail-is/hail pull request #11207
Opened 2022-01-07 15:13 UTC by daniel-goldstein

and give the user a warning that they might want to log in. Anonymous credentials will allow us to access public buckets without authenticating, which was not possible until now. I contemplated whether we should only suggest the login if they've received a 401 but I assume most everyone using this will want to be authenticated and we already log a warning as it is.

This is reasonably testable, but I couldn't find where it should go. Does `test_fs` test credential-loading at all?

2022-01-07 15:15 UTC, danking requested changes

2022-01-07 15:15 UTC, danking commented on hail/python/hailtop/aiocloud/aiogoogle/credentials.py
> +        pass
You can just use `AnonymousCloudCredentials` from aiocloud.common.

2022-01-07 15:19 UTC, danking commented
AFAIK, we don't test credential discovery. A little tricky because you want to modify the file system, which isn't kosher on a developer's laptop. Also not clear what to do about, e.g., the metadata server. You could mock it, but I've always felt pretty negative about the value of mocking. You might try adding some build.yaml steps that use docker to replicate some common environments?

2022-01-07 15:22 UTC, daniel-goldstein commented
Ah, I forgot this is potentially a laptop-running test and not in a batch job! Definitely would require some more thought.

2022-01-10 15:02 UTC, danking approved these changes

2022-01-10 15:58 UTC, merged