from_pandas
hail-is/hail pull request #11213
Opened 2022-01-10 20:20 UTC by ammekk

Updated from_pandas to not rely on spark.

2022-01-11 22:11 UTC, johnc1231 requested changes
We are going to grow the scope of this a bit.

Right now, you'd run into a problem if the first row of your dataframe contained an empty python list. The problem is, hail won't know what the element type is. Same for empty dict, empty set. Ndarrays are covered since numpy always stores an element type.

Probably the right thing to do is to scan over all the data in a type inference pass where we look at the elements and decide the type. If one column has an array of ints and an array of floats, we should realize that the more general type is floats and accept that. 

It might be best to extend `Table.parallelize` to do this. Imagine if `parallelize` took a `type_hints` argument, which was a dictionary of field names to hail types. For any types specified in `type_hints`, we'd know the type already. Then we'd infer the rest. Then `from_pandas` could just generate a set of type hints based on the non `object` columns, and let `parallelize` infer the type of the remaining columns.

2022-01-18 16:59 UTC, danking requested changes
love it!

2022-01-18 16:59 UTC, danking commented on hail/python/hail/table.py
> +    def parallelize(cls, rows, schema=None, key=None, n_partitions=None, partial_type=None) -> 'Table':
Let's make partial_type keyword only: `..., n_partitions=None, *, partial_type=None`

2022-01-18 16:59 UTC, danking commented on hail/python/test/hail/table/test_table.py
> +
nix empty lines at end of file

2022-01-25 20:11 UTC, johnc1231 commented
@ammekk You have to fix documentation for this method. The documentation contains an example which is failing tests

2022-02-01 15:03 UTC, johnc1231 requested changes

2022-02-01 15:03 UTC, johnc1231 commented on hail/python/hail/table.py
> +            if type_hint:
Prefer `if type_hint is not None` if that's the intended check being done here.

2022-02-03 13:24 UTC, johnc1231 approved these changes

2022-02-03 14:08 UTC, merged