[vds] Add n_partitions argument to read_vds
hail-is/hail pull request #11446
Opened 2022-03-02 16:43 UTC by chrisvittal

At request of gnomAD

2022-03-02 19:33 UTC, patrick-schultz approved these changes

2022-03-03 12:32 UTC, danking commented
```
hail/vds/variant_dataset.py:27:62: F821 undefined name '_n_partitions'
```

2022-03-03 12:33 UTC, danking requested changes
just requesting changes so it shows in Chris' CI page

2022-03-03 22:17 UTC, danking commented
omnibus'ed https://github.com/hail-is/hail/pull/11482

2022-03-03 22:17 UTC, closed without merging