[query] reduce mean test time
hail-is/hail pull request #11449
Opened 2022-03-02 20:18 UTC by danking

More tests => lower mean => more even distribution of time across jobs => lower mean test job time

2022-03-02 20:52 UTC, patrick-schultz requested changes

2022-03-02 20:52 UTC, patrick-schultz commented on hail/python/test/hail/methods/test_pca.py
> +    spectra_helper(spec1, k, m, n)
Can't we combine these all into one test, with the spectrum another parameter?

2022-03-02 20:52 UTC, patrick-schultz commented on hail/python/test/hail/methods/test_pca.py
> +    spectra_helper(spec1, k, m, n)
And the spectral_moments tests below could get the same treatment.

2022-03-02 21:55 UTC, patrick-schultz approved these changes

2022-03-04 20:17 UTC, danking commented
I will revisit this next week

2022-03-04 20:17 UTC, closed without merging