Sb fs globbing
hail-is/hail pull request #11626
Opened 2022-03-21 01:45 UTC by danking

2022-04-05 23:23 UTC, danking commented on hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
> +        params['name'] = urllib.parse.quote(name, safe="")
this was a latent bug

2022-04-06 20:08 UTC, daniel-goldstein requested changes
Nice. It took me half-implementing this another way to understand why you went to the trouble of grouping non-pattern components instead of just one loop over the components listing as you go. Perhaps a performance comment to that effect would help, because my first impression was that it was a bit more complicated than it needed to be.

2022-04-06 20:08 UTC, daniel-goldstein commented on hail/python/hail/fs/router_fs.py
> +        for intervening_components, single_component_glob_pattern in glob_components:
Hard for me to tell what intervening means. I feel like `no_pattern_components` is more straightforward.

2022-04-11 14:11 UTC, danking commented on hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
> +            name += '?' + parsed.query
We should talk about this.

2022-04-15 17:58 UTC, daniel-goldstein commented on hail/python/hail/fs/router_fs.py
> +        for intervening_components, single_component_glob_pattern in glob_components:
preceeding is fine

2022-04-18 00:52 UTC, daniel-goldstein approved these changes

2022-04-19 17:23 UTC, merged