[query] Actually allow the service to use the shuffler
hail-is/hail pull request #11642
Opened 2022-03-22 18:46 UTC by johnc1231

2022-03-22 18:48 UTC, tpoterba approved these changes

2022-03-22 20:08 UTC, danking submitted a review, later dismissed

2022-03-24 17:39 UTC, johnc1231 commented
@tpoterba Enough has changed that I think this should have a compiler team review check on my fixes to Shuffling.

2022-03-24 17:57 UTC, tpoterba requested changes
minor things

2022-03-24 17:57 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
> +    val idealNumberOfRowsPerPart = if (targetNumPartitions == 0) { 1 } else {
style nit: no braces necessary around 1

2022-03-24 17:57 UTC, tpoterba commented on hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
> +    val tableRange = TableRange(40, 10)
revert?

2022-03-24 18:01 UTC, johnc1231 commented on hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
> +    val tableRange = TableRange(40, 10)
Oh yeah, might as well revert

2022-03-24 20:40 UTC, danking approved these changes

2022-03-24 22:06 UTC, merged