[batch] Use sops for credentials
hail-is/hail pull request #11724
Opened 2022-04-04 05:56 UTC by lgruen

Context: https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/ci_config.20secrets

#assign services

2022-06-01 02:58 UTC, lgruen commented
Friendly ping, as merging this would help keep our fork in sync.

2022-06-01 20:02 UTC, jigold commented
@daniel-goldstein I think I am fine with this change in theory. However, it is unclear to me how this would work if we added our encoded files to the repository. Would other forks have overwrite ours each time they merged changes? Would you want me to follow the new directions in my hail-jigold test project to verify the new changes are good?

2022-06-27 15:37 UTC, daniel-goldstein commented
Forks would indeed need to overwrite ours, but since the file wouldn't change much it seems like that's not much of a hassle to maintain, right Leo? And ya this seems like a fine change but we would need to follow up right afterward with our own credentials.

2022-07-04 00:39 UTC, lgruen commented
> I think if it's not too hard of a change, we should add the files with encoded secrets to something like `infra/gcp/data/...`. This makes it clear that these files have a different purpose and gives some indication that they're specific to your repo. If you want to also add prefixing the file name with the repo, then that would make it even clearer. But if it's too much work, don't bother. Maybe something like `infra/gcp/data/hail-is/` etc.

I've put all deployment-specific configs in an `$ORGANIZATION_DOMAIN` subfolder now, which hopefully should avoid any collisions.

2022-07-06 16:40 UTC, jigold submitted a review, later dismissed

2022-07-07 01:31 UTC, lgruen commented on infra/gcp/README.md
> +   # E.g. "hail.is"
Yes, that sounds fine too! It's another variable to explain the semantics of (as it doesn't appear in `ci_config.json`), but it actually clarifies the `<REPO>` reference at the end of the README. I'll push a commit to change this.

2022-08-18 06:33 UTC, lgruen commented
Just realized that this is still open. Are there any missing changes?

2022-08-18 14:23 UTC, jigold commented
I'm so sorry. I didn't see you addressed my comments about the domain. I'll double check it one last time, but I'm sure it's fine.

2022-08-18 14:56 UTC, jigold requested changes

2022-08-18 15:11 UTC, daniel-goldstein commented on infra/gcp/README.md
> +- Create `infra/gcp/$GITHUB_ORGANIZATION/global.tfvars` based on the template below, where `$GITHUB_ORGANIZATION` corresponds to the GitHub organization used for your Hail Batch deployment (e.g. [`ha
This is already prefixed by the cloud (`gcp`), do you mean we would run multiple instances of hail in the same cloud?

2022-08-18 17:33 UTC, jigold approved these changes

2022-08-18 18:55 UTC, merged