[hailtop.aiotools.diff] add hailtop.aiotools.diff
hail-is/hail pull request #11788
Opened 2022-04-21 16:26 UTC by danking

Recursively compare two paths searching for:
1. missing files
2. files with different sizes

The output may be sent directly to hailtop.aiotools.copy to eliminate
the differences. For example:

```
python3 -m hailtop.aiotools.diff gs://abc/ s3://def/ | tee diff.json
cat diff.json | python3 -m hailtop.aiotools.copy 'null' -
```

2022-04-21 16:32 UTC, danking commented
I also included a few minor fixes to S3AsyncFS and a typing addition to tqdm.

2022-04-21 17:35 UTC, daniel-goldstein requested changes
This is neat, but I think I take a bit of issue with size-based `diff`. Sure the etags aren't the same? I thought they were the MD5sum of the object but they could be slightly different.

2022-04-21 17:35 UTC, daniel-goldstein commented on hail/python/hailtop/aiocloud/aioaws/fs.py
> +    def __init__(self, thread_pool: Optional[ThreadPoolExecutor] = None, max_workers: Optional[int] = None, *, max_pool_connections: int = 10):
Not for this PR, but it could be worth a discussion on making optional arguments keyword-only before making this API "public"

2022-04-26 13:27 UTC, daniel-goldstein submitted a review, later dismissed

2022-04-26 13:28 UTC, daniel-goldstein commented on hail/python/test/hailtop/inter_cloud/test_diff.py
> +    actual = diff(source=src_base, target=dest_base)
I think you just need to await these diffs

2022-05-13 15:54 UTC, danking reviewed
@daniel-goldstein I needed to lift frozendict into hailtop to fix the tests. Can you take a look and make sure you're good with that?

2022-05-18 17:53 UTC, danking commented
bump

2022-05-18 17:57 UTC, daniel-goldstein commented
@danking Fine by me but I think you forgot to git add hailtop/frozendict?

2022-05-18 17:58 UTC, danking commented
pushed

2022-05-20 23:35 UTC, merged