[ggplot] add approx_cdf based geom_density
hail-is/hail pull request #11835
Opened 2022-05-13 20:50 UTC by patrick-schultz

<img width="1024" alt="Screen Shot 2022-05-13 at 4 49 21 PM" src="https://user-images.githubusercontent.com/3430459/168387606-65228cab-cb13-42fd-aa91-bae4425df600.png">

2022-05-13 20:51 UTC, patrick-schultz commented
Still need to add documentation.

2022-05-14 13:52 UTC, johnc1231 commented
❤️

2022-05-16 15:12 UTC, chrisvittal requested changes
Looks great. Please add docs.

2022-05-16 16:38 UTC, chrisvittal approved these changes

2022-05-16 16:38 UTC, merged