[batch] Add pool labels
hail-is/hail pull request #11879
Opened 2022-06-01 03:09 UTC by lgruen

This adds a `label` column to pools, which can be used to select a subset of pools to consider when scheduling a job.

The label can be specified for each job by setting the `_pool_label` attribute, e.g. `job._pool_label = 'seqr'` will consider all pools that have the `seqr` label.

Note: this incurs a DB migration.

`batch/sql/add-seqr-pools.sql` is an example for adding a copy of the default preemptible pools, with an additional `seqr` label applied. CPG limits the number of instances in those dedicated pools to prevent long running seqr loading pipeline jobs from starving other batches for resources.

#assign services

2022-06-01 14:27 UTC, jigold commented
This should be assigned to me.

2022-06-01 21:03 UTC, jigold requested changes
Three things:

1. What do you think about allowing a pool to have multiple labels? I know this will change the UI a bit, but we could ignore the UI and implement the support for multiple labels in the backend without having to deal with the HTML and CSS.
2. Can we convert no label to `None` instead of `''` and handle `None` appropriately?
3. I think you implemented this, but I want to be sure. If a job has a label, then it can be assigned to the cheapest/ideal pool matching that label. Otherwise, if a job has no label, then it can be assigned to the cheapest/ideal pool matching a pool with no labels.

2022-06-01 21:05 UTC, jigold commented
To get rid of the CI errors, then you have to run black on some of your files.

```
PYTHONPATH=${PYTHONPATH:+${PYTHONPATH}:}../hail/python:../gear:../web_common python3 -m black . --line-length=120 --skip-string-normalization --check --diff
--- batch/inst_coll_config.py	2022-06-01 03:13:40.430014 +0000
+++ batch/inst_coll_config.py	2022-06-01 03:15:40.847020 +0000
@@ -307,13 +307,20 @@
                 if optimal_cost is None or max_regional_maybe_cost < optimal_cost:
                     optimal_cost = max_regional_maybe_cost
                     optimal_result = (pool.name, maybe_cores_mcpu, maybe_memory_bytes, maybe_storage_gib)
         return optimal_result
 
-    def select_pool_from_worker_type(self, cloud, pool_label, worker_type, cores_mcpu, memory_bytes, storage_bytes, preemptible):
+    def select_pool_from_worker_type(
+        self, cloud, pool_label, worker_type, cores_mcpu, memory_bytes, storage_bytes, preemptible
+    ):
         for pool in self.name_pool_config.values():
-            if pool.cloud == cloud and pool.worker_type == worker_type and pool.preemptible == preemptible and pool.label == pool_label:
+            if (
+                pool.cloud == cloud
+                and pool.worker_type == worker_type
+                and pool.preemptible == preemptible
+                and pool.label == pool_label
+            ):
                 result = pool.convert_requests_to_resources(cores_mcpu, memory_bytes, storage_bytes)
                 if result:
                     actual_cores_mcpu, actual_memory_bytes, acutal_storage_gib = result
                     return (pool.name, actual_cores_mcpu, actual_memory_bytes, acutal_storage_gib)
         return None
@@ -322,11 +329,19 @@
         if self.jpim_config.cloud != cloud:
             return None
         return self.jpim_config.convert_requests_to_resources(machine_type, storage_bytes)
 
     def select_inst_coll(
-        self, cloud, machine_type, pool_label, preemptible, worker_type, req_cores_mcpu, req_memory_bytes, req_storage_bytes
+        self,
+        cloud,
+        machine_type,
+        pool_label,
+        preemptible,
+        worker_type,
+        req_cores_mcpu,
+        req_memory_bytes,
+        req_storage_bytes,
     ):
         if worker_type is not None and machine_type is None:
             result = self.select_pool_from_worker_type(
                 cloud=cloud,
                 pool_label=pool_label,
would reformat batch/inst_coll_config.py
--- batch/front_end/front_end.py	2022-06-01 03:13:40.462017 +0000
+++ batch/front_end/front_end.py	2022-06-01 03:15:42.270698 +0000
@@ -838,11 +838,18 @@
                     )
 
                 inst_coll_configs: InstanceCollectionConfigs = app['inst_coll_configs']
 
                 result, exc = inst_coll_configs.select_inst_coll(
-                    cloud, machine_type, pool_label, preemptible, worker_type, req_cores_mcpu, req_memory_bytes, req_storage_bytes
+                    cloud,
+                    machine_type,
+                    pool_label,
+                    preemptible,
+                    worker_type,
+                    req_cores_mcpu,
+                    req_memory_bytes,
+                    req_storage_bytes,
                 )
 
                 if exc:
                     raise web.HTTPBadRequest(reason=exc.message)
 
would reformat batch/front_end/front_end.py

Oh no! 💥 💔 💥
2 files would be reformatted, 89 files would be left unchanged.
```

2022-06-02 21:09 UTC, jigold commented
Ok. I thought about this some more. What you've implemented is essentially a "taint" in Kubernetes. I ultimately want both taints and something more complicated that will have to be integrated into the scheduler. I think for now your change is self contained and it will be easy to transform later on without too much complexity or breaking changes for users. I think if you want to rename "label" to "taint" then that might make it clearer what's going on.

cc: @daniel-goldstein

2022-06-22 17:17 UTC, danking commented
I rebased and ran black, let's continue on my PR where we can make whatever changes are necessary to merge. Jackie, you should have permission to push directly to that branch. https://github.com/hail-is/hail/pull/11944

2022-06-22 17:17 UTC, closed without merging