[batch] Add always_copy_output option
hail-is/hail pull request #11884
Opened 2022-06-02 15:22 UTC by jigold

CHANGE_LOG: 
- Added ``Job.always_copy_output`` when using the ``ServiceBackend``. The default behavior is `False` which
  is a breaking change from the previous behavior to always copy output files irregardless of the job's
  completion state.

Thoughts on introducing this "breaking" change? I think it's okay and we will announce the change on Zulip. I think the benefits of getting rid of this not so intuitive behavior where we copy files despite the main container's completion state outweighs possibly breaking someone's pipeline that relied on files being there when the copy step could have failed as well.

2022-06-02 20:04 UTC, daniel-goldstein commented
I think the proposed new default and the option to change it is much more intuitive than the current behavior and worth a change. Though, I think it would be most polite to announce it on zulip/email list a week or two in advance of the release.

2022-06-02 20:04 UTC, daniel-goldstein commented
I think the proposed new default and the option to change it is much more intuitive than the current behavior and worth a change. Though, I think it would be most polite to announce it on zulip/email list a week or two in advance of the release.

2022-06-22 09:22 UTC, daniel-goldstein commented
Another thing I just thought of, I think we should add raise some form of error if a job that is `alwaysRun` has inputs from a job that is not `always_copy_output`. I can't imagine something like that being intentional, but if there is a valid use case, maybe we have a warning instead of an error.

2022-06-23 13:59 UTC, daniel-goldstein submitted a review, later dismissed
Needs rebase fix

2022-06-24 18:08 UTC, jigold commented
I'm not sure how I feel about the warning / error suggestion when always run jobs have inputs that aren't always copied out. Cleanup jobs shouldn't care whether the outputs don't get copied out on failure.

2022-06-24 23:42 UTC, daniel-goldstein commented
Do cleanup jobs take input files from the parent job? IIUC, if I have an always_run job that takes an input from a job that failed, and whose outputs were not written, the input container for the always_run job would fail.

2022-06-29 21:11 UTC, jigold commented
Hopefully the new warning gets at the case you were thinking of as well as a more general problem beyond `always_copy_output`

2022-06-29 22:33 UTC, daniel-goldstein requested changes

2022-06-29 22:33 UTC, daniel-goldstein commented on hail/python/hailtop/batch/job.py
> +                                      f'the always run job with the following command will not run:\n{command}')
I think this should be `the always run job with the following command may not succeed`. It *will* run, right?

2022-07-08 18:08 UTC, jigold commented
Let's leave the WIP tag on, but this should be all set.

2022-07-08 18:32 UTC, daniel-goldstein submitted a review, later dismissed

2022-10-03 21:42 UTC, danking submitted a review, later dismissed

2022-10-03 21:42 UTC, danking commented on hail/python/hailtop/batch/docs/change_log.rst
> +  is a breaking change from the previous behavior to always copy output files irregardless of the job's
irregardless => regardless

2022-10-27 15:35 UTC, daniel-goldstein submitted a review, later dismissed

2022-10-27 16:01 UTC, jigold commented
We cannot take off WIP and merge this until November 1st.

2022-11-02 13:57 UTC, danking submitted a review, later dismissed
Why are we making the server side change? If we only change the client *and also always send the setting* then we preserve the behavior of old versions of the hailtop.batch library while also switching to a different behavior.

2022-11-04 13:20 UTC, daniel-goldstein commented
Agreed I think this properly preserves behavior for old clients

2022-11-09 16:06 UTC, daniel-goldstein commented
@danking This is assigned to me but since you're the last person to leave `changes_requested` it seems appropriate that you re-review.

2022-11-10 20:52 UTC, danking approved these changes
LGTM

2022-11-15 20:11 UTC, merged