[batch] Remove unneeded foreign key constraints
hail-is/hail pull request #11938
Opened 2022-06-21 18:55 UTC by jigold

Too many foreign key constraints are bad because they add compute time for every insert into a referenced table. Foreign key constraints also cause any insert on a referenced table to take out exclusive write locks on the referenced row. For example, every time we insert a new row into `attempt_resources` we're locking both `batches` and `jobs` unnecessarily which makes inserts effectively serial.

2022-06-21 21:59 UTC, jigold commented
I verified that the right foreign key constraints were deleted in my namespace with dev deploy and I didn't touch the foreign key constraints in the other databases.

2022-06-22 13:33 UTC, danking commented
What kind of lock does a foreign key constraint take on the foreign row (or table)? I'm surprised it's an exclusive lock, I'd think you just need a shared lock on the foreign table. If it's shared, how is that serializing the inserts?

2022-06-22 14:37 UTC, jigold commented
You're right. I must have gotten confused with another db operation. These changes will still save some computation time and make it easier to reason about who is taking out locks on which tables when we are trying to understand where deadlocks are coming from.

2022-06-22 14:59 UTC, danking commented
The foreign key constraints are also a safety belt which protect us from a corrupted database. How much does this improve performance? Let's explicitly record the cost-benefit analysis in the PR comments so we can refer back to it if necessary.

2022-06-23 14:54 UTC, daniel-goldstein requested changes
Could you put the performance results here when you're done with them (or link to zulip)?

2022-06-27 15:50 UTC, jigold commented
I'm closing this for now.

2022-06-27 15:50 UTC, closed without merging