[ci] Add frozen mode and only merge if no active deploys
hail-is/hail pull request #12036
Opened 2022-07-18 14:26 UTC by jigold

Adding a frozen mode in case the database migrations go off the rails and also to ensure we don't merge unless the previous deploy has finished.

2022-07-18 16:04 UTC, danking requested changes

2022-07-18 16:04 UTC, danking commented on ci/ci/github.py
> +                    ):
It seems to me that the goal of this change is to force CI to *attempt* to deploy every commit of main. Is that correct? In particular, a failure or checkout_failure is sufficient to allow CI to try to merge the next commit. These failure modes can happen well before the database is deployed.

I think this change successfully makes it very rare that an instance of Batch is running that is incompatible with the database, but it doesn't eliminate that event. Really eliminating that event needs a more sophisticated deployment process and some thought.

Using a WIP tag can eliminate that event with added human involvement. I'm curious what you think about that alternative. Regardless, I think a "stop deploying mode" for CI is worthwhile.

2022-07-22 13:37 UTC, jigold commented
bump

2022-07-22 14:34 UTC, danking approved these changes

2022-07-25 19:56 UTC, merged