added import_csv
hail-is/hail pull request #12047
Opened 2022-07-22 20:44 UTC by Aleisha02

2022-07-22 20:45 UTC, danking requested changes

2022-07-22 20:45 UTC, danking commented on hail/python/hail/methods/impex.py
> +   """Import csv file as :class:`.Table`."""
Let's add an example!

2022-07-25 14:51 UTC, danking requested changes
This looks great, just one nit.

2022-07-25 14:51 UTC, danking commented on hail/python/hail/methods/impex.py
> +          key=table_key_type,
Can you add one space before every line here? The `key` should line up with the `paths`.

2022-08-12 20:49 UTC, Aleisha02 commented
ready for new review i think

2022-08-13 16:34 UTC, danking requested changes

2022-08-13 16:34 UTC, danking commented on hail/python/hail/methods/impex.py
> +                key=None,
too many spaces now; the `k` in key should be directly under the `p` in paths.

2022-08-13 16:34 UTC, danking commented on hail/python/hail/methods/impex.py
> +   """Import csv file as :class:`.Table`.
import "a" csv file as "a" ...

2022-08-13 16:34 UTC, danking commented on hail/python/hail/methods/impex.py
> +   Examples
need one space before the `E` in examples.

2022-10-03 21:51 UTC, danking approved these changes

2023-06-09 23:54 UTC, merged