[batch] Add infrastructure for updates
hail-is/hail pull request #12117
Opened 2022-08-22 18:39 UTC by jigold

Stacked on #11998. This PR adds a new `batch_updates` table as well as propagates update_ids to the batch_inst_coll_staging and batches_cancellable_resources tables. The tricky part is making sure that old/currently running batches are migrated properly while new batches are created properly between when the migration has occurred but before batch is redeployed.

2022-08-23 13:09 UTC, jigold commented
Let's wait until I get open batches working again before merging, but we can start the review process.

2022-08-23 16:30 UTC, daniel-goldstein approved these changes
This looks great.

2022-08-23 16:30 UTC, daniel-goldstein commented on batch/sql/add-batch-updates.sql
> +CREATE TRIGGER batches_before_update BEFORE UPDATE ON batches
This is missing from estimated-current, but is correct. Since this is getting deleted in the next PR I wouldn't bother.

2022-09-13 14:41 UTC, jigold commented
What does full-deploy mean? Can we not make this change online anymore?

2022-09-16 19:01 UTC, daniel-goldstein requested changes
Tiny things

2022-09-16 19:01 UTC, daniel-goldstein commented on batch/sql/estimated-current.sql
> +  `time_created` BIGINT,
Perhaps we should make `time_created` NOT NULL

2022-09-16 19:24 UTC, daniel-goldstein approved these changes
Looks good to me

2022-09-19 18:31 UTC, merged