[query] Allow seeks more than MAX_INT bytes away
hail-is/hail pull request #12164
Opened 2022-09-08 18:36 UTC by daniel-goldstein

2022-09-08 20:49 UTC, daniel-goldstein commented on hail/src/test/scala/is/hail/fs/FSSuite.scala
> +        i += 1
I clearly can't write scala

2022-09-08 21:23 UTC, danking approved these changes

2022-09-08 21:23 UTC, danking requested changes

2022-09-08 21:23 UTC, danking commented on hail/src/test/scala/is/hail/fs/FSSuite.scala
> +      val i = 0
```suggestion
      var i = 0
```

2022-09-16 16:41 UTC, danking approved these changes

2022-09-16 21:52 UTC, merged