[lowering] Lower BGEN export
hail-is/hail pull request #12185
Opened 2022-09-15 14:47 UTC by chrisvittal

2022-09-19 23:23 UTC, chrisvittal commented
This is green now. Testing it fully is difficult since we don't have lowered import. However, manually testing both lowered and unlowered versions has produced bit-for-bit identical output, and [test_bgen_export_from_vcf](https://github.com/chrisvittal/hail/blob/e0de6b3f5c91820be94591e95d1a49b67c83cd7f/hail/python/test/hail/methods/test_impex.py#L1521-L1536) does use the lowered execution for export and passes.

2022-09-20 16:52 UTC, tpoterba commented
awesome!

2022-10-04 13:51 UTC, tpoterba requested changes
tiny comment, otherwise looks great.

2022-10-04 15:08 UTC, tpoterba approved these changes

2022-10-04 17:52 UTC, merged