[batch] Use a simulated job queue to estimate the ready cores in the control loop
hail-is/hail pull request #12212
Opened 2022-09-21 16:40 UTC by jigold

I added a new Grafana panel without alerts that hopefully will let us catch problems if jobs aren't getting scheduled in a timely manner. I think to have an alert, we'd want to measure what the average wait time of a job in the queue is which would require more infrastructure (keeping track of last state change). We can consider adding that now -- not sure how much work it would be.

2022-09-22 15:47 UTC, daniel-goldstein submitted a review, later dismissed
This looks pretty good, it does seem like a small departure from our current implementation that gets us most of the way to basic region-based scaling. Comments I made are pretty minor, I think it all comes down to how that query performs.

I'm a little nervous about the length of the query string scaling in O(users), but there's many parts of this scheduler/scaler that aren't quite suited to many users anyway. We'll have to address those all separately down the road.

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +)
Can we use different terminology here? In my mind we're already using a job queue: the list of Ready jobs in the database, the difference here being that we currently look at the *entire* job queue but the new change looks at the *head* of the job queue

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +)
I also think `total` here is a little redundant

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +
There's an idiom with prometheus metrics to standardize a set of common prefixes (like I use `http` and `sql`). I might have messed this up on some other queries, but can we use `scheduler_` and `autoscaler_` prefixes for these metrics?

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +    def compute_n_instances_needed(self, ready_cores_mcpu, n_instances_by_state, region=None):
Can we add types to this signature

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +            10 * 8 * self.worker_cores
Let's make `10` (and its usage above in `compute_n_instances_needed`) a named constant

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +            10 * 8 * self.worker_cores
Also, I either don't understand what we're computing here or I don't think it's correct. If we're trying to compute the upper bound on how many cores we would have available to schedule on in a few minutes, then we can write:

```python
autoscaler_runs_per_minute = 60 / AUTOSCALER_LOOP_PERIOD_SECONDS
max_new_cores_in_two_and_a_half_minutes = int(2.5 * MAX_INSTANCES_PER_AUTOSCALER_LOOP * autoscaler_runs_per_minute)

max_possible_future_available_cores = self.worker_cores + max_new_cores_in_two_and_a_half_minutes
```

I would rather use a name like `max_possible_future_available_cores` than `n_free_cores`

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +        set_gauge_value(TOTAL_CORES_ATTEMPTED_TO_SCHEDULE, {pool_labels: n_cores_mcpu_attempted_to_schedule / 1000})
I think I find this function more confusing than it is worth. Can we just do:

```python
TOTAL_CORES_SCHEDULED.labels(pool_name=self.pool.name).set(n_cores_mcpu_scheduled / 1000)
```

I find this reads much more clearly. There's also no reason to clear these gauges before setting them

2022-09-22 15:47 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +        set_gauge_value(N_INSTANCES_WITH_JOB_QUEUE, {pool_label: n_instances_with_job_queue})
Same comment as below about not using `set_gauge_value`

2022-09-22 19:29 UTC, jigold commented
I changed the control loop to use the old method of estimating ready cores for now. I'll change it to the new way in a second PR. This way we can make sure we're happy with the metrics in Grafana before I change the behavior.

2022-09-28 12:49 UTC, jigold commented
This is ready for a look. The tests are passing except one service backend test timed out.

2022-09-28 20:53 UTC, daniel-goldstein requested changes

2022-09-28 20:53 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +        return instances_needed
I think this doesn't need to return anything anymore, right?

2022-09-28 20:53 UTC, daniel-goldstein commented on batch/batch/driver/instance_collection/pool.py
> +CONTROL_LOOP_RUNS = pc.Counter(
Nit: match the name of the constant to the name of the query

2022-09-28 20:53 UTC, daniel-goldstein commented on batch/test/test_batch.py
> +        dev_client.close()
Should this test have another batch that is running at the same time by a different user as well?

2022-09-29 19:48 UTC, daniel-goldstein approved these changes

2022-09-29 23:28 UTC, merged