[ci] Permit deployment of batch and auth at the same time
hail-is/hail pull request #12354
Opened 2022-10-19 15:10 UTC by daniel-goldstein

The serial deployment of auth and batch can lengthen the critical path of CI pipelines by a few minutes if k8s needs to spin up new nodes. While auth is necessary for batch to function correctly, it's not necessary to deploy batch, so I think it's more appropriate to not have `deploy_batch` depend on `deploy_auth` but have anything that depends on `deploy_batch` also depend on `deploy_auth`. There's already a precedent for this in that the service backend tests depend on `deploy_batch` and `deploy_memory` as opposed to `deploy_batch` being dependent on `deploy_memory`.

I also removed the dependency of `upload_query_jar` on `deploy_batch`, no idea why that was there, but maybe it should be the other way around?

2022-10-19 15:46 UTC, jigold commented
Is it worth just adding a sink no-op node for deploy_batch and deploy_auth which is like deploy_batch_system (I know terrible name)? I'm just worried about the case where we someday have a storage service or other multiple components in addition to auth.

2022-10-19 16:27 UTC, daniel-goldstein commented
That's a nice idea, it would help with e.g. forgetting to `deploy_memory` whenever I want to mess with QoB in my namespace, which would admittedly become more of a problem if I make this change. I'll try that out

2022-10-24 17:21 UTC, jigold requested changes
see comment.

2022-11-30 21:36 UTC, danking commented
bump

2023-01-04 20:39 UTC, daniel-goldstein commented
I think I have a slightly different idea for this that less invasive. Will open a new PR with that

2023-01-04 20:39 UTC, closed without merging