[native] update gitignore
hail-is/hail pull request #12414
Opened 2022-11-02 16:19 UTC by tpoterba

2022-11-02 17:51 UTC, chrisvittal requested changes
One question.

2022-11-02 22:04 UTC, daniel-goldstein commented
Hm I only use neovim and I have a .cache dir, I wonder where it's from, maybe clangd?

2022-11-03 00:07 UTC, tpoterba commented on .gitignore
> +.cache/
clangd.

2022-11-03 13:33 UTC, chrisvittal approved these changes

2022-11-03 17:55 UTC, merged