[query] Retry transient errors in HadoopFS
hail-is/hail pull request #12411
Opened 2022-11-01 21:59 UTC by daniel-goldstein

2022-11-03 19:02 UTC, danking requested changes

2022-11-03 19:02 UTC, danking commented on hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
>      getFileSystem(fname).delete(new hadoop.fs.Path(fname), false)
For retry transient to work you'll need to ensure idempotency. I think it's sufficient to try-catch and smother FileNotFoundException Same for delete. Not sure about rmtree. You'll have to try calling that on a directory that doesn't exist.

2022-11-03 19:02 UTC, danking commented on hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
> -  def openNoCompression(filename: String): SeekableDataInputStream = {
If the streams hiccup we'll still get errors, but this PR is a worthwhile improvement. I'm not sure how to robustly retry the input streams we get from Hadoop anyway.

2022-11-30 21:50 UTC, danking commented
bump

2022-12-13 19:20 UTC, daniel-goldstein commented
@danking Have you actually seen anymore of these errors after your fix of the hadoop tests erasing each others' files? I considering closing this because I've not seen further evidence that hadoop isn't properly addressing transient errors.

2022-12-16 17:03 UTC, danking commented
Let's close until we have more evidence.

2022-12-16 17:03 UTC, closed without merging