[mypy] Upgrade mypy and make suggested fixes
hail-is/hail pull request #12447
Opened 2022-11-10 15:40 UTC by daniel-goldstein

These changes are mostly because mypy now needs all `None` parameters to be explicit optionals, whereas before it would let something like `def foo(arg: str = None)` slide. The `type: ignore` on the azure client call is an azure library bug, I looked into the source for that function and there's a comment saying that the input is an `Optional[int]` but the type stubs that mypy is picking up say `int`.

the `check_untyped_defs` config flag tells mypy to typecheck the bodies of functions that do not have a type signature, which apparently it wasn't doing on its own.

2022-11-10 15:41 UTC, daniel-goldstein commented
Sorry jumped the gun there, unassigning because there's still more linting to fix

2022-11-10 21:28 UTC, jigold approved these changes

2022-11-10 21:28 UTC, jigold commented on hail/python/Makefile
> +PYTHON := python
fix.

2022-11-10 21:28 UTC, jigold requested changes
python -> python3

2022-11-15 20:10 UTC, jigold commented
Looks like this needs a rebase now.

2022-11-17 16:37 UTC, jigold commented
Unfortunately, needs a rebase again.

2022-11-17 16:39 UTC, jigold approved these changes

2022-11-17 16:40 UTC, jigold commented
Approving in anticipation that the rebase is just fixing the pinned requirements. Can you re-request a review if you make other changes?

2022-11-21 22:01 UTC, merged