[query] Expose hl.keyed_intersection and hl.keyed_union in Python.
hail-is/hail pull request #12539
Opened 2022-12-02 23:14 UTC by tpoterba

2022-12-05 21:43 UTC, danking requested changes

2022-12-05 21:43 UTC, danking commented on hail/python/hail/expr/functions.py
> +    ----------
needs the same warning

2022-12-13 19:22 UTC, danking commented
bump

2022-12-13 21:20 UTC, tpoterba commented
ugh, this PR is quite mislabeled. This was meant to be the secondary indexing stub -- the last commit here -- but was stacked on the keyed_intersection stuff (which has merged to main in another PR) and I didn't fix up the title. I'll rebase to make this clearer as an example for us to poke at indexing for seqr, and make the warning fix in another PR.

2023-02-06 21:26 UTC, closed without merging