[query][qob][hailtop/fs] Expose modification and creation time.
hail-is/hail pull request #12571
Opened 2022-12-27 17:53 UTC by danking

Fixes #12540.

CHANGELOG: When using Query-on-Batch, hl.hadoop* methods now properly support creation and modification time.

Creation time is supported by modern Linuxes but only through a new statx API which is not exposed by the Python standard library. There is a 0.1 version library from 2021 which exposes statx including the "birth time". I chose to raise an exception for now.

Each cloud does support a "modification time" but it generally refers to changes to metadata or is just the creation time:
- https://cloud.google.com/storage/docs/json_api/v1/objects#resource (see updated)
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_ResponseSyntax ("Last-Modified", is always creation time)
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax same as above
- https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob (see Last-Modified and x-ms-creation-time)

2022-12-27 17:58 UTC, danking commented
I also just implemented RC3339 parsing because Google's timestamps are not compliant with ISO8601.

2023-01-19 04:19 UTC, danking commented on hail/python/hail/fs/router_fs.py
> +        async_to_blocking(self.cm.__aexit__(None, None, None))
Random other bug I found while I was in here.

2023-01-19 22:43 UTC, danking commented
tests and lints resolved

2023-01-20 15:56 UTC, jigold requested changes

2023-01-20 16:03 UTC, danking reviewed
addressed

2023-01-20 16:03 UTC, danking commented on hail/python/test/hailtop/inter_cloud/test_fs.py
> +            status.time_created()
good catch

2023-01-20 16:29 UTC, jigold approved these changes

2023-02-04 03:19 UTC, merged