[query] IBD implemented in terms of block matrices
hail-is/hail pull request #12629
Opened 2023-01-27 15:57 UTC by jigold

Patrick -- can you give this a careful look over. Once we're happy with it, I'll redo the benchmarking as a last sanity check.

2023-01-30 18:41 UTC, patrick-schultz requested changes
This is very nice and clean. I only see a few little things to clean up.

2023-01-30 18:41 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/identity_by_descent.py
> +    NOT_MISSING = BlockMatrix.from_entry_expr(dataset.is_not_missing).checkpoint(hl.utils.new_temp_file())
Given the expense of `from_entry_expr`, I think it's worth doing the minimum necessary. These four are related by `not_missing = is_hom_ref + is_het + is_hom_var`, so any one can be computed from the other three.

2023-01-30 22:02 UTC, jigold commented
@patrick-schultz Are you okay with where the checkpoints are? If yes, then I'll do one last set of benchmarks and then this is ready to go!

2023-01-31 15:32 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/identity_by_descent.py
> +    sample_ids = dataset.s.collect()
Since we're making multiple passes over `dataset`, we probably want to checkpoint it before this first pass.

2023-01-31 15:32 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/identity_by_descent.py
> +    total_possible_ibs = NOT_MISSING.T @ NOT_MISSING
Not sure if checkpointing NOT_MISSING before the matmul if worth the cost of the write. Might try benchmarking both ways.

2023-01-31 15:32 UTC, patrick-schultz commented on hail/python/hail/methods/relatedness/identity_by_descent.py
> +    ibs2 = total_possible_ibs - ibs0 - ibs1
I *think* you want to checkpoint ibs0, ibs1, ibs2. But again, it's not clear to me if the io or the repeated computation is worse.

2023-01-31 19:29 UTC, jigold commented
```
# (n_samples, n_variants)

# Spark backend (1 core)
# (2500, 100000) =>   147.05s
# (5000, 10000) =>    113.28s

# Local backend
# (2500, 100000) =>   233.94s
# (5000, 10000) =>    489.46s
```

2023-02-08 21:17 UTC, merged