[query] Lower linear SKAT
hail-is/hail pull request #12637
Opened 2023-01-30 16:24 UTC by danking

CHANGELOG: Query-on-Batch now supports `hl.skat(..., logistic=False)`.

I also added actual tests for `hl.skat`, which were lost at some point.

I am somewhat not confident in my documentation and comments, because the SKAT paper is terse and unclear. I would really apprecaiate strong criticism of the documentation and the code comments.

2023-01-30 16:32 UTC, danking commented
These are the rendered docs. They are not included in the actual docs because I do not want people using this function yet.


<img width="1194" alt="Screen Shot 2023-01-30 at 11 31 24" src="https://user-images.githubusercontent.com/106194/215536917-52463b33-8138-4d94-a3b3-456eef086b1f.png">
<img width="1194" alt="Screen Shot 2023-01-30 at 11 31 29" src="https://user-images.githubusercontent.com/106194/215536912-7f5cac4c-e4d2-4793-8352-c84c4be7db89.png">
<img width="1194" alt="Screen Shot 2023-01-30 at 11 31 33" src="https://user-images.githubusercontent.com/106194/215536909-4136c303-3bc9-485a-842f-10bbe1b955c2.png">
<img width="1194" alt="Screen Shot 2023-01-30 at 11 31 39" src="https://user-images.githubusercontent.com/106194/215536903-69b75d4a-83aa-4971-875c-6e9a68c74dcc.png">

2023-01-30 18:21 UTC, patrick-schultz requested changes
Some notes after a first pass

2023-01-30 18:21 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    )
More efficient:
```
((ht.y_residual @ ht.G).map(lambda x: x**2) * ht.weight).sum(0)
```

2023-01-30 18:21 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    Q, _ = hl.nd.qr(ht.covmat)
Already computed this

2023-01-30 18:21 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    singular_values = hl.nd.svd(ht.G.T @ (ht.G * ht.weight) - C0.T @ (C0 * ht.weight), compute_uv=False)
As discussed in zulip, I think a better way to compute this is:
```
R = nd.qr(ht.G - Q @ (Q.T @ G), mode="r")
singular_values = hl.nd.svd(R, compute_uv=False)
eigenvalues = singular_values.map(lambda x: x**2)
```
(replace `singular_values` with `eigenvalues` below)

2023-01-31 23:57 UTC, danking commented
Comments addressed. Still gotta work on the verbiage to clearly explain the present of P_0.

2023-02-01 22:56 UTC, danking commented
@patrick-schultz Alright. This passes tests locally. I'm happy with the docs verbiage. I am eager for your review!

<img width="1105" alt="Screen Shot 2023-02-01 at 17 54 00" src="https://user-images.githubusercontent.com/106194/216184499-6b30a121-9e07-40a6-8825-dc6e7c6194bf.png">

<img width="1105" alt="Screen Shot 2023-02-01 at 17 54 10" src="https://user-images.githubusercontent.com/106194/216184498-5f9eaeaf-fa76-4161-acdd-81682e06aa3f.png">

2023-02-02 16:13 UTC, patrick-schultz submitted a review, later dismissed
A few docs comments. Everything else looks great!

2023-02-02 19:50 UTC, danking commented on hail/python/hail/methods/statgen.py
> +    # SVD(M) = U S V. U and V are unitary, therefore SVD(k M) = U (k S) V.
In the next line, we scale the singular values by `\sigma^2` instead of multiplying A by `sqrt(\sigma^2)`.

2023-02-02 19:50 UTC, danking commented on hail/python/hail/methods/statgen.py
> +    # SVD(M) = U S V. U and V are unitary, therefore SVD(k M) = U (k S) V.
I added a blank line to clarify to which expression the comment applies.

2023-02-02 21:56 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    # SVD(M) = U S V. U and V are unitary, therefore SVD(k M) = U (k S) V.
Oh I see. That doesn't have anything to do with unitarity. Scalars commute with all matrices.

2023-02-02 21:58 UTC, patrick-schultz requested changes

2023-02-02 21:58 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +        U \Lambda U &= B \quad\quad \Lambda \textrm{ diagonal } U \textrm{ orthogonal} \\
Still missing a transpose: `U \Lambda U.T`

2023-02-03 21:34 UTC, danking commented on hail/python/hail/methods/statgen.py
> +        U \Lambda U &= B \quad\quad \Lambda \textrm{ diagonal } U \textrm{ orthogonal} \\
ah oops

2023-02-03 21:41 UTC, patrick-schultz approved these changes

2023-02-03 22:51 UTC, merged