[query] lower logistic SKAT
hail-is/hail pull request #12643
Opened 2023-02-02 02:10 UTC by danking

CHANGELOG: `hl.skat(..., logistic=True)` now supported in the Batch backend.

Stacked on linear skat https://github.com/hail-is/hail/pull/12637

2023-02-06 15:21 UTC, danking commented on hail/python/test/hail/methods/test_skat.py
> -def test_linear_skat_R_truth():
this name was actually duplicated in current main, it's now called `test_linear_skat_no_weights_R_truth`

2023-02-06 15:23 UTC, danking commented on hail/python/hail/methods/statgen.py
> +    if hl.current_backend().requires_lowering:
In the second phase, we'll benchmark and address speed problems. Until we're certain it is fast enough, I don't want to enable it for all backends.

2023-02-06 15:25 UTC, danking commented on hail/python/test/hail/methods/test_skat.py
> +        [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0]]
I needed to create a matrix on which the logistic model converged.

2023-02-06 15:27 UTC, danking commented on hail/python/test/hail/methods/test_skat.py
> -def test_linear_skat_R_truth():
This test is inadvertently duplicated in main. I just removed it entirely, but the diff is a bit awkward.a

2023-02-06 15:44 UTC, danking commented
Hmm. I trust the code now. I test against several R SKAT runs. I'm not sure I understand how we derive that Q is generalized chi-squared distributed. We use the residual phenotypes in the calculation of Q, but those are inverse-logit transformed normal variables. The derivation for the linear case doesn't apply, as far as I can tell. I assume the residuals are Bernoulli distributed? Maybe not. I guess the phenotypes are Bernoulli but the errors aren't? I'm not sure.

2023-02-13 21:49 UTC, danking commented
bump @patrick-schultz ideally we would merge this before Wednesday's meeting!

2023-02-13 22:06 UTC, patrick-schultz requested changes

2023-02-13 22:06 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    variance.
I think everything below this doesn't make much sense. The residuals are certainly not normal -- they can only take two possible values. I tried to look into how to justify the logistic case, and made a little progress ("Pearson residuals" are relevant), but I think it's best to not try to write a complete derivation here. It should be enough to summarize the math from the paper that we implement.

2023-02-13 22:07 UTC, patrick-schultz commented
> bump @patrick-schultz ideally we would merge this before Wednesday's meeting!

My bad, didn't realize I hadn't submitted my review.

2023-02-15 23:33 UTC, danking commented
@patrick-schultz , I've reworked the docs in a less wrong way. Let me know what you think!

<img width="1606" alt="Screen Shot 2023-02-15 at 18 32 21" src="https://user-images.githubusercontent.com/106194/219216726-c396892b-5411-4451-8ef0-c8c955a0fd19.png">
<img width="1606" alt="Screen Shot 2023-02-15 at 18 32 26" src="https://user-images.githubusercontent.com/106194/219216731-3cfa206b-b773-4ea2-9df0-8921c2510705.png">
<img width="1606" alt="Screen Shot 2023-02-15 at 18 32 29" src="https://user-images.githubusercontent.com/106194/219216737-f0df11d5-6624-4e82-860e-25fb46374fae.png">

2023-02-15 23:34 UTC, danking commented on hail/python/hail/methods/statgen.py
> +       :math:`\sigma^2 = p(1 - p)` where :math:`p` is the best-fit probability.
done

2023-02-15 23:34 UTC, danking commented on hail/python/hail/methods/statgen.py
> +       :math:`\sigma^2 = p(1 - p)` where :math:`p` is the best-fit probability.
I changed this to have a sample index since the sigmas are sample indexed in the logistic case.

2023-02-16 17:39 UTC, patrick-schultz requested changes
Looks great, just a couple small fixes

2023-02-16 17:39 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +        \textrm{logit}(P(y=1)) &= \beta_0 X + \beta_1 G + \varepsilon \quad\quad \varepsilon \sim N(0, \sigma^2)
This is still saying the residuals are normally distributed. I think the right way to express the logistic regression model is
```
y ~ Bernoulli(logit^{-1}(beta_0 X + beta_1 G))
```

2023-02-16 17:39 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +        \textrm{logit}(P(y=1)) = \beta_\textrm{null} X + \varepsilon \quad\quad \varepsilon \sim N(0, \sigma^2)
Here too

2023-02-16 17:39 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    instead consider :math:`Z^T Z` (note that we elide transpositions of symmetric matrices):
This isn't saying what you mean (`Z Z^T` is symmetric, so its transpose is `Z Z^T`). The only way I know to say this is that the eigenvalues of both `Z Z^T` and `Z^T Z` are the squared singular values of `Z`.

2023-02-16 17:39 UTC, patrick-schultz commented on hail/python/hail/methods/statgen.py
> +    Q, _ = hl.nd.qr((ht.covmat.T * sqrtv).T)
Oops, yes, that's what I meant.

The -1 thing is a numpy behavior we mimic. From [their docs](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html):
> One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

So `reshape(-1, 1)` is a universal "make this a column vector" command.

2023-02-16 23:31 UTC, danking commented
Thanks for clarifying these points and pointing out the errors!

<img width="1559" alt="Screen Shot 2023-02-16 at 18 31 01" src="https://user-images.githubusercontent.com/106194/219511417-004e5529-c41c-4068-bc85-d679fca58058.png">
<img width="1559" alt="Screen Shot 2023-02-16 at 18 31 04" src="https://user-images.githubusercontent.com/106194/219511421-ba3600ad-b0a3-4564-862a-78f6b7501467.png">
<img width="1559" alt="Screen Shot 2023-02-16 at 18 31 09" src="https://user-images.githubusercontent.com/106194/219511419-cfa45641-bcf4-4e29-a5f1-bf431981c0c6.png">

2023-02-17 14:16 UTC, merged