[lowering] Fix MatrixBlockMatrixWriter lowering when some partitions are empty
hail-is/hail pull request #12797
Opened 2023-03-17 18:52 UTC by chrisvittal

Using changePartitionerNoRepartition with a partitioner with a different
number of partitions cannot be correct and will result in dropped data.
Just construct the new partitioner (based on row index, so it will
comply with invariants) directly.

2023-03-17 18:58 UTC, chrisvittal commented
resolves https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/.60pc_relate.60.20crash.20with.200.2E2.2E110

2023-03-17 19:36 UTC, ehigham reviewed
Unsolicited feedback - is there no way to test this that doesn't involve an integration test and/or the need to check in so many files? I wonder if this can be captured in a scala unit test?

2023-03-17 20:01 UTC, chrisvittal commented
Great question. If I could create a table that could reproduce this bug in pure code, I would.

2023-03-17 20:05 UTC, tpoterba commented
shouldn't we be able to create a MatrixTable with empty partitions, write as BM, and trigger this?

2023-03-20 15:38 UTC, tpoterba requested changes
This test seems unnecessarily integration-y for something that we should able to test directly. If we have the partition counts of the input to write_from_entry_expr, we should be able to just generate the MT with those counts and trigger the failure directly?

2023-03-20 15:53 UTC, chrisvittal commented
I'll try it.

2023-03-20 18:32 UTC, danking commented on hail/python/test/hail/methods/relatedness/test_pc_relate.py
> +from ...helpers import resource, skip_when_service_backend, fails_service_backend, fails_local_backend
unnecessary change

2023-03-20 19:43 UTC, chrisvittal commented on hail/python/test/hail/methods/relatedness/test_pc_relate.py
> +from ...helpers import resource, skip_when_service_backend, fails_service_backend, fails_local_backend
thanks!

2023-03-20 19:46 UTC, chrisvittal commented on hail/python/test/hail/linalg/test_linalg.py
> +            mt = mt.filter_rows((mt.locus.position <= 500) | (mt.locus.position > 1500)).checkpoint(path)
unfortunately, this is a bit of a load bearing checkpoint, the issue we've run into doesn't replicate otherwise

2023-03-21 19:07 UTC, merged