[devbin] Automate cloning db and accessing it with a preconfigured VM
hail-is/hail pull request #12794
Opened 2023-03-16 18:00 UTC by jigold

This PR creates a clone of a database along with a companion VM where the SSL and MySQL user credentials are setup automatically.

Note that you'll have to run the script multiple times to get the final result as the "clone" step will time out. The script should be idempotent.

2023-04-12 19:16 UTC, danking commented
I dismissed them as won’t fix because they’re leaking secrets as intended into config files.

2023-04-24 19:48 UTC, danking commented
@daniel-goldstein bump

2023-04-24 20:25 UTC, daniel-goldstein requested changes

2023-04-24 20:25 UTC, daniel-goldstein commented on devbin/setup-vm-with-clone-db-access.sh
> +pip3 install -r gear/requirements.txt
We try to use `pinned-requirements.txt` files as much as possible for reproducibility. You can instead do

```
pip install \
    -r hail/python/pinned-requirements.txt \
    -r hail/python/dev/pinned-requirements.txt \
    -r gear/pinned-requirements.txt
```

2023-05-08 14:56 UTC, jigold commented
I'm going to close this for now and address your comments the next time I need to clone the database.

2023-05-08 14:56 UTC, closed without merging