[query] Make BlockMatrix persist consistent with (matrix) tables
hail-is/hail pull request #12864
Opened 2023-04-10 19:27 UTC by chrisvittal

- Add persist_blockmatrix to backends.
- Make unpersist_blockmatrix consistent with other unpersist backend methods.

2023-04-19 15:58 UTC, ehigham requested changes
This is indeed consistent, though the code is more-or-less copy and paste. Could you refactor to eliminate the code duplication?

Another (perhaps minor) issue I have is the use of exceptions for control-flow in the `unpersist_` method and that the keys are not removed when they're unpersisted. Perhaps restructure to use `pop`, for example:
```python3
persisted = self._persisted_locations.pop(t_or_bm, None)

if not persisted:
    raise ValueError(f'{t_or_bm} was not persisted.')

return persisted.__exit__(None, None, None)
```

2023-04-19 19:40 UTC, danking commented
Drive by comment here as I review PRs, but this is The Python Way, for better or worse. People call it "easer to ask forgiveness than permission". I don't personally have strong feelings one way or the other but we do this in many places in our codebase.

2023-04-20 15:01 UTC, ehigham commented
> Drive by comment here as I review PRs, but this is The Python Way, for better or worse. People call it "easer to ask forgiveness than permission". I don't personally have strong feelings one way or the other but we do this in many places in our codebase.

Be that as it may, throwing if something does not exist is clearer and more robust that catching an error because some operation failed for what is arguably unexceptional, and just hoping that the `ValueError` that that operation threw is because the item did not exist, rather than another `ValueError` risen in any subsequent work.

2023-04-20 15:28 UTC, ehigham commented
> I agree this is the most compelling critique. I think the Pythonistas would make two points: a) KeyError is the one specific error you get in this case and b) it should be written like this:
> 
> ```python
> try:
>     persisted_bm = self._persisted_locations[bm]
> except KeyError as err:
>     raise ValueError(f'{bm} is not persisted') from err
> persisted_bm.__exit__(None, None, None)
> ```

Updated my comment - I think my argument still holds with KeyError

2023-04-20 15:40 UTC, danking commented
Agreed the lack of a pop might be a legitimate bug.

2023-04-20 15:54 UTC, chrisvittal commented
All of this is wrong compared to the docs anyways.
```python3
    def unpersist(self) -> 'MatrixTable':
        """
        Unpersists this dataset from memory/disk.

        Notes
        -----
        This function will have no effect on a dataset that was not previously
        persisted.

        Returns
        -------
        :class:`.MatrixTable`
            Unpersisted dataset.
        """
        return Env.backend().unpersist(self)
```

Whereas, we currently return `None` from `unpersist` and raise if the dataset was not persisted. This is blatantly wrong, and I'm going to fix that.

2023-04-20 18:16 UTC, ehigham approved these changes
Nice! Thanks for making the changes

2023-04-20 18:17 UTC, merged