[query] Add manifest files with parallel export
hail-is/hail pull request #12875
Opened 2023-04-11 19:28 UTC by tpoterba

2023-04-13 13:35 UTC, chrisvittal submitted a review, later dismissed
Please write more (in some place that will be in the git log) about the expected behavior and purpose here, as well as what should be in one of these manifest files. 

Furthermore, it seems like manifests are using absolute paths. This isn't robust to moving the sharded export.

2023-04-13 18:12 UTC, tpoterba commented
good comments, thanks! will address.

2023-04-28 17:29 UTC, tpoterba commented on hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
> +        val path = cb.memoize(partFiles(i))
sorry, getting back to this -- is your concern that we're not handling missing?

I've added an assertion that there are no missing values.

2023-04-28 17:45 UTC, tpoterba commented
addressed!

2023-05-09 18:05 UTC, chrisvittal requested changes
Please edit the PR description. What is a manifest file? Why do we write them now? What should be in them?

2023-05-09 19:03 UTC, chrisvittal approved these changes
Thanks!

2023-05-10 03:21 UTC, merged