[query] Expand ReadValue beyond hail EType deserialization
hail-is/hail pull request #12948
Opened 2023-04-28 14:31 UTC by chrisvittal

This is analogous to the WriteValue change implemented earlier.

Add deserializers, subclasses of ValueReader and have ReadValue use them. A ValueReader deserializes a single hail value, managing the I/O resources required to do so.

One ValueReader has been implemented as part of this change. The ETypeFileValueReader, the minimum necessary functionality for ensuring ReadValue still works exactly as it used to.

2023-04-28 14:32 UTC, chrisvittal commented
stacked on #12935

2023-05-15 13:14 UTC, tpoterba requested changes
some comments on the node / analyses, but looks great and happy to see this!

2023-05-15 15:45 UTC, chrisvittal commented on hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
> +          case reader: ETypeValueReader =>
Good suggestion thanks.

2023-05-15 16:39 UTC, chrisvittal commented on hail/src/main/scala/is/hail/expr/ir/ValueReader.scala
> +  def argumentTypes: IndexedSeq[Type]
Honestly, I can't think of a reason why extra arguments are necessary at all here. Will fix.

2023-05-15 20:05 UTC, chrisvittal reviewed
I've reworked this in a direction that I think makes things much simpler.
* ValueReaders/Writers take Input/OutputStreams
* Codegen for nodes that use them are responsible for managing those resources
* ReadValue and WriteValue now have very well defined semantics, read (write) a single value from (to) a path.
* We can easily expand upon this with say, `SerializeValue` and `DeserializeValue`. `SerializeValue` would take an SValue and return TBinary and `DeserializeValue` would take a `TBinary` and return an SValue.

2023-05-15 20:17 UTC, tpoterba commented
That sounds good!

2023-05-15 20:20 UTC, tpoterba approved these changes

2023-05-16 06:33 UTC, merged