[batch] Simplify cloudfuse credential handling
hail-is/hail pull request #12962
Opened 2023-05-02 15:34 UTC by daniel-goldstein

2023-05-02 20:31 UTC, daniel-goldstein commented
Feel free to unassign if you'd rather deal with changes to cloudfuse-adjacent code at a later time, I just had this already primed last week.

2023-05-09 16:14 UTC, danking submitted a review, later dismissed

2023-05-09 16:14 UTC, danking commented on batch/batch/cloud/gcp/worker/worker_api.py
> +        await check_exec_output('fusermount', '-u', mount_base_path_data)
same here

2023-05-09 16:15 UTC, daniel-goldstein commented on batch/batch/worker/worker_api.py
> +        mount_command = self._mount_cloudfuse(credentials, mount_base_path_data, mount_base_path_tmp, config)
Gladly. I originally changed it to `exec` but undid that because it felt like a different change. but I will happily throw it in.

2023-05-09 16:25 UTC, daniel-goldstein commented on batch/batch/worker/worker_api.py
> +        mount_command = self._mount_cloudfuse(credentials, mount_base_path_data, mount_base_path_tmp, config)
I instead just made the abstract method run the operation instead of passing strings.

2023-05-09 16:27 UTC, danking requested changes

2023-05-09 16:27 UTC, danking commented on batch/batch/cloud/azure/worker/worker_api.py
> +            'entry_timeout=240',
you're sure these don't need the `-o`?

2023-05-09 16:30 UTC, daniel-goldstein commented on batch/batch/cloud/azure/worker/worker_api.py
> +            'entry_timeout=240',
Nope, good catch, fixed.

2023-05-09 16:39 UTC, danking approved these changes

2023-05-10 22:03 UTC, merged