[hailctl/dataproc] upgrades `notebook` to version 6.0.*
hail-is/hail pull request #12965
Opened 2023-05-02 17:20 UTC by iris-garden

See https://github.com/hail-is/hail/issues/12926. Attempting to install hail on dataproc using the `init_notebook.py` script errors out because hail depends on a more recent version of `jinja2` than the version of `notebook` pinned in the script allows for. This change upgrades the pinned version of `notebook` in the script to be compatible with hail's pinned `jinja2` version.

2023-05-02 21:10 UTC, danking commented
Nice! If you use the phrase "Fixes #12926" in your PR message, GitHub will automatically close that ticket when this PR merged.

2023-05-02 21:11 UTC, danking requested changes
@iris-garden were you able to create a dataproc cluster and run some trivial hail code (like `hl.utils.range_table(10)._force_count()`) after this change?

2023-05-04 17:23 UTC, iris-garden commented
> @iris-garden were you able to create a dataproc cluster and run some trivial hail code (like `hl.utils.range_table(10)._force_count()`) after this change?

Nope! This was just to make sure the pipeline succeeds first. Circling back to the dataproc part now; about to ask the team for some help on that on Zulip.

2023-05-05 17:18 UTC, danking commented
That sounds sufficient to me

2023-05-05 17:18 UTC, danking approved these changes

2023-05-05 20:08 UTC, merged