[services] indicate how many errors we have seen
hail-is/hail pull request #12984
Opened 2023-05-04 15:03 UTC by danking

We are increasingly seeing errors from "Connection reset" which we switched from "transient" to "retry once". The current code makes it impossible to determine if we are correctly retrying this error once.

If we see that there are a lot of "Connection reset" errors that happen twice we should perhaps change "retry once" to "retry five times" or use a more generous delay.

2023-05-04 15:19 UTC, daniel-goldstein approved these changes

2023-05-04 18:43 UTC, daniel-goldstein requested changes

2023-05-04 18:43 UTC, daniel-goldstein commented on hail/python/hailtop/utils/utils.py
> +                raise ValueError(f"errors={errors}, delay={delay}") from e
This smothers the real exception that the caller might expect, e.g. tests that test for a 404

2023-05-10 18:53 UTC, daniel-goldstein commented
@danking Is this still relevant? Can we close it since now we're retrying frice?

2023-05-15 22:05 UTC, daniel-goldstein requested changes
See comment

2023-05-16 20:35 UTC, danking commented
debatable. I think it's useful to know this but maybe better conceived as a log message. Let's close and reconsider when its a problem again.

2023-05-16 20:35 UTC, closed without merging