Dk ruff
hail-is/hail pull request #12990
Opened 2023-05-05 01:40 UTC by danking

what do you think of it?

2023-05-05 13:56 UTC, daniel-goldstein requested changes
I just looked at your second commit, but you should be able to merge main now. Overall on board with attacking these ignored rules.

2023-05-05 13:56 UTC, daniel-goldstein commented on batch/batch/worker/worker.py
> +                    v_container_path = _v_container_path
This feels like a bug, no? the `destination` that we set in the container should be as specified by the image manifest, not altered to prepend a `/`. This prepending a slash is only for putting it somewhere easy to find on the host.

I think I only added `VOLUME` support to get buildkit working which I presume uses an absolute path which is why we never noticed it, but I presume there's nothing wrong with specifying a `VOLUME` that is relative to the `WORKDIR`.

2023-05-05 15:47 UTC, daniel-goldstein requested changes
Just checking, does this use of a relative path replicate in docker? My stipulation earlier was what *seemed* reasonable, I do not remember off the top of my head the `VOLUME` spec.

2023-05-05 15:47 UTC, daniel-goldstein commented on build.yaml
> +        VOLUME ["relative_volume]
```suggestion
        VOLUME ["relative_volume"]
```

2023-05-09 15:13 UTC, danking commented
Fixed and test updated.

2023-05-09 15:14 UTC, daniel-goldstein approved these changes

2023-05-12 04:06 UTC, merged