More parallelism
hail-is/hail pull request #13076
Opened 2023-05-17 20:47 UTC by danking

2023-05-17 21:39 UTC, danking commented
Deploy commits don't need to cleanup which adds some latency to this PR. We should probably use xargs -P4 to delete instances 4-way parallel. This PR is ~46 minutes, including all the cleanup time, where as deploys are 46 minutes *without the cleanup time*. Notice two things: (1) the service backend is again the critical path (2) some local backend tests took quite a while to get scheduled. Seems fishy to me that it took ~16 minutes to find a core for the local backend tests to run on.

Anyway, seems good to use more fine-grained parallelism. This should help keep the cluster large-ish and turning over fast so that users get a great experience during the work day.

---

A deploy commit:

<img width="2032" alt="Screen Shot 2023-05-17 at 17 30 55" src="https://github.com/hail-is/hail/assets/106194/9c00365e-1079-451c-bd85-e10561e715c1">

This PR:

<img width="2032" alt="Screen Shot 2023-05-17 at 17 34 40" src="https://github.com/hail-is/hail/assets/106194/fa7751be-3986-4361-89ea-e322760176bf">

2023-05-17 21:40 UTC, danking commented
Probably we should iterate on this PR, accumulating speed boosts until we get a satisfying PR latency.

2023-05-18 03:02 UTC, danking commented
down to 38 minutes, with the cleaning up GCP instances now a significant delay.

<img width="2031" alt="Screen Shot 2023-05-17 at 23 02 20" src="https://github.com/hail-is/hail/assets/106194/6b14d74e-877c-4259-bc26-fd4fed91fe26">

2023-05-18 15:50 UTC, danking commented
This was 11257f9473bfc17fd4db0ee6b6164da300b382af:

<img width="2032" alt="Screen Shot 2023-05-18 at 11 50 02" src="https://github.com/hail-is/hail/assets/106194/0dc45ce1-a3a4-4a21-a068-9895776d8c8a">

2023-05-18 17:28 UTC, danking commented
`bbfc2a1e72822328bf5c8fd33d0e6f4ce5692da3`:
<img width="2032" alt="Screen Shot 2023-05-18 at 13 28 28" src="https://github.com/hail-is/hail/assets/106194/206a6646-c003-48f8-922c-a3f1979023da">

2023-05-19 00:26 UTC, danking commented
Latest changes are worse e1699ab16df88fdc8d44099defe319d9f60f1ab0

<img width="2032" alt="Screen Shot 2023-05-18 at 20 25 44" src="https://github.com/hail-is/hail/assets/106194/17384151-7864-47e5-b759-c6b2b2899a65">

2023-05-19 00:30 UTC, danking commented
This looks to me like we just have bad long tails. If we can 90% and 99% test times down further maybe we're basically good. Seems feasible for the entire service backend tests to take <20 minutes.

2023-05-19 14:49 UTC, danking commented
bd4e923ffdf13e847dab5017f78a3a1716d31c51 (36 minutes):

<img width="2032" alt="Screen Shot 2023-05-19 at 10 49 01" src="https://github.com/hail-is/hail/assets/106194/1186d88a-a28f-4978-952c-df8598ef95f4">

2023-05-19 21:27 UTC, danking commented
fc0d048c0c07c9ec61ff186bc0a117333cd3054e (40 minutes):

<img width="2032" alt="Screen Shot 2023-05-19 at 17 27 32" src="https://github.com/hail-is/hail/assets/106194/b2743bc3-c871-4df9-9990-7990438bfe79">

2023-05-22 16:36 UTC, danking commented
2079a85bce (41 minutes):

I could try to make the tests even more fine-grained and split up even more long-running tests. Seems like some of the bottlenecks I'm hitting now are:
1. Introducing an image with the wheel already installed isn't worthwhile, it adds 2.5 min latency.
2. The large number of splits often requires default Hail to scale up adding a 2min delay (It would be great to get that down).


I'm gonna revert the change that added images and maybe try to reduce service backend parallelism a bit. 36 minutes is an improvement. We should probably focus on making Hail faster rather than trying to squeeze lower latency out of parallelism.

<img width="2032" alt="Screen Shot 2023-05-22 at 12 30 47" src="https://github.com/hail-is/hail/assets/106194/aaa3fbb7-176d-4487-b65e-586c235e2089">
<img width="541" alt="Screen Shot 2023-05-22 at 12 31 23" src="https://github.com/hail-is/hail/assets/106194/016f1089-d08d-4555-ae86-c01353f39c78">

2023-05-25 16:08 UTC, danking commented
Rate limiting is a bit too restrictive methinks. That said, there are a lot of deadlocks when the rate limits kick in. Perhaps worth diving more deeply into the deadlocks at some point. The critical path service backend test is #35. Here are its slowest ones. I think we should probably checkpoint the import VCF, but, regardless, pc_relate just needs to be made faster.

I know how to double the speed of PCA. It's in a dead branch of mine. Patrick will incorporate those ideas into his rewrite using the new math.

If #35 was the same speed as the next slowest, we'd save 3 minutes. I think we can save ~7 minutes by cutting all these slow tests down so that the distribution of runtimes is more uniform.

```
256.68s call     hail/methods/relatedness/test_pc_relate.py::test_pc_relate_against_R_truth
178.28s call     hail/methods/test_pca.py::test_spectra_2[triplet0]
102.60s call     hail/vds/test_vds.py::test_truncate_reference_blocks
82.86s call     hail/backend/test_service_backend.py::test_tiny_driver_has_tiny_memory
```

f1ac37dbeb3625cbf91f1f9df5399f3723843029 (40 minutes) (https://ci.hail.is/batches/7484187):

<img width="2032" alt="Screen Shot 2023-05-25 at 12 01 55" src="https://github.com/hail-is/hail/assets/106194/902a0624-46a0-4beb-ae03-6c419350ca41">
<img width="542" alt="Screen Shot 2023-05-25 at 12 01 28" src="https://github.com/hail-is/hail/assets/106194/3cfa366d-5719-428a-9f4f-5bd07caaf6ca">
<img width="521" alt="Screen Shot 2023-05-25 at 12 01 07" src="https://github.com/hail-is/hail/assets/106194/da778828-9f9e-46cc-b574-68b9835e6589">
<img width="522" alt="Screen Shot 2023-05-25 at 12 01 03" src="https://github.com/hail-is/hail/assets/106194/3074a6f9-06d5-487e-941c-995b47177181">

2023-05-25 16:09 UTC, danking commented
Also! Chris' zstd change should make a modest across the board improvement to test times.

2023-05-25 16:41 UTC, daniel-goldstein requested changes
Awesome, just a couple nits.

2023-05-25 16:41 UTC, daniel-goldstein commented on build.yaml
> +        | xargs -P4 -n2 -r sh -c 'gcloud -q compute instances delete --zone "$1" --project {{ global.gcp_project }} "$2" || true' argv0
This is probably fine, but have you tried doing, say, `P8`? I feel like we ought to be able to issue delete requests for all live instances at once and there could be many more than 4 across all the pools.

2023-05-26 18:43 UTC, danking commented
That huge spike in ready jobs has got to be a mistake. Where do we create a 1500 partition dataset?

Service backend [split 35](https://batch.hail.is/batches/7489026/jobs/197) is again the critical path. I tried pushing a commit which checkpoints the VCF. The main problem is probably just that our PC-Relate implementation is slow.
```
============================= slowest 50 durations =============================
240.09s call     hail/methods/relatedness/test_pc_relate.py::test_pc_relate_against_R_truth
168.03s call     hail/methods/test_pca.py::test_spectra_2[triplet0]
93.98s call     hail/vds/test_vds.py::test_truncate_reference_blocks
86.56s call     hail/backend/test_service_backend.py::test_tiny_driver_has_tiny_memory
83.82s call     hail/methods/test_qc.py::Tests::test_vep_grch38_against_dataproc
```

2a3fbd185e9255ed447dd80b983709d49c7a345e (45 minutes):

<img width="2032" alt="Screen Shot 2023-05-26 at 14 39 28" src="https://github.com/hail-is/hail/assets/106194/2f98159e-e60e-4410-af4b-7bca72fc43a8">


<img width="305" alt="Screen Shot 2023-05-26 at 14 36 58" src="https://github.com/hail-is/hail/assets/106194/be2c4b32-db08-484f-a6de-08bc41149e65">

<img width="523" alt="Screen Shot 2023-05-26 at 14 38 18" src="https://github.com/hail-is/hail/assets/106194/981665f6-fe7c-45eb-8659-836d505fa280">
<img width="518" alt="Screen Shot 2023-05-26 at 14 38 13" src="https://github.com/hail-is/hail/assets/106194/feaf826a-57d2-4404-9844-69048e3ade69">

2023-05-26 20:06 UTC, danking commented
Checkpointing the VCF made it, if anything, slower.
```
254.81s call     hail/methods/relatedness/test_pc_relate.py::test_pc_relate_against_R_truth
189.52s call     hail/methods/test_pca.py::test_spectra_2[triplet0]
95.37s call     hail/vds/test_vds.py::test_truncate_reference_blocks
92.80s call     hail/methods/test_qc.py::Tests::test_vep_grch38_against_dataproc
86.83s call     hail/backend/test_service_backend.py::test_tiny_driver_has_tiny_memory
68.86s call     hail/matrixtable/test_matrix_table.py::test_read_write_balding_nichols_model
```

2023-05-26 20:09 UTC, danking commented
The test_hail_python tests have mysteriously disappeared.

2023-05-30 13:44 UTC, danking commented
WIP, because there's too much chaos in CI right now. Let's squash the local backend issue first.

2023-05-31 18:12 UTC, danking commented
I'm gonna pull these changes into a new PR

2023-05-31 18:12 UTC, closed without merging

2023-05-31 18:18 UTC, danking commented
https://github.com/hail-is/hail/pull/13128