[query] fix requester pays in all Query backends
hail-is/hail pull request #13089
Opened 2023-05-22 14:59 UTC by danking

CHANGELOG: Requester pays buckets now work in `hailtop.fs` and `hl.hadoop_*`. This has been broken since at least 0.2.115.

I first check for an explicit argument or the standard hailctl configuration. If neither of those exist, I try to parse spark-defaults.conf with lots of error handling and warning.

2023-05-22 21:36 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
> +            self._fs = None
This just seemed like old cruft. If there's no project, we should just use the backend's configuration and FS.

2023-05-24 14:07 UTC, daniel-goldstein requested changes
Just a few small things.

2023-05-24 14:07 UTC, daniel-goldstein commented on hail/python/hailtop/config/user_config.py
> +) -> Optional[Union[str, Tuple[str, List[str]]]]:
Shouldn't these use the `GCSRequesterPaysConfiguration` type?

2023-05-25 19:06 UTC, danking commented on hail/python/hailtop/config/user_config.py
> +    buckets = configuration_of('gcs_requester_pays', 'buckets', None, None)
Python's parser doesn't seem to support sub-sections. https://docs.python.org/3.4/library/configparser.html#supported-ini-file-structure

I'm not exactly sure what to do here to be honest. Maybe its time to find a more sophisticated config file format / parser?

2023-05-25 19:14 UTC, daniel-goldstein requested changes
Does my suggestion help?

2023-05-25 19:14 UTC, daniel-goldstein commented on hail/python/hailtop/config/user_config.py
> +                        )
I'm pretty sure you should just be able to do `mode = SparkConfGcsRequesterPaysMode(val)`

2023-05-25 20:35 UTC, daniel-goldstein commented on hail/python/hailtop/config/user_config.py
> +    buckets = configuration_of('gcs_requester_pays', 'buckets', None, None)
Hm, that's annoying. I guess that's where [TOML has the upper hand](https://toml.io/en/v1.0.0#table).

2023-06-09 21:55 UTC, merged