[ci/ui] filters jobs by status
hail-is/hail pull request #13148
Opened 2023-06-06 19:30 UTC by iris-garden

Currently, when the user views the jobs for a CI pipeline, either on the `pr.html` page or the `batch.html` page, they are displayed all together in a big table, like so:

<img width="618" alt="Screenshot 2023-06-06 at 15 30 21" src="https://github.com/hail-is/hail/assets/84595986/8c3f45a8-756d-4e10-ac27-a57791f3965c">

This change filters the jobs out into smaller tables, with any failed jobs displayed first, followed by any jobs that are currently running, then any pending jobs, then the rest.

Example with failed job:

<img width="728" alt="Screenshot 2023-06-06 at 15 12 36" src="https://github.com/hail-is/hail/assets/84595986/5b20f95e-e530-43c2-bc96-4fcd639083d3">

Example with running/pending jobs:

<img width="643" alt="Screenshot 2023-06-06 at 15 10 54" src="https://github.com/hail-is/hail/assets/84595986/7b5790e6-a5e0-426f-b290-a28fee19e967">

2023-06-06 19:32 UTC, iris-garden commented
Note: I have not updated the batch page for CI pipelines or the batch page for non-CI batch because I wanted to first run this change by the rest of the team, hence the WIP status on the PR.

2023-06-07 13:17 UTC, jigold commented
I'm okay with changing the behavior of the ci page, but we should not change the Batch UI page without more planning and discussion. I am in the process of adding a better searching mechanism for those pages that will probably help quite a lot.

2023-06-09 20:46 UTC, danking requested changes

2023-06-09 20:46 UTC, danking commented on ci/ci/ci.py
> +                    running += [job]
`.append(job)`

2023-06-20 20:14 UTC, danking submitted a review, later dismissed

2023-06-20 20:24 UTC, iris-garden commented on ci/ci/templates/filtered-jobs.html
> +{{ job_table(jobs, "jobs", "jobsSearchBar") }}
haha fair, I didn't rename it out of laziness, will fix that

2023-06-21 15:16 UTC, iris-garden commented on ci/ci/templates/filtered-jobs.html
> +{{ job_table(jobs, "jobs", "jobsSearchBar") }}
updated!

2023-06-22 17:14 UTC, danking approved these changes

2023-07-14 19:09 UTC, merged