[auth] More easily add developers to developer namespaces
hail-is/hail pull request #13180
Opened 2023-06-14 19:22 UTC by daniel-goldstein

I decided to break off this chunk from another PR that has stalled. That PR will ultimately build on this to add all developers automatically to dev AND test namespaces, but this should be an improvement for now. A few things in here:

- Deleted all the `DatabaseResource` stuff in the auth driver. Since databases now are created and destroyed with the namespace and not the developer, this is basically dead code.
- Added the ability to add a user for an existing hail identity. This is only permitted in dev namespaces and serves as a way for developers to use the same hail identity across namespaces. There is one caveat here: `create_initial_account.py` tries to copy the `<dev-name>-gsa-key` secret from default into the developer namespace and this code will *not* do that anymore. For the developer to submit jobs to the namespace, they must first manually copy in the secret from `default` if it does not already exist inside the namespace. This is awkward, but IMO acceptable because:
    - the copying code in `create_initial_account.py` is already broken anyway because when that script is run in a dev deploy it does not have access to production secrets
    - I hope that when we eventually go keyless we can delete the gsa key secrets and this whole problem goes away.
    - I generally feel it's not too bad to do this manual one time copy as opposed to maintaining code from a security perspective that is privileged enough to reach across namespaces.
- Deletes `create_initial_account.py` in favor of using our actual API to create the dev user.

2023-06-14 19:24 UTC, daniel-goldstein commented on hail/python/hailtop/hailctl/dev/cli.py
> -    print(steps)
This accidentally snuck in when I was rewriting `hailctl`.

2023-06-15 14:03 UTC, jigold submitted a review, later dismissed
This looks great! Thank you for the comments inlined into the code. 

> For the developer to submit jobs to the namespace, they must first manually copy in the secret from default if it does not already exist inside the namespace.

Can we dummy proof this a bit more to have a nice error message if this is not the case?

2023-06-15 14:57 UTC, jigold commented on auth/auth/driver/driver.py
> +    # auth services in test namespaces cannot/should not be creating and deleting namespaces
I think I would want a check here if it is a dev deployment that the expected secret given by `hail_credentials_secret_name` exists in that namespace using the k8s client.

2023-06-15 16:08 UTC, jigold requested changes

2023-06-15 16:08 UTC, jigold commented on auth/auth/auth.py
> +            log.info(res)
delete?

2023-06-15 16:08 UTC, jigold commented on auth/auth/auth.py
> +                text=f'hail credentials secret name specified but was not found: {hail_credentials_secret_name}'
Can we add the namespace we're looking at as well in the error message?

2023-06-15 19:23 UTC, merged