[batch] JVM container logs streamed with fluentd
hail-is/hail pull request #13190
Opened 2023-06-16 20:10 UTC by jigold

The goal of this PR is to have all of the JVM container logs available where all the worker logs are. I tagged the entries with "worker.log" so they show up with the other worker log entries. However, it's plain text with no timestamp. We can improve the formatting as a separate project. Notice the two entries with "*" on the left instead of the normal "I".

The design choice I made is to have the JVM containers write to a location that is static. We cannot easily change the fluentd configuration dynamically. It requires restarting the daemon which takes 1.5 seconds. Furthermore, the configuration for fluentd is on /etc/ on the host which the batch worker container cannot access. Hence, why I took the approach of specifying it in the startup script at known locations. 

Before we merge this, I'd like to confirm that (a) we want these logs and (b) they don't contain any secrets.
<img width="1585" alt="Screenshot 2023-06-16 at 4 06 43 PM" src="https://github.com/hail-is/hail/assets/1693348/0ce9f7dc-1188-4c66-ae6f-83fcc3744f95">

2023-06-16 20:14 UTC, jigold commented
cc: @iris-garden This is the feature we discussed last week that might help debugging Query.

2023-06-21 20:00 UTC, daniel-goldstein requested changes
Nice, just a couple small things.

2023-06-21 20:03 UTC, jigold commented on batch/batch/cloud/gcp/driver/create_instance.py
> +tag worker.log
Do you prefer `jvm-{idx}.log` or `jvm.log`?

2023-06-21 20:06 UTC, jigold commented on batch/batch/cloud/gcp/driver/create_instance.py
> +tag worker.log
I just kept it as `jvm-{idx}.log`

2023-06-21 20:06 UTC, jigold commented on batch/batch/cloud/gcp/driver/create_instance.py
> +sudo service google-fluentd restart
These files need to be touched after the XFS file system and all is created. I moved the rest of the fluentd configuration code down so it's all together.

2023-06-21 20:13 UTC, daniel-goldstein approved these changes

2023-06-22 18:52 UTC, merged