[release] update changelog for 0.2.119
hail-is/hail pull request #13216
Opened 2023-06-26 18:12 UTC by chrisvittal

2023-06-26 22:54 UTC, danking commented
For the record, until we have a fix for GRCh38 VEP image building, we have to manually copy the 0.2.118 tag to the 0.2.119 tag for vep-grch38-95.
```
skopeo copy docker://us-docker.pkg.dev/hail-vdc/hail/hailgenetics/vep-grch38-95:0.2.118 docker://us-docker.pkg.dev/hail-vdc/hail/hailgenetics/vep-grch38-95:0.2.119                                                      
```

I have done this and retried the ci-test.

2023-06-27 23:27 UTC, chrisvittal commented
It passed.

2023-06-28 14:21 UTC, danking requested changes
LGTM after this

2023-06-28 14:21 UTC, danking commented on hail/python/hail/docs/change_log.md
> +  the default compression algoritm for table and matrix table storage. Reducing
```suggestion
  the default compression algorithm for table and matrix table storage. Reducing
```

2023-06-28 14:24 UTC, danking requested changes

2023-06-28 14:24 UTC, danking commented on hail/python/hail/docs/change_log.md
> +  file size around 20% in most cases.
I think we need a bigger notice of the change of file format. Can we add a new section ### File Format with a message like "The file format is now X.Y.Z. Previous versions of Hail will not be able to read files written by this version of Hail."

2023-06-28 17:26 UTC, danking approved these changes

2023-06-28 17:27 UTC, merged