[batch] Fix list batches query and test
hail-is/hail pull request #13237
Opened 2023-07-11 18:05 UTC by jigold

2023-07-11 18:07 UTC, danking requested changes
Can you describe the problem(s)? I'm not sure what this is fixing

2023-07-11 18:09 UTC, jigold commented
The test that lists batches timed out. The main problem is the limit in the aioclient used by the test_batch tests was passing a string rather than an integer. I assumed downstream the function was passing an integer. Therefore, we were doing this:

```
batch_id < "137"
```

and not `batch_id < 137`.

So the query was running forever and scanning all batches from the `test` user.

I also was missing a tag annotation on the queries, but that was not causing the timeout.

2023-07-11 20:30 UTC, danking submitted a review, later dismissed
Can you edit the PR message with your comment so that when the commit merges into main we have a record of why we made this change? Thanks!

2023-07-12 13:24 UTC, jigold commented
@danking 

I can keep digging, but it looks like the ParamSpec feature isn't available in the Python version we're running. I'll see if there's a workaround, but I'd really not like to hold up this change anymore than needed.

```
Module "typing" has no attribute "ParamSpec"; maybe "_ParamSpec"?
```

2023-07-12 13:25 UTC, jigold commented
It looks like ParamSpec was added in 3.10

2023-07-12 13:47 UTC, danking commented
Can we use the `ParamSpec` from `typing_extensions`?

2023-07-12 14:51 UTC, jigold commented
This looks like it's going to succeed.

2023-07-12 16:10 UTC, danking approved these changes

2023-07-12 16:10 UTC, danking commented on batch/batch/front_end/front_end.py
> +async def _handle_api_error(f: Callable[P, Awaitable[T]], *args: P.args, **kwargs: P.kwargs) -> Optional[T]:
This should be a separate PR, but these new types and all those `assert ... is not None` reveal another issue.

This function conflates two distinct pieces of functionality:
1. Make functions returning no values idempotent
2. Convert `BatchUserError` into an HTTPResponse.

I'm a bit unsure if BatchOperationAlreadyCompletedError is the right thing to use. It seems a bit confusing if I am at the delete billing project form, then press submit, then I lose my WiFi, then refresh the page (clicking OK when it says "do you want to resubmit this form"), then I get "this billing project already is deleted". I guess that tells me that the first request actually did make it through, but as a user, all that matters is that the BP doesn't exist anymore, right? If I mistype the name I'd get a 404, so I can't accidentally think I deleted a different BP.

Regardless, I think we should have `_handle_api_error` which lacks the first except and `_handle_idempotence_and_api_error` which calls `_handle_api_error` wrapped in a try-except.

2023-07-12 16:10 UTC, danking commented
Approved, but see my comment about _handle_api_error.

2023-07-12 16:12 UTC, jigold commented
Thank you! I agree these functions need to be rewritten.

2023-07-12 17:10 UTC, merged