[tests] Mark tests where they should be run in
hail-is/hail pull request #13238
Opened 2023-07-11 22:02 UTC by jigold

2023-07-12 00:06 UTC, danking requested changes

2023-07-12 00:06 UTC, danking commented on hail/python/test/hail/helpers.py
> +            raise RuntimeError(f'unknown location {location}')
let's error if 'all' is specified with any other location.

2023-07-12 00:06 UTC, danking commented on hail/python/test/hail/methods/relatedness/test_pc_relate.py
> +@run_in('local', 'spark', 'batch', clouds=['gcp'])  # reason='takes >14 minutes in QoB in Azure'
should be 'all' right?

2023-07-12 00:06 UTC, danking commented on hail/python/test/hail/helpers.py
> +            raise RuntimeError(f'unknown location {location}')
Maybe also error if all three are specified? Best to enforce a consistent, simple style across everything.

2023-07-20 23:00 UTC, danking requested changes
I reviewed by hand every single instance where run_in was not 'all' and some cases where it was 'all'. These are my only comments. I think we should work hard to merge this soon, it will reduce the churn in CI and increase developer velocity, the most important thing we have.

2023-07-21 12:59 UTC, patrick-schultz commented on hail/python/test/hail/expr/test_expr.py
> +    @run_in('local')
Agreed. We were too quick to say everything in test_expr was just local computation.

2023-07-21 14:17 UTC, danking commented on hail/python/test/hail/expr/test_expr.py
>  def test_local_agg():
👍 misread this one. you're right.

2023-07-21 14:19 UTC, jigold commented on hail/python/test/hail/methods/test_vep.py
> +import unittest
reverted that change. I forgot why I did it other than at the time all of the other tests were meant to be local, but now they're not.

2023-07-21 16:44 UTC, jigold commented
Should be good to go. Please double check I got all of the changes you wanted.

2023-07-27 14:27 UTC, jigold commented
Closing for now.

2023-08-02 21:07 UTC, jigold commented
Closing again for now.

2023-08-02 21:07 UTC, closed without merging