[hailctl] clarify suggested use of -- and allow it in hailctl batch submit
hail-is/hail pull request #13447
Opened 2023-08-16 17:02 UTC by danking

CHANGELOG: Resolves #13446. In all three submit commands (batch, dataproc, and hdinsight), Hail now allows and encourages the use of -- to separate arguments meant for the user script from those meant for hailctl. In hailctl batch submit, option-like arguments, for example "--foo", are now supported before "--" if and only if they do not conflict with a hailctl option.

2023-08-16 17:24 UTC, jigold requested changes
I assume you tested this and that's why the ValueErrors were there?

2023-08-16 17:24 UTC, jigold commented on hail/python/hailtop/hailctl/batch/cli.py
> +    raise ValueError((name, image_name, files or [], output, script, [*(arguments or []), *ctx.args]))
Is this raise not supposed to be here?

2023-08-16 17:24 UTC, jigold commented on hail/python/hailtop/hailctl/dataproc/cli.py
> +    raise ValueError((name, script, files, pyfiles, properties, gcloud_configuration, dry_run, region, [*(arguments or []), *ctx.args]))
remove ValueError?

2023-08-16 17:24 UTC, jigold commented on hail/python/hailtop/hailctl/hdinsight/cli.py
> +    raise ValueError((name, storage_account, http_password, script, [*(arguments or []), *ctx.args]))
Remove ValueError.

2023-08-16 23:43 UTC, danking commented
FWIW, the helps look like this now:
```
(base) dking@wm28c-761 hail % hailctl batch submit --help                               
                                                                                                                                                                                                                                                                                                                              
 Usage: hailctl batch submit [OPTIONS] SCRIPT [ARGUMENTS]...                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                              
 Submit a batch with a single job that runs SCRIPT with the arguments ARGUMENTS.                                                                                                                                                                                                                                              
 If you wish to pass option-like arguments you should use "--". For example:                                                                                                                                                                                                                                                  
 hailctl batch submit --image-name docker.io/image my_script.py -- some-argument --animal dog                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                              
╭─ Arguments ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *    script         TEXT            [default: None] [required]                                                                                                                                                                                                                                                             │
│      arguments      [ARGUMENTS]...  You should use -- if you want to pass option-like arguments through. [default: None]                                                                                                                                                                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --files               TEXT              Files or directories to add to the working directory of the job. [default: None]                                                                                                                                                                                                   │
│ --name                TEXT              The name of the batch.                                                                                                                                                                                                                                                             │
│ --image-name          TEXT              Name of Docker image for the job (default: hailgenetics/hail) [default: None]                                                                                                                                                                                                      │
│ --output      -o      [text|yaml|json]  [default: text]                                                                                                                                                                                                                                                                    │
│ --help                                  Show this message and exit.                                                                                                                                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

(base) dking@wm28c-761 hail %                                                                                        
(base) dking@wm28c-761 hail % hailctl hdinsight submit --help                                                        
                                                                                                                                                                                                                                                                                                                              
 Usage: hailctl hdinsight submit [OPTIONS] NAME STORAGE_ACCOUNT HTTP_PASSWORD                                                                                                                                                                                                                                                 
                                 SCRIPT [ARGUMENTS]...                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                              
 Submit a job to an HDInsight cluster configured for Hail.                                                                                                                                                                                                                                                                    
 If you wish to pass option-like arguments you should use "--". For example:                                                                                                                                                                                                                              [...]

2023-08-18 20:39 UTC, jigold approved these changes

2023-08-18 21:42 UTC, merged