[batch] re-allow sending kwargs to python jobs
hail-is/hail pull request #13505
Opened 2023-08-25 17:39 UTC by danking

CHANGELOG: Fix bug introduced in 0.2.117 by commit `c9de81108` which prevented the passing of keyword arguments to Python jobs. This manifested as "ValueError: too many values to unpack".

We also weren't preserving tuples. They become lists. I fixed that too. I also added some types and avoided an is instance by encoding the necessary knowledge.

2023-08-25 17:50 UTC, daniel-goldstein requested changes

2023-08-25 17:50 UTC, daniel-goldstein commented on hail/python/hailtop/batch/job.py
> +UnpreparedArg = '_resource.ResourceType' | List['UnpreparedArg'] | Tuple['UnpreparedArg', ...] | Dict[str, 'UnpreparedArg'] | Any
I think we have to wait until [3.10](https://peps.python.org/pep-0604/) for this unfortunately.

2023-08-28 16:58 UTC, daniel-goldstein submitted a review, later dismissed

2023-08-28 16:58 UTC, daniel-goldstein commented on hail/python/hailtop/batch/resource.py
> +ResourceType = PythonResult | ResourceFile | ResourceGroup
Still have pipes here. I didn't mean to get rid of the types altogether though, just replace the pipes with a `Union`

2023-08-31 19:00 UTC, danking commented
Ah, my bad, I thought you mean the recursive types with strings. I didn't realize the pipes were new. That's what I get for not clicking links.

2023-08-31 22:26 UTC, danking commented on devbin/generate_gcp_ar_cleanup_policy.py
I don't entirely understand why pyright runs on everything but it does and it dislikes the formatting of this file.

2023-08-31 22:26 UTC, danking commented on hail/scripts/test_requester_pays_parsing.py
> +from hailtop.config import ConfigVariable, configuration_of
pyright also disliked this

2023-08-31 22:26 UTC, danking commented on hail/scripts/test_requester_pays_parsing.py
> +from hailtop.config import ConfigVariable, configuration_of
and it's right: ConfigVariable is not part of user_config.py

2023-08-31 23:15 UTC, daniel-goldstein approved these changes

2023-09-01 14:53 UTC, danking commented
Blocked by https://github.com/hail-is/hail/pull/13536

2023-09-01 16:32 UTC, merged