[ci] Support docker build args in buildImage steps
hail-is/hail pull request #13612
Opened 2023-09-12 23:07 UTC by daniel-goldstein

Curious for your thoughts on this. I think this will make it easier to build `hailgenetics/hail` images for different python versions without duplicating Dockerfiles with the nice side-effect of not needing to jinja our Dockerfiles.

2023-09-12 23:08 UTC, daniel-goldstein commented on ci/ci/build.py
> +     --local context={shq(context)} \\
Every line here except for the added `{build_args_str}` line is just changing `\` to `\\` so it renders nicely with line breaks in the job page.

2023-09-12 23:11 UTC, daniel-goldstein commented on docker/hail-ubuntu/Dockerfile
> +ARG DOCKER_PREFIX={{ global.docker_prefix }}
This default is for backward compatibility with the current CI that doesn't know about `ARG` and just wants to render this file template. We could presumably replace this with `ARG DOCKER_PREFIX=docker.io` so someone can build this image without needing to set up a whole registry / copy over images / set up k8s secrets to get the `global-config`

2023-09-14 19:54 UTC, danking requested changes

2023-09-14 19:54 UTC, danking commented on ci/test/resources/build.yaml
>          to: /io/hail-ubuntu
Can you update the other images to user build args? The `git-make-bash` can take the docker root image as an arg and that serves as a test of build args in inline images.

2023-09-14 19:55 UTC, danking commented
love it

2023-09-15 20:57 UTC, danking approved these changes
haha, yeah, I just meant the CI stuff but this is great too.

2023-09-16 23:23 UTC, merged