Fewer qob tests
hail-is/hail pull request #13620
Opened 2023-09-14 04:39 UTC by daniel-goldstein

2023-09-14 22:07 UTC, danking requested changes
a few initial reactions. Overall I'm quite pleased with this. 

I kinda prefer a fresh file with freshly written tests? I feel like it's a bit hard to get a total view of what is and is not tests when we're using annotations.

2023-09-14 22:07 UTC, danking commented on hail/python/test/hail/table/test_table.py
>      ht = hl.utils.range_table(100, 10)
add `test_interval_filter_partitions` b/c it will exercise range reads.

2023-09-14 22:07 UTC, danking commented on hail/python/test/hail/vds/test_vds.py
also test `test_split_sparse_roundtrip` b/c split multi is the composition of multiple tricky code paths

2023-09-14 22:07 UTC, danking commented on hail/python/test/hail/methods/test_statgen.py
include all the split_multi tests

2023-09-14 23:09 UTC, daniel-goldstein commented
> I kinda prefer a fresh file with freshly written tests? I feel like it's a bit hard to get a total view of what is and is not tests when we're using annotations.

I agree a single file feels nice, but I'm a little hesitant to copy paste tests. Unless you think I should move where these tests are? That also feels weird.


Does the following pytest invocation make you feel better about markers?

```
(hail) dgoldste@wmce3-cb7 hail % pytest --collect-only -m qobtest hail/python/test
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.9.17, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/dgoldste/hail/hail/python/test
configfile: pytest.ini
plugins: anyio-4.0.0, xdist-2.5.0, instafail-0.5.0, timeout-2.1.0, devtools-0.12.2, asyncio-0.21.1, timestamper-0.0.9, metadata-3.0.0, html-1.22.1, forked-1.6.0
asyncio: mode=auto
collected 8218 items / 8133 deselected / 85 selected

<Package hail>
  <Module test_context.py>
    <Function test_init_hail_context_twice>
    <Function test_top_level_functions_are_do_not_error>
    <Function test_tmpdir_runs>
  <Module test_randomness.py>
    <Function test_table_explode>
<Package backend>
  <Module test_service_backend.py>
    <Function test_tiny_driver_has_tiny_memory>
    <Function test_big_driver_has_big_memory>
    <Function test_tiny_worker_has_tiny_memory>
    <Function test_big_worker_has_big_memory>
    <Function test_regions>
<Package expr>
  <Module test_expr.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_aggregators>
      <TestCaseFunction test_densify_table>
      <TestCaseFunction test_scan>
<Package genetics>
  <Module test_reference_genome.py>
    <Function test_reference_genome>
    <Function test_reference_genome_sequence>
    <Function test_reference_genome_liftover>
    <Function test_read_custom_reference_genome>
<Package matrixtable>
  <Module test_grouped_matrix_table.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_joins_work_correctly>
  <Module test_matrix_table.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_collect_cols_by_key>
      <TestCaseFunction test_naive_coalesce>
      <TestCaseFunction test_range_count>
<Package methods>
  <Module test_family_methods.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_trio_matrix_1>
  <Module test_impex.py>
    <UnitTestCase VCFTests>
      <TestCaseFunction test_glob>
      <TestCaseFunction test_import_gvcfs>
  <Module test_qc.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_sample_qc>
      <TestCaseFunction test_variant_qc>
  <Module test_skat.py>
    <Function test_logistic_skat_phenotypes_are_binary>
    <Function test_logistic_skat_no_weights_R_truth>
  <Module test_statgen.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_impute_sex_same_as_plink>
      <TestCaseFunction test_linreg_basic>
<Package relatedness>
  <Module test_identity_by_descent.py>
    <Function test_ibd_default_arguments>
  <Module test_pc_relate.py>
    <Function test_pc_relate_simple_example>
<Package table>
  <Module test_grouped_table.py>
    <UnitTestCase GroupedTableTests>
      <TestCaseFunction test_aggregate_by>
  <Module test_table.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_aggregate1>
      <TestCaseFunction test_annotate>
    <Function test_lowered_persist>
    <Function test_lowered_shuffle>
<Package utils>
  <Module test_hl_hadoop_and_hail_fs.py>
    <Function test_hadoop_methods_1[remote]>
    <Function test_hadoop_methods_1[local]>
    <Function test_hadoop_methods_2[remote]>
    <Function test_hadoop_methods_2[local]>
    <Function test_hadoop_methods_3[remote]>
    <Function test_hadoop_methods_3[local]>
    <Function test_read_overwrite[remote]>
    <Function test_read_overwrite[local]>
    <Function test_hadoop_exists[remote]>
    <Function test_hadoop_exists[local]>
    <Function test_hadoop_is_file[remote]>
    <Function test_hadoop_is_file[local]>
    <Function test_hadoop_stat[remote]>
    <Function test_hadoop_stat[local]>
    <Function test_subdirs[remote]>
    <Function test_subdirs[local]>
    <Function test_rmtree_empty_is_ok[remote]>
    <Function test_rmtree_empty_is_ok[local]>
    <Function test_rmtree_empty_subdir_is_ok[remote]>
    <Function test_rmtree_empty_subdir_is_ok[local]>
    <Function test_remove_and_rmtree[remote]>
    <Function test_remove_and_rmtree[local]>
  <Module test_utils.py>
    <UnitTestCase Tests>
      <TestCaseFunction test_escape_id>
      <TestCaseFunction test_escape_string>
      <TestCaseFunction test_expr_exception_results_in_hail_user_error>
      <TestCaseFunction test_frozen_dict>
      <TestCaseFunction test_hadoop_copy_log>
      <TestCaseFunction test_hadoop_exists>
      <TestCaseFunction test_hadoop_glob_heterogenous_structure>
      <TestCaseFunction test_hadoop_is_dir>
      <TestCaseFunction test_hadoop_is_file>
      <TestCaseFunction test_hadoop_ls>
      <TestCaseFunction test_hadoop_ls_file_that_does_not_exist>
      <TestCaseFunction test_hadoop_ls_glob_1>
      <TestCaseFunction test_hadoop_ls_glob_2>
      <TestCaseFunction test_hadoop_ls_glob_no_slash_in_group>
      <TestCaseFunction test_hadoop_ls_simple>
      <TestCaseFunction test_hadoop_methods>
      <TestCaseFunction test_hadoop_mkdir_p>
      <TestCaseFunction test_hadoop_mkdir_p_2>
      <TestCaseFunction test_hadoop_no_glob_in_bucket>
      <TestCaseFunction test_hadoop_stat>
      <TestCaseFunction test_interval_ops>
      <TestCaseFunction test_json_encoder>
      <TestCaseFunction test_linked_list>
      <TestCaseFunction test_range_matrix_table_n_lt_partitions>
      <TestCaseFunction test_struct_ops>
<Package vds>
  <Module test_combiner.py>
    <Function test_combiner_works>
  <Module test_vds.py>
    <Function test_multi_write>

=============================================================== 85/8218 tests collected (8133 deselected) in 5.04s ===============================================================
```

2023-09-15 14:24 UTC, danking approved these changes
We can iterate from here. Let's reduce test costs and time.

2023-09-15 16:57 UTC, merged