[compiler] Fix Appending Code to Class Init
hail-is/hail pull request #13674
Opened 2023-09-20 15:39 UTC by ehigham

A returnX statement at the end of the original init block made all code appended to the constructor dead. Move this statement to the end of the constructor when emitting the class.

2023-09-20 20:14 UTC, patrick-schultz requested changes
Can you throw an exception [here](https://github.com/hail-is/hail/blob/92e4776161e732d6e6b18c0889a5c2901fc2f94a/hail/src/main/scala/is/hail/expr/ir/Compile.scala#L206)? That would have caught this bug.

2023-09-20 20:29 UTC, ehigham commented
> Can you throw an exception [here](https://github.com/hail-is/hail/blob/92e4776161e732d6e6b18c0889a5c2901fc2f94a/hail/src/main/scala/is/hail/expr/ir/Compile.scala#L206)? That would have caught this bug.

I'm not quite sure what you mean? On what condition should I throw?

2023-09-21 18:48 UTC, patrick-schultz commented
Whoops, sorry clipboard malfunction. I meant [here](https://github.com/hail-is/hail/blob/e6728b812e73a8bd636046bed22f97c5b47a5f12/hail/src/main/scala/is/hail/lir/X.scala#L416), when trying to add code to an lir block after a terminating control op.

2023-09-22 13:05 UTC, patrick-schultz approved these changes

2023-09-25 18:02 UTC, merged