[vds] for filter_intervals, do not serialize the intervals to Python
hail-is/hail pull request #13749
Opened 2023-09-28 21:52 UTC by danking

CHANGELOG: Fix #13758, which, since 0.2.117, required at least 10x the RAM to represent a list of intervals.

2023-09-29 11:14 UTC, patrick-schultz requested changes
I think this will cause the collect to be recomputed each time `intervals` is used (filtering both variants and reference).

Ideally, we should be doing an interval join here instead of collecting the table. But until then, I'm not sure this is an improvement.

2023-09-29 13:44 UTC, danking commented
Interval join won't use the index though, right? I don't think it's necessarily better.

2023-09-29 14:31 UTC, patrick-schultz commented
Ah, you're right.

2023-10-02 15:04 UTC, danking commented
I suppose there's two root causes here:
1. We use the Py4J socket which inflates a byte array by ~5x (and stores it twice, so 10x really).
2. For Python->Scala we use JSON, which also radically inflates the data size.

2023-10-02 15:05 UTC, danking commented
Is there no way to bind the result of the collect and reference in the IR twice?

2023-10-02 16:53 UTC, patrick-schultz commented
That's what the literal was doing. The problem is the result is being used in two completely separate pipelines---the variants and reference. The right thing is probably to collect with `localize=False`, and use the result to annotate globals on both sides, but we still don't support referencing the local environment in MapGlobals.

2023-10-02 18:04 UTC, danking commented
Ah, right, OK, I forget that we have two parallel pipelines here.

2023-10-02 18:04 UTC, closed without merging