[hailctl] Fix uploading files from parent directories of cwd
hail-is/hail pull request #13812
Opened 2023-10-13 18:19 UTC by jigold

The bug in #13785 was that we used a `relpath`, but the files that were to be included was the parent directory of the current working directory of the script. To solve this, I added a new option `--mounts` that uses the Docker syntax for `-v src:dest` to specify where the contents of the source should be mounted into the container.

2023-10-20 15:34 UTC, jigold commented
I think we might need a different name than "mount". In Docker, you can only use the same destination mount once. i.e. you can't have this. `--mount file1:/ --mount file2:/`. 

@danking Do you have any thoughts on the interface for this?

2023-10-23 17:29 UTC, jigold commented
Fixes https://github.com/hail-is/hail/issues/13785

2023-10-23 20:29 UTC, danking requested changes

2023-10-23 20:29 UTC, danking commented on hail/python/hailtop/hailctl/batch/cli.py
> +    ] = None,
I don't like the term `mount` b/c this isn't mounting the users hard drive into the cloud.

I think it's a bit confusing that there are two arguments with nearly identical descriptions.

How about this:
1. Replace `--file` with the functionality provided by `--mount`
2. Allow the new `--file` to elide the destination. When the destination is elided, it is assumed to be the same as the source (so: `..` means `..:..` both relative to the current working directory)
3. By default, make the working directory of the job match the working directory of the user's laptop. 

These three things together allow `--file .. --file ../../reference_data:/reference_data --file ../../other_project/thing.py` to work as expected. You'll get a container with this file structure:
```
/Users
  /dking
    /projects
      /foo
        thing.py
        ... everything else in the working directory of this script on the user's laptop ...
/reference_data
   ... everything in /Users/dking/projects/reference_data on the user's laptop ...
```

NB: if you do `--file .. --file foo.py` you're implicitly copying foo.py twice. Unnecessary, but should be fine if foo.py is not mutated while we are submitting.

2023-11-07 15:30 UTC, jigold commented
bump. Test failure was unrelated.

2023-11-09 21:33 UTC, iris-garden requested changes
lgtm! happy to hit approve once the conflicts are fixed

2023-11-29 14:53 UTC, jigold commented
I rebased this @iris-garden

2023-11-29 19:52 UTC, iris-garden approved these changes

2023-11-30 20:14 UTC, danking commented
Supporting `file://` seems to suggest that we would support URIs in general (e.g. `--files gs://foo/bar:/baz`); AFAICT we don't support the latter, right? What's the motivation to support `file://`?

2023-12-01 21:13 UTC, jigold commented
> Supporting `file://` seems to suggest that we would support URIs in general (e.g. `--files gs://foo/bar:/baz`); AFAICT we don't support the latter, right? What's the motivation to support `file://`?

I didn't know what we currently support with regards to file paths, so I just made it that we're resilient to someone adding file://

2023-12-01 21:13 UTC, jigold commented
I'm not sure what to do about the invalid block id transient error...

2024-01-08 22:05 UTC, jigold commented
This took me an incredibly long time to figure out, but I'm pretty sure the issue is that my last test copies the same file twice. Once explicitly as a single file and the second time as part of the directory to copy recursively. I don't think our copier code interacts correctly with Azure Blob Storage in this case and we end up with invalid block ID list errors.

I'm still stewing over which option is the best to address this. I could either not have `submit.py` ask to copy the same file twice or I can modify the copier to have a lock on the create blob writer stream so that we don't have this issue. However, I'm worried about deadlocks with our extensive use of semaphores and parallelism. Thoughts?? I think the right thing to do is fix it for now in `submit.py` so we can get this in and then make an issue to make a more durable fix to the copier.

2024-01-09 00:50 UTC, danking commented
@jigold https://azure.github.io/Storage/docs/application-and-user-data/code-samples/concurrent-uploads-with-versioning

Looks like this is the expected behavior from Azure Blob Storage when concurrently uploading blobs. It seems like *all* blocks are purged when any single upload succeeds. Unfortunately, it doesn't seem possible to distinguish between a truly invalid block list and this transiently invalid block list. I dislike this interface, but it is what we have.

It seems to me that the right fix is to deduplicate the file list before uploading. Multiple files uploading to the same target should be an error if they're different source files.

2024-01-09 19:25 UTC, jigold commented
@iris-garden Can you review again when you get a chance? Tests are all passing now

2024-01-09 21:03 UTC, merged