[query] Update ReferenceGenome docs
hail-is/hail pull request #13924
Opened 2023-10-26 18:36 UTC by chrisvittal

Add a section on managing the default reference using the `default_reference` method.

2023-10-26 18:37 UTC, chrisvittal commented
Next part of #13856

2023-10-26 19:09 UTC, danking requested changes

2023-10-26 19:09 UTC, danking commented on hail/python/hail/genetics/reference_genome.py
> +    It is a current limitation of hail that a custom reference genome cannot be
Capitalize hail when used as a noun in English text.

2023-10-26 19:09 UTC, danking commented on hail/python/hail/genetics/reference_genome.py
> +    to :func:`~hail.default_reference` after initializing hail.
same

2023-10-30 14:13 UTC, danking approved these changes

2023-10-30 15:42 UTC, merged