[benchmark] fix combiner benchmarks
hail-is/hail pull request #13956
Opened 2023-10-31 15:34 UTC by ehigham

The combiner benchmarks broke following the deletion of the vds_combiner experimental package. Re-implement them in terms of the `vds` package.

2023-10-31 15:36 UTC, ehigham commented on benchmark/python/benchmark_hail/__main__.py
> +def main(argv=sys.argv[1:]):
This change makes it easier for me to launch the benchmark suite in a debugger and change which benchmark i want to debug from within the debugger.

2023-10-31 15:42 UTC, ehigham commented
Hi Chris, would you mind taking a look when you get a chance? I believe you might know the most about the functionality these are exercising. Do the new implementations look ok? Are they benchmarking equivalent functionality?

2023-10-31 17:25 UTC, chrisvittal approved these changes

2023-10-31 17:29 UTC, chrisvittal requested changes
This is indeed what we would like to be checking.

2023-10-31 17:29 UTC, chrisvittal commented on benchmark/python/benchmark_hail/run/combiner_benchmarks.py
> +        combiner.run()
I believe this is now redundant.

2023-10-31 17:53 UTC, ehigham commented on benchmark/python/benchmark_hail/run/combiner_benchmarks.py
> +        combiner.run()
Great! I'll remove it. Thanks.

2023-11-02 15:20 UTC, chrisvittal approved these changes

2023-11-02 15:53 UTC, merged