[services] Add cloudprofile.agent role to service accounts in terraform
hail-is/hail pull request #13978
Opened 2023-11-06 17:35 UTC by jigold

2023-11-07 18:36 UTC, daniel-goldstein requested changes
Let me know if you need anything to apply these changes. This is a purely additive change so I'd rather apply it before merging so we know it's correct.

2023-11-07 18:36 UTC, daniel-goldstein commented on infra/gcp-broad/main.tf
> +  project = var.gcp_project,
```suggestion
  project = var.gcp_project
```

2023-11-07 18:36 UTC, daniel-goldstein commented on infra/gcp/main.tf
> +  project = var.gcp_project,
```suggestion
  project = var.gcp_project
```

2023-11-07 18:36 UTC, daniel-goldstein commented on infra/gcp/main.tf
> +  project = var.gcp_project,
```suggestion
  project = var.gcp_project
```

2023-11-07 18:36 UTC, daniel-goldstein commented on infra/gcp-broad/main.tf
> +    "cloudprofile.agent"
This also needs to be on the test auth account, right?

2023-11-07 20:49 UTC, jigold commented
I'm not sure how to apply it anymore. Can we do it together on zoom at some point this week?

2023-11-07 20:53 UTC, daniel-goldstein commented
Sure thing! Maybe thursday afternoon at some point? Feel free to grab something on my calendar.

2023-11-13 15:59 UTC, daniel-goldstein approved these changes

2023-11-13 16:28 UTC, merged