[hailctl] fs subcommand and utilities
hail-is/hail pull request #14121
Opened 2024-01-03 17:45 UTC by chrisvittal

Add hailctl fs as a cloud agnostic filesystem utility, along with two commands `ls` and `du`. Output is rudimentary at this point and is subject to change.

du:
```
 Usage: hailctl fs du [OPTIONS] [PATHS]...

 Display storage resourse usage

╭─ Arguments ──────────────────────────────────────────────────────────────────╮
│   paths      [PATHS]...  [default: None]                                     │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────────────────────╮
│ --human-readable  -h        print sizes in human readable format (base 10)   │
│ --summarize       -s        display only a total for each argument           │
│ --help                      Show this message and exit.                      │
╰──────────────────────────────────────────────────────────────────────────────╯
```

ls:
```
 Usage: hailctl fs ls [OPTIONS] [PATHS]...

 List objects

╭─ Arguments ──────────────────────────────────────────────────────────────────╮
│   paths      [PATHS]...  [default: None]                                     │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────────────────────╮
│ --long            -l        use long listing format                          │
│ --human-readable  -h        print human readable file sizes (base 10)        │
│ --help                      Show this message and exit.                      │
╰──────────────────────────────────────────────────────────────────────────────╯
```

2024-01-04 18:14 UTC, daniel-goldstein requested changes

2024-01-10 17:27 UTC, chrisvittal commented on hail/python/hailtop/hailctl/fs/cli.py
> +        async_to_blocking(afs.close())
Ok. I'll take care of that.

2024-01-10 17:27 UTC, chrisvittal commented on hail/python/hailtop/hailctl/fs/cli.py
> +        async_to_blocking(fs.close())
Agreed, but not this PR.

2024-01-10 17:28 UTC, chrisvittal commented on hail/python/hailtop/hailctl/fs/cli.py
> +    async for item in await fs.listfiles(path):
Sort of. It's not too bad to do a recursive listing, but then all the bookeeping needs to be done manually. I'll take care of it.

2024-08-20 16:01 UTC, closed without merging