[batch] make ubuntu:20.04, 22.04, 24.04 public images
hail-is/hail pull request #14223
Opened 2024-01-30 21:37 UTC by danking

And mirror them too!

2024-01-30 21:58 UTC, daniel-goldstein requested changes
Looks great, but I think there's a missing negative

2024-01-30 21:58 UTC, daniel-goldstein commented on hail/python/hailtop/batch/publicly_available_images.py
> +def is_docker_hub_image_mirrored_in_hail_batch(image_ref: ParsedDockerImageReference) -> bool:
Shouldn't this be *not* mirrored?

2024-01-30 22:00 UTC, daniel-goldstein commented
Also can you dev deploy `mirror_hailgenetics_images` (maybe change that name too) to make sure that still works?

2024-02-01 22:22 UTC, closed without merging

2024-02-01 22:22 UTC, danking commented
In the spirit of not writing code in February, I'm gonna leave this as future work for the team.