[batch] extract python job specific tests to separate file
hail-is/hail pull request #14314
Opened 2024-02-16 22:47 UTC by danking

Stacked on https://github.com/hail-is/hail/pull/14313.

It is currently too hard to see what parts of python jobs are well tested or not.

2024-02-16 22:48 UTC, danking commented
To be clear this is a straight copy-paste job.

2024-02-22 17:28 UTC, danking commented
@daniel-goldstein  This is not stacked on anything anymore.

2024-02-22 23:28 UTC, daniel-goldstein requested changes
merge conflicts

2024-02-27 15:52 UTC, daniel-goldstein approved these changes

2024-02-27 18:45 UTC, merged