[query] Include traceback in code-generated asserts in debug builds
hail-is/hail pull request #14372
Opened 2024-02-27 23:17 UTC by ehigham

Include the call-stack of the compiler when we emit assertions into generated code. This is useful for showing us the trace of the code that emitted a `.get` on `IEmitCode`, for example.

To do this, add a `hailBuildConfiguration` enum {`release`|`debug`} into `build-info.properties`, parsed as `HAIL_BUILD_CONFIGURATION`.

2024-03-05 15:06 UTC, chrisvittal requested changes
One code change comment.

Another thing I'm noticing about this change, is that we don't use `_assert` a lot. I suspect we need to audit the code base and figure out what uses of `_fatal` are in fact assertions about our code generation that should never fail.

2024-03-05 20:42 UTC, ehigham commented
Apologies, this PR blew up a bit

2024-03-05 22:59 UTC, chrisvittal commented
💥

2024-03-06 00:21 UTC, chrisvittal approved these changes

2024-03-06 00:22 UTC, merged