[query] Struct of Arrays encoder prototype
hail-is/hail pull request #14391
Opened 2024-03-04 17:06 UTC by chrisvittal

TODO

2024-05-03 14:23 UTC, patrick-schultz requested changes
Thanks Chris, this is looking great! Just a few small questions/requests.

Something to consider for the future (but not this PR, we should just get something working merged): maybe `EStructOfArrays` should just construct a wrapped encoder for an actual struct of arrays, and the encode/decode methods just transpose to the appropriate stype and pass it to the wrapped encoder. That might make it easier to add support for more types, and would adapt easily once we start adding struct-of-arrays stypes.

The only downside I see is we have to materialize the entire transposed representation, instead of just one field at a time as we're doing now. But I think that's okay. We should defer that kind of performance optimization until after the infrastructure is more built up.

2024-05-03 17:15 UTC, chrisvittal commented on hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
> +  // XXX: this is a very basic output that does not apply any transformation to the values, just
It's another notation for searchable notes in comments, my editor highlights them, like TODO or FIXME. This is out of date however, so, it's gone.

2024-05-03 17:22 UTC, chrisvittal commented on hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
> +      }
If I can get it to work, I will. I'll also make that a separate change.

2024-05-03 17:27 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
> +      }
Sounds good. It looked to me like it would only be a few line change, but I could be wrong. Don't worry about it if it's harder than that.

2024-05-03 17:36 UTC, chrisvittal commented on hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
> +    )
With the only option for fields being EArray (for now), this is ok. Will change.

Once (if) we start writing uncompressed arrays, we do need to take care to set the missing data to some constant value which will facilitate better compression.

2024-05-03 17:40 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
> +    )
Good point. But that feels like it should be an option on `constructFromElements`.

2024-05-07 19:47 UTC, patrick-schultz approved these changes

2024-05-08 18:56 UTC, merged