release 0.2.129
hail-is/hail pull request #14426
Opened 2024-03-28 19:35 UTC by ehigham

2024-04-01 19:07 UTC, patrick-schultz requested changes
A few more I think would be good to mention:

Bug fix: #14335, #14375
Documentation: #14339
New features: #14405

2024-04-01 20:23 UTC, ehigham commented
> A few more I think would be good to mention:
> 
> Bug fix: #14335, #14375 Documentation: #14339 New features: #14405

Thanks. Those bug fixes are actually included - I think i just referenced the issue instead of the PR. I'd have thought that would be the more useful link rather than link to the pr that fixed the issue?

2024-04-01 20:27 UTC, patrick-schultz commented
Oh I see, sure that makes sense.

2024-04-02 14:13 UTC, patrick-schultz approved these changes

2024-04-02 14:56 UTC, merged