[dataproc] adds project to args for submit
hail-is/hail pull request #14619
Opened 2024-07-16 17:59 UTC by iris-garden

Currently, if you try to pass `--project` to `hailctl dataproc submit`, it still tries to use the project configured via `gcloud config`, and passes through the value specified for `--project` in the `pass_through_args`.

This change allows the user to specify which project their Dataproc cluster is in as part of the command.

An example command where the project is ignored on `main` but used correctly on this branch is:

```bash
hailctl dataproc submit test.py --region us-central1 --project broad-ctsa
```

2024-07-29 15:18 UTC, chrisvittal approved these changes

2024-07-31 15:32 UTC, patrick-schultz requested changes
PRs need to link to issues now. If there isn't one already, can you make an issue that describes the problem, and link it from here?

2024-07-31 15:57 UTC, iris-garden commented
Good catch, updated!

2024-07-31 16:03 UTC, patrick-schultz approved these changes

2024-07-31 18:36 UTC, merged