[query] Remove jackson string length restriction in Spark/Local backends
hail-is/hail pull request #14651
Opened 2024-08-02 21:01 UTC by chrisvittal

Resolves #14650

2024-08-02 21:08 UTC, ehigham requested changes
Can you comment about how you've tested this? I think it might also be worth commenting in the source code why/in what circumstances strings might get so long?

As an aside, do you know why strings are getting so crazy long? Is that legit?

2024-08-05 16:19 UTC, chrisvittal commented
@ehigham Think I've addressed everything.

2024-08-05 17:37 UTC, ehigham approved these changes
Thanks for adding the comments - that'll be helpful when reviewing this code in the future no doubt!

2024-08-07 16:51 UTC, patrick-schultz requested changes
I'm a bit concerned about the replication, and in the future making a change and forgetting to apply it in all three places. Instead of doing this in the `apply` methods for each backend (and `main` for the service backend), could we move it to the constructor of the `Backend` superclass?

2024-08-07 19:44 UTC, patrick-schultz approved these changes
Nice, thanks Chris!

2024-08-07 20:27 UTC, merged