fix TableAggregate bug
hail-is/hail pull request #14673
Opened 2024-09-06 19:36 UTC by patrick-schultz

2024-09-06 19:36 UTC, patrick-schultz commented
* **#14673** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14673?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @patrick-schultz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-07 13:57 UTC, chrisvittal approved these changes
Glad the fix was simple

2024-09-09 17:12 UTC, ehigham submitted a review, later dismissed
Can you lock down this behaviour with a test?

2024-09-09 17:13 UTC, ehigham requested changes
Can you lock down this behaviour with a test?

2024-09-09 17:21 UTC, patrick-schultz commented
> Can you lock down this behaviour with a test?

As I said in the description, I tried hard to write a test, but I couldn't manage to find a way to exercise this with a targeted test. And this bug is currently blocking a user, so I want to get it released asap. I can try again, but I suspect it would end up being a day or two of extra work, and would likely still end up brittle and unsatisfactory. I'd rather spend my effort getting back into the line of work that would eventually make it much easier to target specific compiler code paths.

2024-09-09 20:48 UTC, ehigham approved these changes
sorry for not reading description!

2024-09-19 19:26 UTC, merged