[query] Expose references via `ExecuteContext`
hail-is/hail pull request #14686
Opened 2024-09-17 00:42 UTC by ehigham

[query] Expose references via `ExecuteContext`

extract references from `Backend` implementations

2024-09-17 00:43 UTC, ehigham commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/hail-is/hail/14686?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14686** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14686?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#14684** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14684?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14683** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ehigham and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2025-01-28 18:20 UTC, chrisvittal approved these changes
Looks good to me. Won't change my approval, I just have one question.

2025-01-29 21:31 UTC, ehigham commented on hail/hail/src/is/hail/io/reference/package.scala
I guess there's no good reason for this. Multiple file vs single file. I'll put them back.

2025-01-30 19:13 UTC, patrick-schultz requested changes
Looks good overall, just a few questions

2025-01-30 19:13 UTC, patrick-schultz commented on hail/hail/test/src/is/hail/utils/FlipbookIteratorSuite.scala
> +        case that: Box[_] if typ == that.typ => value == that.value.asInstanceOf[A]
Just curious, did something change to make this necessary?

2025-01-30 19:18 UTC, ehigham commented on hail/hail/src/is/hail/backend/Backend.scala
> -  def references: mutable.Map[String, ReferenceGenome]
All state is being lifted out of the backend interfaces into common driver classes. This allows us to stop duplicating logic around state, especially with py4j. 

Part of the problem with splitting all these changes is you don't really see the bigger picture behind these smaller changes. Sorry for not communicating the intent better. Take a look at the `ehigham/stateless-backend` branch which inverts control around the backend classes.

2025-01-30 19:19 UTC, ehigham commented on hail/hail/src/is/hail/backend/py4j/Py4JBackendExtensions.scala
> +  def backend: Backend
It makes this easier to refactor into `Py4JBackendApi` which is composed of a backend rather than being a `Backend`.

2025-01-30 19:21 UTC, ehigham commented on hail/hail/src/is/hail/backend/py4j/Py4JBackendExtensions.scala
> +    references -= name
It's used in a couple of places in a subsequent PR. Allows me to change the implementation later.

2025-01-30 19:23 UTC, ehigham commented on hail/hail/src/is/hail/variant/ReferenceGenome.scala
> -    val chainFilePath = fs.parseUrl(chainFile).toString
The URL is validated in the smart constructor for `LiftOver` by `restore`. That's all this parse + toString stuff is doing.

2025-01-30 21:23 UTC, patrick-schultz commented on hail/hail/src/is/hail/backend/Backend.scala
> -  def references: mutable.Map[String, ReferenceGenome]
Makes sense, thanks for explaining

2025-01-31 17:58 UTC, patrick-schultz commented on hail/hail/test/src/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
> +    ctx.local(flags = ctx.flags + ("shuffle_cutoff_to_local_sort" -> "40")) { ctx =>
Huh, I could have sworn I replied to this, but my comment seems to have disappeared.

Sorry, I should have been more specific. I just meant that it might be simpler for `ExecuteContext.local` to take a `overrideFlags: Seq[(String, String)] = Seq.empty`, so you could call `ctx.local(overrideFlags = Seq("shuffle_cutoff_to_local_sort" -> "40"))`. I.e. `local` overides individual flags in the scope, rather than the entire flags map.

But this is minor, so I'm happy to approve as is if you don't want to change it.

2025-01-31 18:27 UTC, ehigham commented on hail/hail/test/src/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
> +    ctx.local(flags = ctx.flags + ("shuffle_cutoff_to_local_sort" -> "40")) { ctx =>
Thanks, I see what you're getting at. But how would I unset flags? By mapping the value to null? yuck!
I think the current thing is simpler and so I'm inclided to keep it.

2025-01-31 18:29 UTC, patrick-schultz approved these changes

2025-01-31 18:29 UTC, merged