[Dev processes] Minor update to dev-docs regarding git hooks setup.
hail-is/hail pull request #14741
Opened 2024-10-22 15:31 UTC by grohli

## Change Description

Added instructions on node installation re: pyright usage (in case node is not installed during the initial `make`).

## Security Assessment

Delete all except the correct answer:
- This change has a low security impact
  - [ ] Required: The impact has been assessed and approved by appsec

### Impact Description

Just adding additional detail in the development-process.md document

(Reviewers: please confirm the security impact before approving)

2024-10-23 20:13 UTC, ehigham commented on dev-docs/development-process.md
> +will automatically install node for you, doing so through the above `make` may not. If it doesn't,
perhaps add to `hail/python/dev/requirements.txt` then rerun `make generate-pip-lockfiles`

2024-10-24 15:29 UTC, grohli commented on dev-docs/development-process.md
> +will automatically install node for you, doing so through the above `make` may not. If it doesn't,
Updated requirements.txt to install node too (in line with https://pypi.org/project/pyright/)

2024-10-24 19:15 UTC, ehigham commented on dev-docs/development-process.md
> +will automatically install node for you, doing so through the above `make` may not. If it doesn't,
Nice. With that you don't need the doc update. Now run
```
$ make generate-pip-lockfiles
```
and commit the changes to the various `pinned-requirements.txt`

2024-10-24 19:49 UTC, grohli commented on dev-docs/development-process.md
> +will automatically install node for you, doing so through the above `make` may not. If it doesn't,
Done and done.

2024-10-24 19:52 UTC, ehigham commented on dev-docs/development-process.md
> +will automatically install node for you, doing so through the above `make` may not. If it doesn't,
Nice. With that you don't need the doc update. Now run
```
$ make generate-pip-lockfiles
```
and commit the changes to the various `pinned-requirements.txt`

2024-10-24 20:49 UTC, ehigham approved these changes
This looks good and should make things easier for new devs. Thanks.

2024-10-30 13:20 UTC, patrick-schultz requested changes
Thanks for cleaning up the installation process! Can you just edit the impact description? It's still describing an old version of the pr.

2024-10-30 15:45 UTC, grohli commented
Updated impact description

2024-10-30 16:07 UTC, patrick-schultz approved these changes
Thanks Greg!

2024-10-30 16:44 UTC, merged