Added ability to check job status of individual job, made associated tests
hail-is/hail pull request #14751
Opened 2024-11-05 19:24 UTC by grohli

## Change Description

Fixes #<issue_number> (delete if N/A)

Brief description and justification of what this PR is doing.

## Security Assessment

Delete all except the correct answer:
- This change has a high security impact
  - [ ] Required: The impact has been assessed and approved by appsec
- This change has a medium security impact
- This change has a low security impact
- This change has no security impact

### Impact Description

For none/low impact: a quick one/two sentence justification of the rating.
  - Example: "Docs only", "Low-level refactoring of non-security code", etc.
For medium/high impact: provide a description of the impact and the mitigations in place.
  - Example: "New UI text field added in analogy to existing elements, with input strings escaped and validated against code injection"

(Reviewers: please confirm the security impact before approving)

2024-11-05 19:25 UTC, grohli commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/hail-is/hail/14751?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14751** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14751?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#14747** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14747?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14684** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14684?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#14686](https://github.com/hail-is/hail/pull/14686) <a href="https://app.graphite.dev/github/pr/hail-is/hail/14686?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#14683** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @grohli and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-05 19:34 UTC, ehigham requested changes

2024-11-05 19:34 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
> +            } yield (readPartitionResult(root, partIdx), partIdx)
This code is duplicated. Maybe add a little helper above (eg above line 294) to encapsulate this

2024-11-05 19:34 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
> +    val (jobGroup, startJobId) =
Can you add a comment about why the partition index is `jobId - startJobId`?

2024-11-05 20:48 UTC, ehigham commented on hail/src/test/scala/is/hail/services/BatchClientSuite.scala
> +    for (_ <- s) {}
Delete - this is unused

2024-11-05 20:48 UTC, ehigham commented on hail/src/test/scala/is/hail/services/BatchClientSuite.scala
> +    client = BatchClient(DeployConfig.get(), Path.of("/tmp/test-gsa-key/key.json"))
revert this line

2025-01-27 21:18 UTC, ehigham requested changes

2025-01-27 21:18 UTC, ehigham commented on hail/hail/src/is/hail/backend/service/ServiceBackend.scala
> +            new CancellationException(s"Job Group ${jobGroup.job_group_id} was cancelled.")
Revert this - there was more context in the last message

2025-01-28 16:38 UTC, grohli commented on hail/hail/src/is/hail/backend/service/ServiceBackend.scala
> +            new CancellationException(s"Job Group ${jobGroup.job_group_id} was cancelled.")
Updated

2025-01-28 20:23 UTC, chrisvittal requested changes
One style nit. Looks great otherwise.

2025-01-28 20:23 UTC, chrisvittal commented on hail/hail/src/is/hail/backend/service/ServiceBackend.scala
> +    // that that job corresponds to.
Reflow these comments so that they're all

```
/* This multiline block
 * comment style. */
```

2025-02-03 19:38 UTC, grohli commented
> One style nit. Looks great otherwise.

Fixed

2025-02-04 20:56 UTC, ehigham approved these changes
Great job with this - this really cleans up the error handling with the batch service backend!

2025-02-05 18:38 UTC, chrisvittal approved these changes
Looks great. Thanks for this.

2025-02-24 21:49 UTC, merged