[QoB] Set StreamReadConstraints maxStringLength as early as possible
hail-is/hail pull request #14750
Opened 2024-11-05 17:51 UTC by chrisvittal

resolves #14749

Leave the override in Backend as well to avoid duplication. Future enhancements may enable us to construct a ServiceBackend from argv alone, allowing this to be reverted.

## Security Assessment

Delete all except the correct answer:
- This change has no security impact

### Impact Description
This change restores known good functionality.

2024-11-05 17:56 UTC, ehigham submitted a review, later dismissed

2024-11-05 17:58 UTC, ehigham requested changes
This is the second time this has happened. Isn't it time we added a test to prevent this from happening again?

2024-11-05 19:15 UTC, chrisvittal commented
Waiting for my test to run on all 3 backends to see that it fails. Then I'll revert and it should pass.

2024-11-05 21:23 UTC, chrisvittal commented on hail/src/main/scala/is/hail/backend/service/Main.scala
> +    )
Sure, I'll try it.

2024-11-07 10:00 UTC, jmarshall commented
Some confirmation: Our large batch that previously failed on 0.2.133 with “String length (20013488) exceeds the maximum length (20000000)” has completed successfully when run on a patched QoB JAR, built from 0.2.133 plus this PR cherry-picked onto it. (Details in populationgenomics/production-pipelines#972.)

2024-11-07 17:55 UTC, ehigham approved these changes
Thanks for adding the test

2024-11-08 21:06 UTC, merged