[query] Extract Backend Methods called from Python into `Py4JBackendExtensions`
hail-is/hail pull request #14767
Opened 2024-12-16 18:49 UTC by ehigham

## Change Description

Fixes #<issue_number> (delete if N/A)

Brief description and justification of what this PR is doing.

## Security Assessment

Delete all except the correct answer:
- This change has a high security impact
  - [ ] Required: The impact has been assessed and approved by appsec
- This change has a medium security impact
- This change has a low security impact
- This change has no security impact

### Impact Description

For none/low impact: a quick one/two sentence justification of the rating.
  - Example: "Docs only", "Low-level refactoring of non-security code", etc.
For medium/high impact: provide a description of the impact and the mitigations in place.
  - Example: "New UI text field added in analogy to existing elements, with input strings escaped and validated against code injection"

(Reviewers: please confirm the security impact before approving)

2024-12-16 18:50 UTC, ehigham commented
* **#14731** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14731?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2  dependent PRs ([#14732](https://github.com/hail-is/hail/pull/14732) <a href="https://app.graphite.dev/github/pr/hail-is/hail/14732?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#14748](https://github.com/hail-is/hail/pull/14748) <a href="https://app.graphite.dev/github/pr/hail-is/hail/14748?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#14698** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14698?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14696** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14696?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14693** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14693?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14692** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14692?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14691** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14691?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14690** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14690?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14686** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14686?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14767** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14767?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/hail-is/hail/14767?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-17 20:13 UTC, patrick-schultz requested changes
This is great. I like how clear it makes it which methods are python endpoints. I just have a few small questions.

2025-01-17 20:56 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
> +  )
This was tricky to debug. We need to set the defaults before `com.fasterxml.jackson.core.JsonFactory` is initialised (which is initialised by spark).

That factory holds onto a copy of these constants and so subsequent calls to `overrideDefaultStreamReadConstraints` will have no effect after the factory is initialised. It's that instance that's used to determine max string length.

Moving it to each backend entry point makes it more likely we'll initialise the defaults first but there are no guarantees. Say someone provides their own spark context before the spark backend is initialised. They're likely to encounter this problem.

2025-01-17 20:57 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/Backend.scala
> +  def loadReferencesFromDataset(path: String): Array[Byte]
there are no references in the backend trait anymore.

2025-01-17 20:59 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
> +  override val references: mutable.Map[String, ReferenceGenome],
There are significant changes to how references are handled in the stack. Can you let this through for now.

2025-01-17 21:04 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/py4j/Py4JBackendExtensions.scala
> +  def persistedIR: mutable.Map[Int, BaseIR]
Thanks. This is an artefact from trying to pick apart multiple changes into separate reviews. I'll persistedIR is be removed from the backend trait in a subsequent change.

2025-01-17 21:07 UTC, ehigham commented on hail/src/main/scala/is/hail/backend/Backend.scala
> +  def loadReferencesFromDataset(path: String): Array[Byte]
This is another artefact of trying to pick apart changes. 
The `references` in `Backend` are only used testing (in `StagedMinHeapSuite`).
The next PR in the stack cleans this up.

2025-01-17 21:24 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/backend/Backend.scala
> +  def loadReferencesFromDataset(path: String): Array[Byte]
Totally fine, thanks!

2025-01-17 21:27 UTC, patrick-schultz approved these changes
Looks good, on to the next!

2025-01-21 14:41 UTC, chrisvittal approved these changes
Really like this change. Looks great!

2025-01-21 16:37 UTC, merged