ApproxCDF bugfix
hail-is/hail pull request #14765
Opened 2024-12-12 17:25 UTC by patrick-schultz

## Change Description

Fixes #<issue_number> (delete if N/A)

Brief description and justification of what this PR is doing.

## Security Assessment

Delete all except the correct answer:
- This change has a high security impact
  - [ ] Required: The impact has been assessed and approved by appsec
- This change has a medium security impact
- This change has a low security impact
- This change has no security impact

### Impact Description

For none/low impact: a quick one/two sentence justification of the rating.
  - Example: "Docs only", "Low-level refactoring of non-security code", etc.
For medium/high impact: provide a description of the impact and the mitigations in place.
  - Example: "New UI text field added in analogy to existing elements, with input strings escaped and validated against code injection"

(Reviewers: please confirm the security impact before approving)

2024-12-12 17:25 UTC, patrick-schultz commented
* **#14765** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14765?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/hail-is/hail/14765?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-12 17:54 UTC, chrisvittal requested changes
Looks great, I have one suggestion to simplify the parameters you added to the fixture.

2024-12-12 17:54 UTC, chrisvittal commented on hail/python/test/hail/expr/test_expr.py
> +@pytest.fixture(scope='module', params=[0, 1])
```suggestion
@pytest.fixture(scope='module', params=(True, False))
```

2024-12-12 17:54 UTC, chrisvittal commented on hail/python/test/hail/expr/test_expr.py
> +        if request.param == 0:
```suggestion
        if request.param:
```

2024-12-12 18:07 UTC, patrick-schultz commented
Done!

2024-12-12 18:42 UTC, ehigham approved these changes
Well done for finding and fixing this so quickly

2024-12-13 14:23 UTC, chrisvittal approved these changes

2024-12-13 14:23 UTC, merged