ir gen mvp
hail-is/hail pull request #14771
Opened 2024-12-17 16:57 UTC by patrick-schultz

## Change Description

Fixes #<issue_number> (delete if N/A)

Brief description and justification of what this PR is doing.

## Security Assessment

Delete all except the correct answer:
- This change has a high security impact
  - [ ] Required: The impact has been assessed and approved by appsec
- This change has a medium security impact
- This change has a low security impact
- This change has no security impact

### Impact Description

For none/low impact: a quick one/two sentence justification of the rating.
  - Example: "Docs only", "Low-level refactoring of non-security code", etc.
For medium/high impact: provide a description of the impact and the mitigations in place.
  - Example: "New UI text field added in analogy to existing elements, with input strings escaped and validated against code injection"

(Reviewers: please confirm the security impact before approving)

2024-12-17 16:57 UTC, patrick-schultz commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/hail-is/hail/14771?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14771** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14771?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/hail-is/hail/14771?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#14769** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14769?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-02-21 18:37 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +  val binding: AttOrChildPack
Is there any reason to not make these ordinary `def`?

2025-02-25 20:39 UTC, ehigham requested changes
This is a really cool change. It's clear you've invested a great deal of thought.
Most of my comments are fairly non-functional or particular to my sensibilities. They're just suggestions. Some renaming might help readability. Moving default implementations out of the base DSL trait I think would be a great improvement. Nonetheless thanks for this lift.

2025-02-25 20:39 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +              childrenOffsets(i),
This looks like it's calling `childrenOffsets` for every `attrsAndChildren`. Is there a reason for this? Would something like the following work?
```scala
(attsAndChildren, childrenOffsets).zipped.map { (attOrChild, offset) => .. }
```

2025-02-25 20:39 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +            assert(false, name)
What's not implemented here? Wouldn't the exception stack trace show us this better?

2025-02-25 20:39 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +             else "")
Do you need the extra newline characters? Couldn't you just fold over the `constraints`? 
```scala
constraints.foldLeft("") { (out, c) => out ++ s"  require($c)\n" }
constrains.view.map(c => s"  require($c)").mkString("\n")
```

2025-02-25 20:39 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +    else ""
maybe make these locals in `generateDef`

2025-04-17 16:28 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  val binding: AttOrChildPack
Nope, I suppose not

2025-04-17 16:54 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  def att(typ: String): AttOrChildPack
Though now that I'm revisiting this after some time away, I think another possibility would be to rewrite `MakeStruct` and similar cases to take separate arrays of names and children, and to hand-write custom apply and unapply methods to preserve the current interface. I think there's few enough cases that the hand-written code wouldn't be burdensome, and it would likely be a significant simplification of the codegen implementation. I'll have to think about it.

2025-04-17 17:02 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  def ApplyNode(missingnessAware: Boolean = false): Trait
I agree it's not the clearest name, but I think it's most important that the terms used in the codegen match the terms used in the rest of the codebase. And as the comment indicates, this controls whether the apply node uses `UnseededMissingnessAwareJVMFunction` or `UnseededMissingnessObliviousJVMFunction`.

I'm certainly not opposed to changing those names, but I'd rather keep that separate from this PR. And `supportsOptionals` isn't really right either. A "missingness oblivious" function is defined on non-missing values, then automatically extended to propagate missingness in any of it's inputs (the function is "strict"). A "missingness aware" function is one that can return a non-missing result even when one or more inputs are missing, like `is_missing`, so the definition must be "aware" of the missingness of its inputs.

2025-04-23 20:14 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  def child(t: String): AttOrChildPack
My inclination is to keep the terminology consistent between the generating code and the generated code. Changing the terminology in the generating code would be a trivial change in the future if we decide to.

2025-04-23 20:24 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  def child(t: String): AttOrChildPack
I agree re. `child`, but disagree about the default names. The fact that using `child` directly without giving an explicit name creates a field named "child" is part of the interface, not an implementation detail. Someone using this interface to generate IR node definitions should know exactly what they're generating. And if we someday use the same interface to generate IR definitions in both Scala and Python, we'd want the field names to be consistent (so the default field names should be fixed by the interface).

2025-04-23 20:31 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +    def ? : AttOrChildPack
All the interfaces on the abstract types could probably be extension methods instead, but that feels clunkier to me, and I'm not sure what the benefit would be. I'm open to discussion though.

2025-04-23 20:37 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +            assert(false, name)
That was stray debugging code; gone now.

2025-04-23 20:42 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  trait IR_Interface {
I've changed a lot of the names, but I'm still using the "Interface" suffix (without an underscore). It feels clearer to me than "Like", but let me know if you still don't like "Interface" with the other changes.

2025-04-23 20:52 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +             else "")
Sorry, I don't follow. Are both lines there part of the same suggestion?

One of the newlines there is just to put a blank line separating constraints from extra methods from standard generated methods. That's just a personal choice, and arguably we should configure the build system to always run scalafmt over the generated source anyways, but I haven't done that yet.

2025-04-23 21:00 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +    else ""
I tried it, but if I move `classDef` inside, then it feels like `classBody`, and by extension `copyMethod` and others, should also be inside. But then `generateDef` is too big and deeply nested.

2025-05-02 14:24 UTC, patrick-schultz commented
Fixed up some bugs I introduced when merging in my other old branch. Should be ready for re-review.

2025-05-09 21:40 UTC, ehigham requested changes
This is such an improvement from when i last saw this. I really like the possibilities this opens up! A few small comments, nothing too contraversial!

2025-05-09 21:40 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/Children.scala
> -package is.hail.expr.ir
Very nice :)

2025-05-09 21:40 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/Copy.scala
> -package is.hail.expr.ir
red is the gods' colour.

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +  def in[T](name: String, pack: ConstrainedType[T]): Declaration[T]
"input"

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +      val constraints = this.constraints ++ attsAndChildren.flatMap(_.constraints)
Not a huge issue, I think of "constraints" as being the type constraints in class or method definitions like
```scala
def launchTheAribitraryMissiles[A: Arbitrary]: Unit
```

Since you're using these to generate "require" statements, perhaps call them "requirements"? Or just "valueConstraints"?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +    r += node("I32", in("x", att("Int"))).withTraits(TrivialIR)
A nice addition would be to make all these `TypedIR` to avoid casting.
Feel free to dismiss or defer to a later change.

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +      .withCompanionExtension
Why not always generate companion objects and extensions thereof?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +      .withMethod(
this method just seems to accept arbitrary code snippets rather than methods.
Perhaps call it "withPreamble" or something?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +        """// expensive, for debugging
This has given me the idea to write a macro that includes this code if we're building in debug mode - would be nicer than having to find and uncomment all this stuff!

2025-05-09 21:40 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +      assert(_typ != null)
Is `null` a valid return from `InferType`?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +  trait TrivialIR extends IR
why remove `sealed`?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +  def in[T](name: String, pack: ConstrainedType[T]): Declaration[T]
Maybe worthwhile constraining `T` to be not `Child` as not all `Child`s are inputs?

2025-05-09 21:40 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +  trait BaseRef extends IR with TrivialIR {
not sealed?

2025-05-09 21:40 UTC, ehigham commented on hail/python/install-editable
revert

2025-05-12 16:10 UTC, patrick-schultz commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +      assert(_typ != null)
No, `InferType` should assign a type to every node. I believe I added this because I ran into a bug where a type did remain null. I don't remember what happened, but since `InferType` often just lifts types from children, one potential failure mode is to call `InferType` on a node when some of its children still have null types.

2025-05-12 16:10 UTC, patrick-schultz commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +  trait TrivialIR extends IR
`sealed` requires all subclasses be defined in the same file as the trait. Anyways, I think match statements that exhaustively list every IR node are a code smell, and I'm not sure we actually have any that benefit from exhaustivity checking.

2025-05-12 16:10 UTC, patrick-schultz commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +  trait BaseRef extends IR with TrivialIR {
It can't be; see above.

2025-05-12 17:12 UTC, ehigham approved these changes
This is great, thanks for addressing my comments and concerns

2025-05-12 17:12 UTC, ehigham commented on hail/hail/src/is/hail/expr/ir/IR.scala
> +  trait TrivialIR extends IR
Oh I see, thanks.

2025-05-12 17:15 UTC, ehigham commented on hail/hail/ir-gen/src/Main.scala
> +    def ? : AttOrChildPack
# https://api.github.com/users/github-actions%5Bbot%5D

2025-05-12 18:04 UTC, patrick-schultz commented on hail/hail/ir-gen/src/Main.scala
> +  def in[T](name: String, pack: ConstrainedType[T]): Declaration[T]
Good point. That's a distinction I want to make, but we don't yet. If I update the codegen to be able to generate the `Binds.scala` stuff, we'll probably make "inputs" and "blocks" different kinds of children.

2025-05-12 19:07 UTC, chrisvittal approved these changes
Thanks for taking point on this review Ed! Looks great Patrick!

2025-05-12 19:08 UTC, merged