[batch] spending limit kill switch for a billing project
hail-is/hail pull request #9355
Opened 2020-08-27 15:12 UTC by jigold

Stacked on #9354

I'm happy with the tests here.

2020-08-28 20:32 UTC, danking submitted a review, later dismissed

2020-08-28 20:32 UTC, danking commented on batch/batch/front_end/front_end.py
> +        await asyncio.sleep(30)
This kind of feels like something the driver should do. Sometimes we scale up to ~10 front ends. We don't want to hammer the DB with 10 of these queries.

2020-10-07 16:01 UTC, danking requested changes
Looks great, just some organization and SLO things

2020-10-07 16:01 UTC, danking commented on batch/test/test_batch.py
> +            assert batch['state'] == 'cancelled', batch
I feel confident this test will fail, but I want something even stronger. If the cancel test runs every ten seconds, then I shouldn't overspend by, say, more than 30 seconds? Or at least one minute?
```python3
try:
    batch = client.create_batch()
    j1 = batch.create_job('ubuntu:18.04', command=['sleep', '5'])
    j2 = batch.create_job('ubuntu:18.04',
                          command=['/bin/bash', '-c', 'while true; do; sleep 3600; done'],
                          parents=[j1])
    batch = batch.submit()
    status = batch.wait()
    assert status['state'] == 'cancelled', batch
    jobs = {b['job_id']: b for b in batch.jobs()}
    assert jobs[2]['msec_mcpu'] < 30_000 * 125  # 30s on 125mCPU
```
Hmm. Oddly we don't have durations for cancelled jobs?

2020-10-23 20:53 UTC, jigold commented on batch/batch/front_end/front_end.py
> -FROM (
The rebase for this was horrendous. Can you double check the query is still correct in utils.py?

2020-10-26 14:30 UTC, danking requested changes

2020-10-26 14:30 UTC, danking commented on batch/batch/batch.py
> +    WHERE user = %s AND id = %s AND NOT deleted;
this needs a FOR UPDATE

2020-10-26 15:40 UTC, jigold commented on batch/batch/utils.py
> +LOCK IN SHARE MODE;
@danking I added a LOCK IN SHARE MODE here. Double check that please.

2020-10-26 15:40 UTC, jigold commented
@danking  See comment. Otherwise, should be good to go.

2020-10-26 15:46 UTC, danking approved these changes
lgtm

2020-10-26 16:46 UTC, merged