[query] refactor block matrix persistence to take backend context
hail-is/hail pull request #9421
Opened 2020-09-08 18:35 UTC by catoverdrive

I need to use the backend context while persisting in order to support this with user separation on the service. I also moved the methods onto the general backend in preparation for implementing this on the service backend.

2020-09-08 19:53 UTC, patrick-schultz requested changes
A couple minor questions/suggestions, otherwise looks good

2020-09-09 17:00 UTC, catoverdrive commented on hail/src/main/scala/is/hail/backend/Backend.scala
> +  def unpersist(backendContext: BackendContext, id: String): Unit
Yeah, I changed this with the idea that we'd just overload on the type of `value` for persist and that the ids would be unique across all types for `unpersist`

2020-09-09 17:31 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/backend/Backend.scala
> +  def unpersist(backendContext: BackendContext, id: String): Unit
Makes sense, thanks.

2020-09-09 17:31 UTC, patrick-schultz approved these changes

2020-09-11 20:36 UTC, catoverdrive commented
@patrick-schultz I'm sending this back to you because I made some pretty drastic changes trying to fix some errors.

The biggest non-refactoring change that the original this introduces is that we can't parse IR for a persisted block matrix reader if the persisted block matrix doesn't exist. (This makes some amount of sense if you consider that we also can't parse the IR for a native block matrix reader if the file doesn't exist.)

This led me down a rabbit hole of test failures since we're parsing IR/types a fair number of times, through the execution and after we get the result. After fiddling with it for a little bit, I removed UnpersistBlockMatrix. I'm not sure what I was thinking when I added it. I re-added an "unpersist" function to the backend to handle unpersisting BlockMatrices. It differs from the current Table/MatrixTable unpersist functions in that we only pass the id of the thing we want to unpersist, not the entire IR, since that's all we need.

2020-09-14 16:50 UTC, patrick-schultz requested changes
Looks fine to me, just one unused import

2020-09-14 16:50 UTC, patrick-schultz commented on hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
> +import org.testng.annotations.{BeforeClass, DataProvider, Test}
Doesn't look like this is being used.

2020-09-15 17:43 UTC, patrick-schultz approved these changes

2020-09-15 18:11 UTC, merged