emitI NDArrayQR
hail-is/hail pull request #9440
Opened 2020-09-11 17:24 UTC by johnc1231

After this and #9438 go in, all NDArray IR nodes will be moved to `emitI`, making it easier for me to update `NDArrayEmitter` to use `EmitCodeBuilder` and `PCode`. I cleaned up `NDArrayQR` a little bit in this PR, but all the low level LAPACK stuff means it's still kind of a mess.

2020-09-15 19:11 UTC, johnc1231 commented
Bump

2020-09-15 20:12 UTC, chrisvittal commented
Thanks for the reminder. Looking now.

2020-09-15 21:21 UTC, chrisvittal requested changes
This code doesn't feel very imperative. If we're going to port it, we should also probably do things like using PCode/PValue methods and updating some of the fields we generate into locals (since method splitting is in).

2020-09-15 21:21 UTC, chrisvittal commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +          ))
You use `computeHAndTau` in both branches, this indicates that the setup could just exist on the CodeBuilder.

2020-09-15 21:21 UTC, chrisvittal commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +              val computeCompleteOrReduced = Code(Code(FastIndexedSeq(
This is another long stretch of code that could largely be placed on the CodeBuilder.

2020-09-15 21:21 UTC, chrisvittal commented on hail/src/main/scala/is/hail/expr/ir/Emit.scala
> +              val qCondition = mb.genFieldThisRef[Boolean]()
In new code, with method splitting, there should be no reason to generate fields.

2020-09-16 14:29 UTC, johnc1231 commented
On the first pass, I had just moved things to CodeBuilder when I thought it improved readability. After your comments, I just moved everything.

2020-09-16 15:17 UTC, chrisvittal approved these changes
LGTM. Great work!

2020-09-17 14:01 UTC, merged