[aiogoogle, aiotools] added statfile, listfiles
hail-is/hail pull request #9451
Opened 2020-09-15 21:56 UTC by cseed

Current plan going forward for this:
 - I'm getting pretty happy with the interface (but maybe want to rename some things).  I think I will document what I have next.
 - Get rid of legacy hailtop.GCS.  This means we can get rid of all the client libraries except the oauth2 flows in auth.
 - The add a glob operation.
 - Add a copy/sync operation.

I might also add an S3AsyncFS.  I could have used that recently.

2020-09-16 17:36 UTC, jigold requested changes

2020-09-16 17:36 UTC, jigold commented on hail/python/hailtop/aiogoogle/client/storage_client.py
> +            self._status = GetObjectFileStatus(self._items)
I think you're missing a return here.

2020-09-16 17:36 UTC, jigold commented on hail/python/hailtop/aiogoogle/client/storage_client.py
> +            name = f'{name}/'
So this method assumes we're always passing a directory.

2020-09-16 17:36 UTC, jigold commented on hail/python/hailtop/aiogoogle/client/storage_client.py
> +        return self._items[key]
self._items can be None in the case of a directory.

2020-09-16 17:36 UTC, jigold commented on hail/python/hailtop/aiogoogle/client/storage_client.py
> +                    yield GoogleStorageFileListEntry(f'gs://{bucket}/{item["name"]}', True, item)
This will allow an object that ends in a slash. Maybe we just ignore it as if it didn't exist here?

2020-09-16 17:36 UTC, jigold commented on hail/python/hailtop/aiogoogle/client/storage_client.py
> +                        url = url[:-1]
So is the contract here that every GoogleStorageFileListEntry must not end in a '/'

2020-09-16 17:36 UTC, jigold commented on hail/python/test/hailtop/test_aiogoogle.py
> +        await fs.statfile(f'{base}/dir')
Can you also add a check for `{base}/dir/`?

2020-09-16 17:36 UTC, jigold commented on hail/python/test/hailtop/test_aiogoogle.py
> +    assert await listfiles(f'{base}/foo', recursive=True) == {(a, True), (c, True)}
Can you also add tests for `{base}/foo/`?

2020-09-16 20:35 UTC, jigold commented on hail/python/hailtop/aiotools/fs.py
> +class FileListEntry(abc.ABC):
I think FileListEntry is fine. I'm not sure what I was thinking earlier.

2020-09-22 00:04 UTC, cseed reviewed
OK, I think I addressed all your comments.  Two points I clarified:

1. FileStatus only refers to files.  It can come from two places: statfile, which throws not found if the path doesn't exist and is a real file, or from FileListEntry.entry, which throws ValueError if the entry is not a file.

2. Paths which are directories always have a trailing slash.  If a function (e.g. listfiles) can only take a slash, the slash is optional (like on the traditional UNIIX interface).  In the current interface, you always know if a path is referring to directory or a file, so all incoming trailing slashes are optional.  Returned paths that are directories will always have a trailing slash.

I'm not totally convinced by this interface.  Let's see what happens when we get to implementing copy/sync method.

2020-09-28 14:09 UTC, jigold approved these changes

2020-10-14 19:54 UTC, merged