[hail] Fix memory leak in BM and make cache size configurable
hail-is/hail pull request #9501
Opened 2020-09-24 15:21 UTC by danking

CHANGELOG: Remove memory leak in `BlockMatrix.to_matrix_table_row_major` and `BlockMatrix.to_table_row_major`. Also, make the cache size used in both methods configurable.

The `ref` variable was holding entire blocks in memory for no reason. It was a
vestiage of debugging. Moreover, the configurable cache permits users to fine tune
memory usage.

2020-09-24 17:05 UTC, johnc1231 requested changes
Docs fixes, otherwise good.

2020-09-24 18:10 UTC, danking commented on hail/python/hail/linalg/blockmatrix.py
> +            every block. Larger values reduce the number of network requests. If
I fixed the verbiage. Latter should have said one partition.

2020-09-24 21:11 UTC, johnc1231 commented
KING tests are failing

2020-09-24 21:11 UTC, johnc1231 requested changes
Tests are failing

2020-09-25 13:47 UTC, johnc1231 approved these changes

2020-09-25 13:47 UTC, merged