[query] Support indexed table reads in lowered execution
hail-is/hail pull request #9522
Opened 2020-09-29 21:26 UTC by tpoterba

2020-09-30 15:38 UTC, tpoterba commented
a large diff, but not that complex. The changes to Emit/EmitStream are rote -- adding `ctx` to the EmitStreamContext and entry points.

The design here (serializing the unstaged closures to generate decoders and such) is pretty gross, and I intend to fix this when we have infrastructure to mix interpreted TableIRs and lowered TableStages, and we can remove the interpreted indexed reader.

2020-10-05 19:58 UTC, patrick-schultz requested changes
Sorry for the delay. Just a couple nits.

2020-10-05 19:58 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/expr/ir/TableIR.scala
> +                .handle(cb, cb._fatal(""))
You can use `IEmitCode.get` when you don't have a specific error message.

2020-10-05 19:58 UTC, patrick-schultz commented on hail/src/main/scala/is/hail/expr/ir/TableIR.scala
> +//    val rowsPath = spec.rowsComponent.absolutePath(params.path)
Delete commented out old code?

2020-10-06 14:23 UTC, tpoterba commented
addressed, thanks for the comments.

2020-10-06 14:29 UTC, patrick-schultz approved these changes

2020-10-06 15:05 UTC, merged