[batch] Teach BatchPoolExecutor how to handle container errors
hail-is/hail pull request #9543
Opened 2020-10-01 23:41 UTC by danking

CHANGELOG: BatchPoolExecutor now raises an informative error message for a variety of "system" errors, such as missing container images.

If the main container fails for reasons beyond BatchPoolExecutor's control, such
as a missing container image, we previously did not report these errors. In
fact, we encountered errors when trying to load the output file that cannot
exist if the main container errors.

Smaller included changes:
- directly use the asynchronous, low-level client instead of the synchronous,
  low-level client
- introduce an `async_cancel` now that we have access to the async client.

2020-10-01 23:41 UTC, danking commented
Hey, @chrisvittal, I assigned to you for curiosity's sake. If you don't want to review it on Friday, just send it to Jackie.

2020-10-02 12:53 UTC, chrisvittal requested changes
Interesting! Seems that there's one logic error here.

2020-10-02 12:53 UTC, chrisvittal commented on hail/python/hailtop/batch/batch_pool_executor.py
> +    async def cancel(self):
should still be sync.

2020-10-02 13:38 UTC, danking commented on hail/python/hailtop/batch/batch_pool_executor.py
> +    async def cancel(self):
Indeed

2020-10-02 14:07 UTC, chrisvittal approved these changes

2020-10-02 14:08 UTC, merged