[docker] Infrastructure for moving third party images to gcr
hail-is/hail pull request #9660
Opened 2020-10-30 15:07 UTC by jigold

`make -C docker/third-party copy`

2020-10-30 19:42 UTC, jigold commented
Maybe this is a better solution?

https://cloud.google.com/container-registry/docs/pulling-cached-images

2020-10-30 21:33 UTC, danking requested changes
Looks fine, one error.

2020-10-30 21:33 UTC, danking commented on docker/third-party/copy_images.sh
> +    echo ERROR: GCR_PROJECT must be set before running this
no GCR_

2020-11-02 17:22 UTC, danking approved these changes

2020-11-02 18:27 UTC, merged