[batch] maybe fix cp dirs
hail-is/hail pull request #9787
Opened 2020-12-04 01:57 UTC by danking

2020-12-04 15:02 UTC, jigold requested changes

2020-12-04 15:04 UTC, jigold commented on batch/batch/worker/worker.py
> +        target_directory = os.path.dirname(dst)
This is specifically for the source. I'm worried about `gs://hail-jigold/`

2020-12-04 15:04 UTC, jigold commented on batch/batch/worker/worker.py
> +        target_directory = os.path.dirname(dst)
Maybe not, actually. Forget this comment.

2020-12-04 16:10 UTC, jigold submitted a review, later dismissed

2020-12-04 16:10 UTC, jigold commented on batch/batch/worker/worker.py
> +        target_directory = os.path.dirname(dst)
Maybe this needs to be `os.path.dirname(dst.rstrip('/') + '/')`?

2020-12-04 16:10 UTC, jigold commented on batch/batch/worker/worker.py
> +        target_basename = os.path.basename(dst)
Same here. We are assuming that dst is a directory.

2020-12-07 22:08 UTC, danking commented on batch/batch/worker/worker.py
> +    src = src.rstrip('/')  # ensure that the source_basename is always non-empty
@jigold this was the bug. I believe it will work now.

2020-12-07 22:36 UTC, jigold approved these changes

2020-12-07 22:37 UTC, merged