[format] black formatting
hail-is/hail pull request #9931
Opened 2021-01-26 20:00 UTC by daniel-goldstein

@danking Here's what it looks like running black on `ci.py` and `address.py` with only customizations being a line length of 120 (I personally prefer shorter but that's what we have currently) and no single quote -> double quote changes (`--skip-string-normalization`).

It is _super_ opinionated, so you have to like the defaults or be willing to roll with it on some calls. It took a lot of [discourse](https://github.com/psf/black/issues/118) just to allow single-quoting strings, but a commit hook to auto-format service code seems useful.

2021-01-26 20:30 UTC, danking commented
I have no qualms with this.

I do hate double quotes, but I guess he's right that black could just reformat my single quotes into double quotes.

2021-01-26 20:32 UTC, danking commented
Looks like I can just enable this with elpy in Emacs. What else would we do? Set a git hook?

2021-01-26 20:33 UTC, danking commented
We can probably turn flake8 off. I don't know what good it provides over pylint and mypy.

2021-01-26 21:32 UTC, daniel-goldstein commented
Ya I'll see if `pylint` and `mypy` give good enough coverage, and whether they fight with `black` over anything. Something useful from that thread was they point out how a big formatting commit ruins git blame unless you account for it.

I think just a pre-commit hook is good, anyone who wants to set it up in their editor can do so fairly easily.

2021-01-28 00:51 UTC, vladsaveliev commented
Hi,

I'm just curious if you tried black on a code that uses Hail query. As far as I see, PEP8 conflicts with the code style adopted in the Hail docs, e.g. black would remove spaces in named function arguments:

```
- mt = mt.annotate_entries(GT = lgt_to_gt(mt.LGT, mt.LA))
+ mt = mt.annotate_entries(GT=lgt_to_gt(mt.LGT, mt.LA))
```

On the other hand, query can be seen as a DSL on top of Python, so the same guidelines probably don't need to be applied to it. Wondering if you had thoughts about lining the query code? We will be writing a lot of that in the nearest future in the Centre for Population Genomics, and would love to set up some style checks, or even automate that with a tool like black or prettier.

And on black - are you considering automating code refactoring with black as part of the CI? Or you wanted to just do checks, alongside with pylint?

Vlad

2021-01-28 02:00 UTC, tpoterba commented
> On the other hand, query can be seen as a DSL on top of Python, so the same guidelines probably don't need to be applied to it

You've hit exactly on the center of a longstanding discussion on the team with no definitive resolution 😄

2021-01-28 14:14 UTC, daniel-goldstein commented
Great question! I have not thought to run black on query and agree with your point about it maybe not being a good match. The intention here was just for formatting internal python services. Even so I don't love quite how restrictive black is, but it does seem like the most popular formatter out there now.

2021-01-28 14:55 UTC, danking commented
FWIW, when I write hail code, I usually write it in PEP8 style because my editor complains. I've grown accustomed to it. I am in favor of blackening everything for consistency.

Re: CI, I think we'll ban (non-hail-query) code that doesn't conform to Black and developers are then incentivized to add a git-hook or editor modification that runs black.

2021-01-28 15:19 UTC, daniel-goldstein commented
I'm going to change this branch to instead add `pre-commit` with `black` as one of its commit hooks. Developers can choose to `pre-commit install` which will set up useful hooks and run `black` over any modified files for directories that opt into it (which I'll start as just CI).

2021-01-28 16:07 UTC, danking requested changes

2021-01-28 16:07 UTC, danking commented on hail/python/dev-requirements.txt
> +pre-commit==2.9.2
should `black` be included here?

2021-01-28 16:07 UTC, danking approved these changes
Disregard, I understand now.

2021-01-28 16:08 UTC, danking requested changes
Can we also enforce this with a build.yaml step that verifies that `ci/` is blackened?

2021-01-28 16:34 UTC, daniel-goldstein commented
There's a `--check` flag, I added it to the existing ci `check`. Had to add `black` to the dev dependencies for that.

2021-01-28 16:38 UTC, danking approved these changes

2021-01-28 16:38 UTC, danking commented
Remove draft whenever you're ready. Looks good to me.

2021-01-28 18:14 UTC, merged