[vep] Rework VEP with more visibility
hail-is/hail pull request #9973
Opened 2021-02-02 19:47 UTC by tpoterba

1. Don't ignore parse errors by default. These shouldn't be happening
   with modern VEP versions anyway (they were caused by genes named NaN
   or something in older versions)
2. Don't silently drop variants that don't have a match in VEP. All keys
   coming in will have a row coming out with a VEP annotation (maybe NA)
   and a partition/block index.

2021-02-02 20:22 UTC, chrisvittal approved these changes

2021-02-02 20:53 UTC, johnc1231 commented
Not compiling

2021-02-02 22:34 UTC, chrisvittal requested changes

2021-02-02 22:34 UTC, chrisvittal commented on hail/python/hail/methods/qc.py
> +def vep(dataset: Union[Table, MatrixTable], config=None, block_size=1000, name='vep', csq=False, tolerate_parse_error=False):
Missed this first go, keyword only for the new parameter?

2021-02-03 00:16 UTC, chrisvittal approved these changes

2021-02-03 16:56 UTC, merged