[batch] eliminate expected exceptional log statement
hail-is/hail pull request #9980
Opened 2021-02-03 15:58 UTC by danking

If there is a true issue, we raise the exception which is caught and printed by
docker_call_retry, or, if that re-raises, it is stored as an error and serialized
back to the driver in Container.run

2021-02-03 16:00 UTC, jigold requested changes
I added all the log.exception messages in other operations below. We should get rid of those as well.

2021-02-08 15:53 UTC, danking commented on batch/batch/worker/worker.py
> -                raise
this isn't a subtype of any of the other caught errors, so there's no need to catch and raise

2021-02-08 15:54 UTC, danking commented
OK, I eliminated a bunch of `log.exception` that are either retried or re-raised. I completely eliminated some of them and in other cases I downgraded them to warning.

2021-02-08 16:04 UTC, jigold approved these changes

2021-02-08 16:56 UTC, merged