[ci] link to batch from job page
hail-is/hail pull request #9993
Opened 2021-02-04 20:24 UTC by daniel-goldstein

2021-02-11 15:33 UTC, daniel-goldstein commented
bump

2021-02-17 21:09 UTC, jigold commented
I think this is a temporary fix as we want Batch to directly return these pages. @CDiaz96 and I will start thinking about how this should be done in Batch more generally tomorrow.

2021-02-17 21:15 UTC, daniel-goldstein commented
Ok, happy to close if you're working on a solution.

2021-02-19 16:31 UTC, jigold commented
I think your solution is better right now.

2021-02-19 16:32 UTC, jigold requested changes

2021-02-19 16:32 UTC, jigold commented on ci/ci/templates/job.html
> +    </form>
Sorry to nitpick. Can we get another new line after the form?

2021-02-19 21:05 UTC, jigold approved these changes

2021-02-19 21:05 UTC, merged